import type {Env} from './types.ts';
import {improvements} from './improvements.ts';
import {readDocument,digest} from './storage.ts';
import {documentId} from './business-scope.ts';
import {emptyState} from '../lib/improvements/model.ts';
import type {Identity} from '../lib/access.ts';
export async function scheduledImprovements(env:Env){const owner=await env.DB.prepare("SELECT id,company_id,name,email,version FROM users WHERE role='owner' AND active=1 LIMIT 1").first<{id:string;company_id:string;name:string;email:string;version:number}>();if(!owner)return;const user:Identity={id:'scheduler:'+owner.id,companyId:owner.company_id,name:owner.name,email:owner.email,version:owner.version,role:'owner',grants:[]};const businesses=(await env.DB.prepare('SELECT id FROM businesses WHERE company_id=?').bind(user.companyId).all<{id:string}>()).results;const date=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}),hour=Number(new Date().toLocaleTimeString('en-GB',{timeZone:'Asia/Tokyo',hour:'2-digit',hour12:false}));let count=0;
 for(const business of businesses){const id=documentId(business.id,'improvements'),doc=await readDocument(env.DB,id,emptyState),p=doc.data.policy;if(!p.scheduled||p.paused||hour<p.hour)continue;const rid='scheduled-'+date;const done=await env.DB.prepare('SELECT id FROM receipts WHERE id=?').bind(id+':'+rid).first();const completed=await env.DB.prepare('SELECT id FROM receipts WHERE id=?').bind(id+':'+rid+'-complete').first();if(completed)continue;if(count++>=5)break;const call=async(action:string,extra:object={},requestId=rid)=>{const d=await readDocument(env.DB,id,emptyState);return improvements(new Request('https://astra.internal/api/marketing/improvements',{method:'POST',body:JSON.stringify({action,requestId,expectedVersion:d.data.version,...extra})}),env,user,business.id);};try{if(!done){const response=await call('diagnose');if(!response.ok)continue;}if(p.allowModel){const modelDone=await env.DB.prepare('SELECT id FROM receipts WHERE id=?').bind(id+':'+rid+'-model').first();if(!modelDone){const response=await call('model',{},rid+'-model');if(!response.ok)continue;}}if(p.mode==='auto'){const latest=await readDocument(env.DB,id,emptyState);for(const c of latest.data.cases.filter(c=>c.phase==='draft'&&p.allowed.includes(c.operation)&&(!p.funnelIds.length||p.funnelIds.includes(c.funnelId))).slice(0,p.maxPerDay)){await call('prepare',{caseId:c.id},rid+'-'+(await digest(c.id)).slice(0,32));}}await env.DB.prepare('INSERT OR IGNORE INTO receipts(id,signature,document_id) VALUES(?,?,?)').bind(id+':'+rid+'-complete','scheduled-complete',id).run();}catch{/* Each completed action remains in the business history; the next hourly invocation can retry uncommitted diagnosis. */}}
}
