import {advertisingEvidence} from './ads-evidence.ts';
import type {Env} from './types.ts';
import {can,type Identity} from '../lib/access.ts';
import {readDocument,commitDocument,digest,Conflict} from './storage.ts';
import {documentId} from './business-scope.ts';
import {emptyBusiness,type BusinessData} from '../lib/marketing-business/types.ts';
import {validateBusiness} from '../lib/marketing-business/validate.ts';
import {validDate,type Fact} from '../lib/analytics/model.ts';
import {emptyState,validateCase,validatePolicy,gate,detect,experimentResult,text,type State,type Improvement,type Run,type Operation} from '../lib/improvements/model.ts';
import {commitWithTarget} from './improvement-store.ts';
import {reason} from './improvement-model.ts';
import type {PostizDraft} from '../lib/postiz/types.ts';
const json=(b:unknown,status=200)=>Response.json(b,{status});
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});
async function facts(env:Env,scope:string,start:string,end:string){const r=await env.DB.prepare('SELECT data FROM analytics_rows WHERE business_id=? AND date>=? AND date<=? ORDER BY date,id LIMIT 10001').bind(scope,start,end).all<{data:string}>();if(r.results.length>10000)throw new Error('実績が多いため期間を短くしてください。');return r.results.map(v=>JSON.parse(v.data) as Fact);}
export async function improvements(r:Request,env:Env,user:Identity,scope:string,delegation?:{allowed:Operation[]}){
 if(!can(user,scope,'improvements',r.method!=='GET'))return json({error:'この事業の改善・診断の権限がありません。'},403);
 const id=documentId(scope,'improvements'),doc=await readDocument(env.DB,id,emptyState),state=structuredClone(doc.data),business=(await readDocument(env.DB,documentId(scope,'business'),emptyBusiness)).data;
 const q=new URL(r.url).searchParams,start=q.get('start')??today().slice(0,7)+'-01',end=q.get('end')??today();if(!validDate(start)||!validDate(end)||start>end)return json({error:'期間を確認してください。'},400);
 if(r.method==='GET'){const rows=await facts(env,scope,start,end);return json({data:state,business:{goals:business.goals,funnels:business.funnels??[],projects:business.projects??[]},rows,model:{configured:!!env.ASTRA_OPENAI_KEY&&!!env.ASTRA_MODEL,name:env.ASTRA_MODEL??null},capabilities:{scheduled:env.ASTRA_SCHEDULE_ENABLED==='true',external:false,posts:can(user,scope,'posts',true),work:can(user,scope,'work',true)||can(user,scope,'business',true)}});}
 if(r.method!=='POST')return json({error:'操作できません。'},405);
 let b;try{const raw=await r.text();if(raw.length>60000)throw new Error();b=JSON.parse(raw);}catch{return json({error:'入力が不正です。'},400);}
 if(!b||!text(b.requestId,100)||!b.requestId||!Number.isSafeInteger(b.expectedVersion))return json({error:'操作情報を確認してください。'},400);
 const signature=await digest(JSON.stringify(b)),replay=await env.DB.prepare('SELECT signature FROM receipts WHERE id=?').bind(id+':'+b.requestId).first<{signature:string}>();if(replay)return replay.signature===signature?json({data:state,replayed:true}):json({error:'操作IDが競合しています。'},409);
 if(b.expectedVersion!==doc.data.version)throw new Conflict('別の画面で更新されました。再取得してください。');
 const now=new Date().toISOString(),c=state.cases.find(c=>c.id===b.caseId);const log=(kind:string,output:string,status:Run['status']='success',caseId?:string)=>state.runs.push({id:b.requestId,at:now,kind,output,status,actor:user.id,caseId,inputVersion:doc.version});
 try{
 if(b.action==='save_case'){
 const v=b.case as Improvement;validateCase(v);if(!business.goals.some(g=>g.id===v.goalId)||v.funnelId&&!business.funnels?.some(f=>f.id===v.funnelId&&f.goalIds.includes(v.goalId)))throw new Error('目標とファネルの関連を確認してください。');const old=state.cases.find(c=>c.id===v.id);if(old&&!['draft','rejected'].includes(old.phase))throw new Error('実行後の案は上書きできません。別の改善案を作成してください。');
 const evidence=b.evidence;if(!evidence||!validDate(evidence.start)||!validDate(evidence.end)||evidence.start>evidence.end||!text(evidence.description)||!text(evidence.source))throw new Error('根拠の期間・出典を確認してください。');const rows=(await facts(env,scope,evidence.start,evidence.end)).filter(r=>!v.funnelId||r.funnelId===v.funnelId);
 const next:Improvement={id:v.id,title:v.title,goalId:v.goalId,funnelId:v.funnelId,hypothesis:v.hypothesis,before:v.before,after:v.after,operation:v.operation,platform:v.platform,owner:v.owner,due:v.due,stopRule:v.stopRule,evidence:{start:evidence.start,end:evidence.end,source:evidence.source,description:evidence.description,factIds:rows.map(r=>r.id),digest:await digest(JSON.stringify(rows))},phase:'draft',result:'pending',resultNote:'',resultSource:'',feedback:old?.feedback??'',rejectionReason:'',createdAt:old?.createdAt??now,updatedAt:now};state.cases=[...state.cases.filter(c=>c.id!==next.id),next];log('proposal','改善案を保存しました。承認は変更内容ごとに確認します。','success',next.id);
 }else if(b.action==='policy'){if(user.role!=='owner')return json({error:'実行範囲は全体管理者だけが変更できます。'},403);validatePolicy(b.policy);if(b.policy.scheduled&&env.ASTRA_SCHEDULE_ENABLED!=='true')throw new Error('定期実行の接続が未設定です。手動診断を利用してください。');if(b.policy.funnelIds.some((fid:string)=>!business.funnels?.some(f=>f.id===fid)))throw new Error('ファネルを確認してください。');state.policy=b.policy;log('policy','実行範囲を変更しました。');
 }else if(b.action==='save_knowledge'){const k=b.knowledge;if(!k||!text(k.id,100)||!k.id||!text(k.title,100)||!k.title.trim()||!text(k.content,12000)||!text(k.source,1000))throw new Error('資料の内容を確認してください。');state.knowledge=[...state.knowledge.filter(v=>v.id!==k.id),{id:k.id,title:k.title,content:k.content,source:k.source,updatedAt:now}];log('knowledge','任意参照の資料を保存しました。');
 }else if(b.action==='save_feature'){const f=b.feature;if(!f||!text(f.id,500)||!f.id||!business.funnels?.some(v=>v.id===f.funnelId)||!text(f.platform,100)||!text(f.content,200)||!Array.isArray(f.tags)||f.tags.length>20||f.tags.some((t:unknown)=>!text(t,100))||f.hour!==null&&(!Number.isInteger(f.hour)||f.hour<0||f.hour>23))throw new Error('特徴・時間帯を確認してください。');state.features=[...state.features.filter(v=>v.id!==f.id),{id:f.id,funnelId:f.funnelId,platform:f.platform,content:f.content,tags:f.tags,hour:f.hour}];log('features','投稿の特徴を保存しました。時間帯は手動登録値です。');
 }else if(b.action==='save_experiment'){const e=b.experiment,f=business.funnels?.find(f=>f.id===e?.funnelId);if(!e||!text(e.id,100)||!e.id||!text(e.name,100)||!e.name.trim()||!f||!state.cases.some(c=>c.id===e.caseId&&c.funnelId===e.funnelId)||!validDate(e.start)||!validDate(e.end)||e.start>e.end||!Number.isInteger(e.minTrials)||e.minTrials<30||e.minTrials>1000000||typeof e.comparable!=='boolean'||!text(e.assignment)||!text(e.variantA,200)||!e.variantA.trim()||!text(e.variantB,200)||!e.variantB.trim()||e.variantA===e.variantB)throw new Error('比較実験の対象・期間・観測量を確認してください。');const allowed=['registrations','sales',...f.stages.map(s=>'stage:'+s.id)];if(!allowed.includes(e.numerator)||!allowed.includes(e.denominator)||e.numerator===e.denominator)throw new Error('分子と分母を選んでください。');const next={id:e.id,caseId:e.caseId,name:e.name,funnelId:e.funnelId,start:e.start,end:e.end,minTrials:e.minTrials,numerator:e.numerator,denominator:e.denominator,variantA:e.variantA,variantB:e.variantB,comparable:e.comparable,assignment:e.assignment};state.experiments=[...state.experiments.filter(v=>v.id!==e.id),next];log('experiment','比較条件を保存しました。','success',e.caseId);
 }else if(b.action==='evaluate'){const e=state.experiments.find(e=>e.id===b.experimentId);if(!e)throw new Error('実験が見つかりません。');const rows=await facts(env,scope,e.start,e.end),result=experimentResult(e,rows,today());e.outcome=result.outcome;e.resultAt=now;log('evaluation',JSON.stringify(result),'success',e.caseId);
 }else if(b.action==='diagnose'||b.action==='model'){if(state.policy.paused)throw new Error('一時停止中です。');const lookback=state.policy.lookback,endDate=new Date(Date.parse(today())-86400000).toISOString().slice(0,10),startDate=new Date(Date.parse(endDate)-(lookback-1)*86400000).toISOString().slice(0,10),oldStart=new Date(Date.parse(startDate)-lookback*86400000).toISOString().slice(0,10),rows=await facts(env,scope,oldStart,endDate),findings=detect(rows,startDate,endDate);
 if(b.action==='model'){
 if(!state.policy.allowModel||!env.ASTRA_OPENAI_KEY||!env.ASTRA_MODEL)throw new Error('全体管理者によるモデル利用設定とAPI接続が必要です。');if(state.runs.filter(r=>r.kind==='model'&&new Date(r.at).toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'})===today()).length>=state.policy.maxPerDay)throw new Error('本日のモデル実行上限に達しました。');log('model','モデルで分析中です。','running');state.version++;await commitDocument(env.DB,id,doc.version,state,b.requestId,signature);
 let answer:Awaited<ReturnType<typeof reason>>|null=null,error='';const context={advertising:await advertisingEvidence(env,user,scope,oldStart,endDate),period:{start:oldStart,end:endDate},goals:business.goals,funnels:business.funnels,findings,metrics:rows.map(r=>({id:r.id,date:r.date,source:r.source,definition:r.definition,funnelId:r.funnelId,content:r.content,angle:r.angle,format:r.format,values:r.values,stageCounts:r.stageCounts})),feedback:state.cases.filter(c=>c.feedback).map(c=>({title:c.title,feedback:c.feedback,result:c.result,resultSource:c.resultSource}))};if(JSON.stringify(context).length>150000)error='モデルへの入力が大きいため診断の観測日数を短くしてください。';else try{answer=await reason(env,state.policy.purpose,context,state.knowledge);}catch(e){error=(e as Error).message;}
 for(let attempt=0;attempt<5;attempt++){const latest=await readDocument(env.DB,id,emptyState),run=latest.data.runs.find(r=>r.id===b.requestId);if(run){Object.assign(run,{status:answer?'success':'failed',output:answer?.output??error,model:answer?.model??env.ASTRA_MODEL,tokens:answer?.tokens??0,costUsd:null,references:answer?.references??[],inputHash:await digest(JSON.stringify(context))});latest.data.version++;try{await commitDocument(env.DB,id,latest.version,latest.data,b.requestId+'-result',await digest(JSON.stringify(run)));}catch(e){if(e instanceof Conflict&&attempt<4)continue;throw e;}}return json({data:latest.data});}throw new Error('分析結果の保存が競合しました。実行履歴を確認してください。');
 }
 for(const item of state.cases){if(item.phase==='observing'&&item.due<today()){item.phase='review';item.updatedAt=now;}}for(const f of findings.slice(0,20)){const key='signal-'+(await digest(JSON.stringify([f.funnelId,f.metric,f.source,f.definition,startDate,endDate]))).slice(0,28);if(state.cases.some(c=>c.id===key))continue;const funnel=business.funnels?.find(v=>v.id===f.funnelId),goalId=funnel?.goalIds[0];if(!goalId)continue;state.cases.push({id:key,title:`${({cost:'集客費用',revenue:'売上',registrations:'登録数',sales:'成約数'} as Record<string,string>)[f.metric]??f.metric}の変化を調べる`,goalId,funnelId:f.funnelId,hypothesis:'データの欠測・定義と、流入や訴求の変化を確認する',before:String(f.baseline),after:'計測条件と流入・訴求の変化を確認し、原因の候補と改善案を記録する',operation:'record_campaign',platform:'',phase:'draft',owner:'',due:today(),stopRule:'原因と計測条件を確認するまで外部変更しない',evidence:{start:startDate,end:endDate,source:f.source,description:JSON.stringify(f),factIds:rows.filter(r=>r.funnelId===f.funnelId).map(r=>r.id),digest:await digest(JSON.stringify(rows.filter(r=>r.funnelId===f.funnelId)))},result:'pending',resultNote:'',resultSource:'',feedback:'',rejectionReason:'',createdAt:now,updatedAt:now});}log('diagnose',JSON.stringify({period:{start:startDate,end:endDate},findings,records:rows.length,note:'同日数・同出典・同定義・全日記録のある範囲だけを比較。原因は未確定。'}));
 }else if(['approve','reject','observe','observe_ad','close','prepare'].includes(b.action)){
 if(!c)throw new Error('改善案が見つかりません。');c.updatedAt=now;
 if(b.action==='approve'){if(c.phase!=='draft')throw new Error('改善案の状態を確認してください。');c.phase='approved';log('approve','表示された変更内容を承認しました。','success',c.id);}
 if(b.action==='reject'){if(!['draft','approved'].includes(c.phase)||!text(b.reason,100)||!b.reason||!text(b.note)||!b.note.trim())throw new Error('見送り理由を記入してください。');c.phase='rejected';c.rejectionReason=b.reason;c.feedback=b.note;log('reject',b.reason+'：'+b.note,'success',c.id);}
 if(b.action==='observe_ad'){if(!['draft','approved','prepared','observing'].includes(c.phase))throw new Error('改善案の状態を確認してください。');const change=await env.DB.prepare("SELECT data,finished_at FROM ad_changes WHERE id=? AND business_id=? AND status='succeeded'").bind(b.changeId,scope).first<{data:string;finished_at:string}>();if(!change||JSON.parse(change.data).caseId!==c.id)throw new Error('この改善案に関連する実行済みの広告変更がありません。');c.phase='observing';c.resultSource='広告変更 '+b.changeId+'：反映確認 '+change.finished_at;log('observe',c.resultSource,'success',c.id);}
 if(b.action==='observe'){if(c.phase!=='prepared')throw new Error('下書き作成後に、実際に開始したことを確認してください。');if(!text(b.note)||!b.note.trim())throw new Error('実施の記録・出典を記入してください。');c.phase='observing';c.resultSource=b.note;log('observe','手動の実施確認：'+b.note,'success',c.id);}
 if(b.action==='close'){if(!['observing','review'].includes(c.phase)||!['continue','change','stop'].includes(b.result)||!text(b.note)||!b.note.trim()||!text(b.source)||!b.source.trim())throw new Error('判断・結果・出典を記入してください。');c.phase='closed';c.result=b.result;c.resultNote=b.note;c.resultSource=b.source;c.feedback=text(b.feedback)?b.feedback:'';log('close',b.result+'：'+b.note,'success',c.id);}
 if(b.action==='prepare'){
 const count=state.runs.filter(r=>r.kind==='prepare'&&r.status==='success'&&new Date(r.at).toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'})===today()).length,error=gate(delegation?{...state.policy,mode:'auto',allowed:delegation.allowed}:state.policy,c,count);if(error){log('prepare',error,'blocked',c.id);}else{
 if(!business.goals.some(g=>g.id===c.goalId)||c.funnelId&&!business.funnels?.some(f=>f.id===c.funnelId&&f.goalIds.includes(c.goalId)))throw new Error('目標・ファネルの設定が変わっています。');
 let target:{id:string;version:number;data:unknown};const ref='improve-'+(await digest(c.id)).slice(0,40);
 if(c.operation==='record_campaign'){if(!can(user,scope,'work',true)&&!can(user,scope,'business',true))return json({error:'実行管理の編集権限が必要です。'},403);const tid=documentId(scope,'business'),td=await readDocument(env.DB,tid,emptyBusiness);if(td.data.campaigns.some(v=>v.id===ref))throw new Error('関連施策が既に存在します。');td.data.campaigns.push({id:ref,title:c.title,goalId:c.goalId,funnelId:c.funnelId||undefined,phase:'planned',assignee:c.owner,hypothesis:c.hypothesis,change:c.after,comparison:c.before,stopRule:c.stopRule,start:today(),end:c.due<today()?today():c.due,result:'pending',reason:'',source:c.evidence.source,postIds:[]});td.data.version++;td.data.updatedAt=now;validateBusiness(td.data);target={id:tid,version:td.version,data:td.data};
 }else{if(!can(user,scope,'posts',true))return json({error:'SNS投稿の編集権限が必要です。'},403);if(!['x','threads','instagram','youtube'].includes(c.platform)||!c.after.trim())throw new Error('SNSと本文を確認してください。');const tid=documentId(scope,'drafts'),td=await readDocument<PostizDraft[]>(env.DB,tid,[]);if(td.data.some(d=>d.id===ref))throw new Error('関連下書きが既に存在します。');td.data.push({id:ref,version:1,title:c.title,content:c.after,goalId:c.goalId,platform:c.platform,createdAt:now,updatedAt:now,remotePostIds:[],syncStatus:'local',reviewState:'editing'});target={id:tid,version:td.version,data:td.data};}
 c.phase='prepared';c.preparedRef=ref;log('prepare','下書き・施策を作成しました。公開はしていません。','success',c.id);state.version++;await commitWithTarget(env.DB,{id,version:doc.version,data:state},target,b.requestId,signature);return json({data:state});}
 }
 }else throw new Error('操作が見つかりません。');
 if(state.cases.length>1000||state.experiments.length>200||state.knowledge.length>100||state.features.length>1000||state.runs.length>5000)throw new Error('保存上限に達しています。履歴を整理してください。');state.version++;await commitDocument(env.DB,id,doc.version,state,b.requestId,signature);return json({data:state});
 }catch(e){if(e instanceof Conflict)throw e;return json({error:(e as Error).message},400);}
}
