import type {Entity,Level,Report} from '../lib/ads/model.ts';
const VERSION='v26.0';
const id=(v:string)=>{if(!/^(?:act_)?\d+$/.test(v))throw new Error('広告の識別番号が不正です。');return v;};
export class MetaError extends Error{uncertain:boolean;constructor(message:string,uncertain=false){super(message);this.uncertain=uncertain;}}
export async function meta(token:string,path:string,params:Record<string,string>={},write=false):Promise<any>{
 if(!/^(?:act_)?\d+(?:\/(campaigns|adsets|ads|insights))?$/.test(path))throw new Error('広告の取得先が不正です。');
 const url=new URL('https://graph.facebook.com/'+VERSION+'/'+path);const body=new URLSearchParams(params);if(!write)url.search=body.toString();let r:Response;
 try{r=await fetch(url,{method:write?'POST':'GET',headers:{Authorization:'Bearer '+token,...(write?{'Content-Type':'application/x-www-form-urlencoded'}:{})},body:write?body:undefined,redirect:'error',signal:AbortSignal.timeout(20000)});}catch{throw new MetaError(write?'通信が途切れました。再実行せず反映結果を確認してください。':'Metaに接続できませんでした。',write);}
 let b:any;try{b=await r.json();}catch{throw new MetaError('Metaの応答を確認できませんでした。',write);}
 if(!r.ok||b.error)throw new MetaError(b.error?.code===190?'Meta接続キーの有効期限を確認してください。':r.status===429||b.error?.code===17?'Metaの利用上限に達しました。時間を置いて再取得してください。':'Metaが処理を受け付けませんでした。広告側の権限・状態・設定を確認してください。',write&&r.status>=500);
 return b;
}
async function list(token:string,path:string,params:Record<string,string>){let after='',rows:any[]=[];for(let page=0;page<20;page++){const b=await meta(token,path,{...params,limit:'100',...(after?{after}:{})});if(!Array.isArray(b.data))throw new MetaError('Metaの一覧形式を確認できませんでした。');rows.push(...b.data);if(!b.paging?.next)return rows;const next=b.paging?.cursors?.after;if(typeof next!=='string'||!next||next===after)throw new MetaError('一覧を最後まで取得できませんでした。');after=next;}throw new MetaError('対象件数が多いため取得しきれませんでした。期間を短くしてください。');}
export async function account(token:string,externalId:string){const a=await meta(token,id(externalId),{fields:'id,name,currency,timezone_name,account_status'});if(a.id!==externalId||typeof a.currency!=='string'||typeof a.timezone_name!=='string')throw new MetaError('広告アカウントを確認できませんでした。');return a;}
const fields=(level:Level)=>'id,account_id,name,status,effective_status,updated_time'+(level==='campaign'?',daily_budget,lifetime_budget':level==='adset'?',campaign_id,daily_budget,lifetime_budget':',campaign_id,adset_id');
const integer=(v:any)=>v==null?null:/^\d+$/.test(String(v))&&Number.isSafeInteger(Number(v))?Number(v):null;
export function entity(raw:any,level:Level,externalId:string):Entity{if(String(raw.account_id)!==externalId.replace(/^act_/,''))throw new MetaError('別の広告アカウントの対象です。');return{id:id(String(raw.id)),accountId:externalId,name:String(raw.name??raw.id),level,campaignId:level==='campaign'?String(raw.id):String(raw.campaign_id??''),adsetId:level==='adset'?String(raw.id):String(raw.adset_id??''),status:String(raw.status??''),effectiveStatus:String(raw.effective_status??''),dailyBudget:integer(raw.daily_budget),lifetimeBudget:integer(raw.lifetime_budget),updatedTime:String(raw.updated_time??'')};}
export async function entities(token:string,externalId:string){const rows:Entity[]=[];for(const level of ['campaign','adset','ad'] as Level[]){for(const raw of await list(token,id(externalId)+'/'+({campaign:'campaigns',adset:'adsets',ad:'ads'}[level]),{fields:fields(level)}))rows.push(entity(raw,level,externalId));}return rows;}
export async function readEntity(token:string,externalId:string,entityId:string,level:Level){return entity(await meta(token,id(entityId),{fields:fields(level)}),level,externalId);}
const decimal=(v:any)=>v==null?null:Number.isFinite(Number(v))&&Number(v)>=0?Number(v):null;
const actions=(v:any)=>Object.fromEntries((Array.isArray(v)?v:[]).filter(v=>typeof v.action_type==='string'&&decimal(v.value)!==null).map(v=>[v.action_type,Number(v.value)]));
export async function reports(token:string,externalId:string,start:string,end:string):Promise<Report[]>{return(await list(token,id(externalId)+'/insights',{level:'ad',time_increment:'1',time_range:JSON.stringify({since:start,until:end}),use_unified_attribution_setting:'true',fields:'ad_id,ad_name,campaign_id,adset_id,date_start,spend,impressions,clicks,actions,action_values'})).map(r=>({date:r.date_start,adId:id(String(r.ad_id)),adName:String(r.ad_name??r.ad_id),campaignId:String(r.campaign_id),adsetId:String(r.adset_id),spend:decimal(r.spend),impressions:decimal(r.impressions),clicks:decimal(r.clicks),actions:actions(r.actions),actionValues:actions(r.action_values)}));}
export async function update(token:string,entityId:string,field:string,value:string|number){const b=await meta(token,id(entityId),{[field]:String(value)},true);if(b.success!==true)throw new MetaError('変更が反映されたか確認できませんでした。',true);}
