'use client';
import {DataChart} from '../components/data-charts';
import {useEffect,useState} from 'react';
import {useIdentity} from '../company/session';
import {pageNames,type AccessPage,type Grant} from '@/lib/access';
type Member={id:string;name:string;email:string;role:string;active:number;version:number};
type Data={members:Member[];grants:(Grant&{user_id:string})[];businesses:{id:string;name:string}[];projects:{id:string;name:string;businessId:string}[];invitations:{id:string;email:string|null;role:string;kind:string;expires:number;used_by:string|null;revoked:number;created_at:string}[];history:{id:string;actor_name:string|null;action:string;target:string;detail:string;created_at:string}[]};
const actionNames:Record<string,string>={'account.enrolled':'アカウント登録','session.login':'ログイン','password.reset':'パスワード再設定','member.invited':'メンバー招待','member.updated':'権限・利用状態の変更','member.reset_link':'再設定リンク発行','invitation.revoked':'招待の取消','company.renamed':'会社名の変更','business.updated':'事業の変更','marketing.updated':'マーケティングデータの変更'};
export default function Owner(){
 const user=useIdentity(),[data,setData]=useState<Data|null>(null),[selected,setSelected]=useState('new'),[email,setEmail]=useState(''),[active,setActive]=useState(true),[grants,setGrants]=useState<Grant[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[link,setLink]=useState(''),[expires,setExpires]=useState(0),[companyName,setCompanyName]=useState(''),[preview,setPreview]=useState(false);
 async function load(){const r=await fetch('/api/owner',{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error);setData(b);return b as Data;}
 useEffect(()=>{if(user.role==='owner')void load().catch(e=>setError(e.message));},[user.role]);
 function choose(id:string,d=data){setSelected(id);const member=d?.members.find(m=>m.id===id);setEmail(member?.email??'');setActive(member?.active===1||id==='new');setGrants(d?.grants.filter(g=>g.user_id===id).map(({user_id,...g})=>g)??[]);setPreview(false);setLink('');setNotice('');setError('');}
 async function send(body:unknown){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/owner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),b=await r.json();if(!r.ok)throw new Error(b.error);const d=await load();if(b.url){setLink(b.url);setExpires(b.expires);setNotice('リンクを発行しました。メールは自動送信していません。招待した本人へ渡してください。');}else{choose(selected,d);setNotice('保存しました。権限を変えたメンバーは再ログインが必要です。');}setPreview(false);return b;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 function patch(businessId:string,page:AccessPage,value:Grant|null){setGrants(old=>[...old.filter(g=>!(g.businessId===businessId&&g.page===page)),...(value?[value]:[])]);setPreview(false);}
 if(user.role!=='owner')return <main className="co-main"><h1>全体管理者専用です</h1><a href="/company">会社ホームへ戻る</a></main>;
 const member=data?.members.find(m=>m.id===selected),isOwner=member?.role==='owner';
 return <main className="co-main"><div className="co-heading"><div><p className="co-eyebrow">あなた専用の全体管理</p><h1>会社とメンバーの管理</h1><p>人ごとに見せる範囲と、できる操作を決めます。</p></div><button disabled={busy} onClick={()=>void load().then(d=>choose(selected,d)).catch(e=>setError(e.message))}>再取得</button></div>
 {error&&<p className="co-error" role="alert">{error}</p>}{notice&&<p className="co-success" role="status">{notice}</p>}{!data&&!error&&<p role="status">管理情報を取得しています…</p>}
 {data&&<><div className="dc-layout"><DataChart title="メンバーの利用状況" unit="人" points={[{id:'active',label:'利用中',value:data.members.filter(m=>m.active).length},{id:'stopped',label:'停止中',value:data.members.filter(m=>!m.active).length}]}/><DataChart title="事業ごとの閲覧可能なメンバー" unit="人" points={data.businesses.map(b=>({id:b.id,label:b.name,value:data.members.filter(m=>m.active&&(m.role==='owner'||data.grants.some(g=>g.user_id===m.id&&g.businessId===b.id))).length}))} note="保存済み権限の内訳です。同じ人が複数事業に含まれるため、事業間で人数を合算しません。"/></div><section className="co-card"><h2>メンバーと権限</h2><div className="co-member-list"><button aria-pressed={selected==='new'} disabled={busy} onClick={()=>choose('new')}>＋ メンバーを招待</button>{data.members.map(m=><button key={m.id} aria-pressed={selected===m.id} disabled={busy} onClick={()=>choose(m.id)}>{m.name}<small>{m.role==='owner'?'全体管理者':m.active?'利用中':'停止中'}</small></button>)}</div>
 {isOwner?<div className="co-preview"><h3>{member.name}（あなた）</h3><p>{member.email}</p><p>全事業・全画面を閲覧できます。全体管理者の権限はこの画面から削除・他の人へ付与できません。</p><p>パスワードを忘れた場合は、管理用の復旧手順から本人専用の再設定リンクを発行します。</p></div>:<fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}><h3>{selected==='new'?'招待する人の設定':`${member?.name??''}さんの設定`}</h3><div className="co-form-grid"><label>メールアドレス<input type="email" value={email} disabled={selected!=='new'} maxLength={254} onChange={e=>{setEmail(e.target.value);setPreview(false);}} placeholder="name@example.com"/></label>{selected!=='new'&&<label className="co-check"><input type="checkbox" checked={active} onChange={e=>{setActive(e.target.checked);setPreview(false);}}/>このメンバーの利用を有効にする</label>}</div>
 <p>「閲覧」を外すと、その画面の数字や明細も取得できなくなります。「編集」はその画面の保存・取込・接続変更を含みます。外部投稿やモデル実行は現在未接続です。</p>
 <div className="co-table co-grants"><table><thead><tr><th>事業</th><th>画面</th><th>閲覧</th><th>編集</th><th>閲覧する案件</th></tr></thead><tbody>{data.businesses.flatMap(b=>(Object.entries(pageNames) as [AccessPage,string][]).map(([page,label])=>{const g=grants.find(g=>g.businessId===b.id&&g.page===page);return <tr key={b.id+page}><th>{b.name}</th><td>{label}</td><td><input aria-label={`${b.name} ${label}を閲覧`} type="checkbox" checked={!!g} onChange={e=>patch(b.id,page,e.target.checked?{businessId:b.id,page,edit:false,projects:null}:null)}/></td><td><input aria-label={`${b.name} ${label}を編集`} type="checkbox" disabled={!g||g.projects!==null} checked={g?.edit??false} onChange={e=>g&&patch(b.id,page,{...g,edit:e.target.checked})}/></td><td>{page==='analytics'&&g?<><select aria-label={`${b.name} 分析の案件範囲`} value={g.projects===null?'all':'selected'} onChange={e=>patch(b.id,page,{...g,edit:e.target.value==='all'?g.edit:false,projects:e.target.value==='all'?null:[]})}><option value="all">すべての案件</option><option value="selected">選んだ案件のみ（閲覧）</option></select>{g.projects!==null&&<>{data.projects.filter(p=>p.businessId===b.id).length===0&&<small>この事業に案件がまだありません。</small>}{data.projects.filter(p=>p.businessId===b.id).map(p=><label className="co-check" key={p.id}><input type="checkbox" checked={g.projects!.includes(p.id)} onChange={e=>patch(b.id,page,{...g,projects:e.target.checked?[...g.projects!,p.id]:g.projects!.filter(id=>id!==p.id)})}/>{p.name}</label>)}</>}</>:g?'事業全体':'—'}</td></tr>;}))}</tbody></table></div>
 <p className="co-muted">案件を限定できるのは、現在「詳細分析」の閲覧です。「全体の数字」や「案件・ファネル設定」を許可すると、その画面の事業全体が見えます。</p>
 <div className="co-actions"><button className="co-primary" onClick={()=>setPreview(true)}>この人に見える範囲を確認</button>{selected!=='new'&&<button disabled={!active} onClick={()=>void send({action:'reset',email})}>パスワード再設定リンクを発行</button>}</div>
 {preview&&<div className="co-preview"><h3>保存前の確認：{email}</h3><p>{active?'利用可能':'利用停止・ログイン不可'}</p>{grants.length===0?<p>閲覧できる事業・業務画面はありません。</p>:<ul>{grants.map(g=><li key={g.businessId+g.page}>{data.businesses.find(b=>b.id===g.businessId)?.name} / {pageNames[g.page]}：{g.edit?'閲覧と編集':'閲覧のみ'}{g.projects!==null?` / 案件：${g.projects.map(id=>data.projects.find(p=>p.businessId===g.businessId&&p.id===id)?.name??id).join('、')||'未選択'}`:' / 事業全体'}</li>)}</ul>}<p>会社ホームにも、この権限で取得できる情報だけが表示されます。</p><button className="co-primary" disabled={!email||grants.some(g=>g.projects!==null&&!g.projects.length)} onClick={()=>void send(selected==='new'?{action:'invite',email,grants}:{action:'member',id:selected,version:member?.version,active,grants})}>{selected==='new'?'この内容で招待リンクを発行':'この内容で保存'}</button></div>}
 </fieldset>}
 {link&&<div className="co-preview"><h3>本人へ渡すリンク</h3><p>有効期限：{new Date(expires).toLocaleString('ja-JP')} / 一度だけ使用できます。</p><a className="co-link" href={link}>{link}</a><button onClick={()=>void navigator.clipboard.writeText(link).then(()=>setNotice('リンクをコピーしました。')).catch(()=>setError('リンクを選択してコピーしてください。'))}>リンクをコピー</button></div>}
 </section>
 <div className="co-columns"><section className="co-card"><h2>招待・再設定リンク</h2>{data.invitations.filter(i=>i.role!=='owner').length===0?<p>招待はまだありません。</p>:data.invitations.filter(i=>i.role!=='owner').map(i=><div className="co-goal" key={i.id}><div><strong>{i.email}</strong><small>{i.kind==='reset'?'再設定':'新規登録'} / {i.used_by?'使用済み':i.revoked?'取消済み':i.expires<Date.now()?'期限切れ':'登録待ち'}</small></div>{!i.used_by&&!i.revoked&&i.expires>Date.now()&&<button disabled={busy} onClick={()=>void send({action:'revokeInvite',id:i.id})}>リンクを無効にする</button>}</div>)}</section><section className="co-card"><h2>会社の設定</h2><form onSubmit={e=>{e.preventDefault();void send({action:'companyName',name:companyName});}}><label>会社の表示名<input value={companyName} maxLength={100} required onChange={e=>setCompanyName(e.target.value)}/></label><button disabled={busy||!companyName.trim()}>会社名を保存</button></form><p><a href="/marketing">事業の追加・名称変更、接続先の設定へ →</a></p></section></div>
 <section><h2>操作履歴</h2><p>最近100件。パスワードや接続キーは記録しません。</p><div className="co-table"><table><thead><tr><th>日時</th><th>操作した人</th><th>操作</th><th>詳細</th></tr></thead><tbody>{data.history.map(h=><tr key={h.id}><td>{new Date(h.created_at).toLocaleString('ja-JP')}</td><td>{h.actor_name??'初期設定'}</td><td>{actionNames[h.action]??h.action}</td><td><details><summary>変更内容</summary><p>{h.target}</p><pre>{JSON.stringify(JSON.parse(h.detail),null,2)}</pre></details></td></tr>)}</tbody></table></div></section></>}
 </main>;
}
