// Local UI contract test with a mocked advertising API. No real ad account or spend is used.
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const base='http://127.0.0.1:8787';
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1600,height:1000}});page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
const entity={id:'101',accountId:'act_123',name:'検証キャンペーン',level:'campaign',campaignId:'101',adsetId:'',status:'ACTIVE',effectiveStatus:'ACTIVE',dailyBudget:10000,lifetimeBudget:0,updatedTime:'2026-09-01'};
const data={accounts:[{id:'a',name:'画面検証用',external_id:'act_123',currency:'JPY',timezone:'Asia/Tokyo',policy:{enabled:true,maxDailyBudget:20000,maxChangePercent:20,maxOperations:3},version:1,busy_id:null,last_sync:'2026-09-10T01:00:00Z'}],selectedId:'a',entities:[entity],reports:[{date:'2026-09-01',adId:'3',adName:'広告',campaignId:'101',adsetId:'2',spend:1200,impressions:300,clicks:20,actions:{purchase:2},actionValues:{}}],changes:[],funnels:[],cases:[],ready:true};
try{
 await page.goto(base+'/login');await page.getByLabel('メールアドレス',{exact:true}).fill('local-owner@example.test');await page.getByLabel('パスワード',{exact:true}).fill('local-owner-test-password');await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.waitForURL('**/company');
 await page.route('**/api/marketing/ads**',async route=>{const req=route.request();if(req.method()==='GET')return route.fulfill({json:data});const b=req.postDataJSON();if(b.action==='propose')data.changes.push({id:b.requestId,account_id:'a',status:'draft',data:{entity,field:b.field,before:entity.status,after:b.after,reason:b.reason,caseId:'',currency:'JPY',policyVersion:1},created_at:'2026-09-10',message:''});if(b.action==='approve')data.changes[0].status='approved';if(b.action==='execute')data.changes[0].status='succeeded';return route.fulfill({json:{message:'操作を保存しました。'}});});
 await page.goto(base+'/marketing?businessId=default&panel=ads');await page.getByLabel('成果として見る行動',{exact:true}).selectOption('purchase');assert.ok((await page.locator('.ad-summary').innerText()).includes('￥600'));
 await page.getByRole('button',{name:'変更案を作る',exact:true}).click();await page.getByLabel('変更する理由',{exact:true}).fill('数字を確認するため一度停止する');await page.getByRole('button',{name:'変更案を保存',exact:true}).click();await page.getByRole('button',{name:'この変更内容を承認',exact:true}).click();await page.getByRole('button',{name:'承認した変更をMetaに反映',exact:true}).click();await page.getByRole('button',{name:'実行履歴',exact:true}).click();await page.getByText(/反映確認済み/).waitFor();
 await page.screenshot({path:'.data/ads-history-desktop.png',fullPage:true});await page.getByRole('button',{name:'数字の比較',exact:true}).click();await page.getByRole('heading',{name:'日別の推移'}).waitFor();await page.screenshot({path:'.data/ads-numbers-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.data/ads-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);console.log('PASS: mocked ad UI totals, proposal approval execution history and mobile width');
}catch(e){console.log((await page.locator('body').innerText()).slice(-5000));throw e;}finally{await browser.close();}
