import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {ads} from '../cloud/ads.ts';
import {aggregate,checkChange,defaultPolicy,offset,type Entity,type Change} from '../lib/ads/model.ts';
import type {Env,Statement} from '../cloud/types.ts';
import type {Identity} from '../lib/access.ts';
import {seal} from '../cloud/native.ts';
import {advertisingEvidence} from '../cloud/ads-evidence.ts';
const object={id:'101',account_id:'123',name:'検証広告',status:'ACTIVE',effective_status:'ACTIVE',daily_budget:'10000',lifetime_budget:'0',updated_time:'2026-09-01T00:00:00Z'};
async function fixture(){const db=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));class Q implements Statement{args:unknown[]=[];sql:string;constructor(sql:string){this.sql=sql;}bind(...args:unknown[]){this.args=args;return this;}async first<T>(){return db.prepare(this.sql).get(...this.args as []) as T??null;}async all<T>(){return{results:db.prepare(this.sql).all(...this.args as []) as T[]};}async run(){return{meta:{changes:Number(db.prepare(this.sql).run(...this.args as []).changes)}};}}
 const env={CONNECTOR_KEY:btoa(String.fromCharCode(...new Uint8Array(32).fill(7))),DB:{prepare:(s:string)=>new Q(s),batch:async(ss:Statement[])=>{db.exec('BEGIN');try{const out=[];for(const s of ss)out.push(await s.run());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}}} as Env;
 const owner:Identity={id:'owner',companyId:'company',name:'所有者',email:'test@example.test',role:'owner',version:1,grants:[]};
 const credential=await seal(env,'default','ads:a','secret-test');db.prepare('INSERT INTO ad_accounts(id,business_id,provider,external_id,name,currency,timezone,credential,policy,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run('a','default','meta','act_123','検証','JPY','Asia/Tokyo',credential,JSON.stringify({...defaultPolicy,enabled:true,maxDailyBudget:20000}),'2026-09-01');
 let count=0;const call=(action:string,extra:object={},user=owner)=>ads(new Request('https://astra.test/api/marketing/ads',{method:'POST',body:JSON.stringify({action,requestId:'r'+(++count),accountId:'a',...extra})}),env,user,'default');
 const stored=(id:string)=>db.prepare('SELECT * FROM ad_changes WHERE id=?').get(id)!;return{db,env,owner,call,stored};}
function mock(options:{stale?:boolean;uncertain?:boolean}={}){const previous=globalThis.fetch;let writes=0,current={...object};globalThis.fetch=async(input,init)=>{const url=new URL(String(input));if(init?.method==='POST'){writes++;if(options.uncertain)throw new Error('timeout');const b=new URLSearchParams(String(init.body));if(b.has('status'))current.status=b.get('status')!;if(b.has('daily_budget'))current.daily_budget=b.get('daily_budget')!;return Response.json({success:true});}if(url.pathname.endsWith('/act_123'))return Response.json({id:'act_123',name:'検証',currency:'JPY',timezone_name:'Asia/Tokyo'});return Response.json({...current,...(options.stale?{updated_time:'2026-09-02'}:{})});};return{restore:()=>globalThis.fetch=previous,writes:()=>writes,setCurrent:(p:object)=>Object.assign(current,p)};}
const proposal={entityId:'101',level:'campaign',field:'status',after:'PAUSED',reason:'成果の確認のため停止',caseId:''};
test('広告の提案・承認・外部実行・読戻しを行い、再送で外部変更を重複しない',async()=>{const x=await fixture(),m=mock();try{assert.equal((await x.call('propose',proposal)).status,200);assert.equal((await x.call('execute',{changeId:'r1'})).status,400);assert.equal(m.writes(),0);await x.call('approve',{changeId:'r1'});assert.equal((await x.call('execute',{changeId:'r1'})).status,200);assert.equal(x.stored('r1').status,'succeeded');assert.equal(m.writes(),1);await x.call('execute',{changeId:'r1'});assert.equal(m.writes(),1);assert.equal(x.db.prepare('SELECT busy_id FROM ad_accounts').get()!.busy_id,null);}finally{m.restore();x.db.close();}});
test('実行直前に広告設定が変わった場合は外部へ送らない',async()=>{const x=await fixture(),m=mock();try{await x.call('propose',proposal);await x.call('approve',{changeId:'r1'});m.setCurrent({updated_time:'2026-09-03'});await x.call('execute',{changeId:'r1'});assert.equal(x.stored('r1').status,'failed');assert.equal(m.writes(),0);}finally{m.restore();x.db.close();}});
test('通信結果が不明な変更はロックを維持し、再送せず読戻しで解決する',async()=>{const x=await fixture(),m=mock({uncertain:true});try{await x.call('propose',proposal);await x.call('approve',{changeId:'r1'});await x.call('execute',{changeId:'r1'});assert.equal(x.stored('r1').status,'uncertain');assert.equal(x.db.prepare('SELECT busy_id FROM ad_accounts').get()!.busy_id,'r1');assert.equal((await x.call('policy',{expectedVersion:1,policy:defaultPolicy})).status,409);await x.call('execute',{changeId:'r1'});assert.equal(m.writes(),1);x.db.prepare('UPDATE ad_changes SET attempted_at=?').run('2026-01-01');m.setCurrent({status:'PAUSED'});await x.call('reconcile',{changeId:'r1'});assert.equal(x.stored('r1').status,'succeeded');assert.equal(m.writes(),1);}finally{m.restore();x.db.close();}});
test('広告権限・事業分離・管理者専用設定・秘密情報の除外',async()=>{const x=await fixture(),m=mock();try{const member={...x.owner,role:'member' as const,grants:[{businessId:'default',page:'ads' as const,edit:false,projects:null}]};assert.equal((await x.call('propose',proposal,member)).status,403);assert.equal((await ads(new Request('https://astra.test/api/marketing/ads'),x.env,member,'other')).status,403);const result=await(await ads(new Request('https://astra.test/api/marketing/ads'),x.env,member,'default')).text();assert.ok(!result.includes('credential'));assert.ok(!result.includes('secret-test'));assert.equal((await x.call('policy',{policy:defaultPolicy},{...member,grants:[{...member.grants[0],edit:true}]})).status,403);assert.equal((await advertisingEvidence(x.env,{...member,grants:[]},'default','2026-09-01','2026-09-10')).available,false);}finally{m.restore();x.db.close();}});
test('予算は通貨単位・変更率・金額上限・旧値の一致を検査する',()=>{const e={id:'1',accountId:'act_123',name:'広告',level:'campaign',campaignId:'1',adsetId:'',status:'ACTIVE',effectiveStatus:'ACTIVE',dailyBudget:10000,lifetimeBudget:0,updatedTime:'v1'} as Entity,c={entity:e,field:'daily_budget',before:10000,after:11000,currency:'JPY'} as Change,p={...defaultPolicy,enabled:true,maxDailyBudget:15000};assert.equal(offset('JPY'),1);assert.equal(offset('USD'),100);checkChange(c,e,p,'JPY');assert.throws(()=>checkChange({...c,after:16000},e,p,'JPY'));assert.throws(()=>checkChange(c,{...e,dailyBudget:11000},p,'JPY'));assert.throws(()=>checkChange(c,e,{...p,enabled:false},'JPY'));assert.throws(()=>checkChange({...c,after:12500},e,p,'JPY'));});
test('広告側の成果を選択し、異なる行動を足さず、取得がなければ未取得',()=>{const r={date:'2026-09-01',adId:'1',adName:'広告',campaignId:'1',adsetId:'2',spend:1000,impressions:100,clicks:20,actions:{purchase:2,'offsite_conversion.fb_pixel_purchase':2},actionValues:{}};assert.equal(aggregate([r],'purchase').results,2);assert.equal(aggregate([r],'').results,null);assert.equal(aggregate([],'purchase').spend,null);assert.equal(aggregate([r],'purchase').cpa,500);});
test('1日の実行上限と方針変更後の古い承認を拒否する',async()=>{const x=await fixture(),m=mock();try{x.db.prepare('UPDATE ad_accounts SET policy=?').run(JSON.stringify({...defaultPolicy,enabled:true,maxDailyBudget:20000,maxOperations:1}));await x.call('propose',proposal);await x.call('approve',{changeId:'r1'});await x.call('execute',{changeId:'r1'});await x.call('propose',{...proposal,after:'ACTIVE'});await x.call('approve',{changeId:'r4'});assert.equal((await x.call('execute',{changeId:'r4'})).status,409);assert.equal(m.writes(),1);await x.call('policy',{expectedVersion:1,policy:{...defaultPolicy,enabled:true,maxDailyBudget:20000}});assert.equal((await x.call('execute',{changeId:'r4'})).status,400);assert.equal(m.writes(),1);}finally{m.restore();x.db.close();}});
test('日別広告実績を同期し、再取得は置換し、別アカウントの広告は拒否する',async()=>{const x=await fixture(),original=globalThis.fetch;let bad=false;globalThis.fetch=async input=>{const path=new URL(String(input)).pathname;if(path.endsWith('/act_123'))return Response.json({id:'act_123',currency:'JPY',timezone_name:'Asia/Tokyo'});if(path.endsWith('/campaigns'))return Response.json({data:[{...object,account_id:bad?'999':'123'}]});if(path.endsWith('/adsets')||path.endsWith('/ads'))return Response.json({data:[]});return Response.json({data:[{date_start:'2026-09-01',ad_id:'3',ad_name:'広告',campaign_id:'101',adset_id:'2',spend:'1200',impressions:'300',clicks:'20',actions:[{action_type:'purchase',value:'2'}]}]});};try{for(let i=0;i<2;i++)assert.equal((await x.call('sync',{start:'2026-09-01',end:'2026-09-02'})).status,200);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM ad_reports').get()!.n,1);const b=await(await ads(new Request('https://astra.test/api/marketing/ads?start=2026-09-01&end=2026-09-02'),x.env,x.owner,'default')).json() as any;assert.equal(b.reports[0].spend,1200);bad=true;assert.equal((await x.call('sync',{start:'2026-09-01',end:'2026-09-02'})).status,400);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM ad_reports').get()!.n,1);}finally{globalThis.fetch=original;x.db.close();}});
test('自律操作はサーバー内部の委任と操作別許可が必要で、公開APIから偽装できない',async()=>{const x=await fixture(),m=mock();try{await x.call('propose',proposal);assert.equal((await x.call('execute',{changeId:'r1',autonomous:true})).status,400);assert.equal(m.writes(),0);const req=()=>new Request('https://test/',{method:'POST',body:JSON.stringify({action:'execute',accountId:'a',changeId:'r1',requestId:'auto-execute'})});assert.equal((await ads(req(),x.env,x.owner,'default',true)).status,400);x.db.prepare('UPDATE ad_accounts SET policy=?').run(JSON.stringify({...defaultPolicy,enabled:true,maxDailyBudget:20000,autonomousOperations:['pause']}));assert.equal((await ads(req(),x.env,x.owner,'default',true)).status,200);assert.equal(x.stored('r1').status,'succeeded');assert.equal(m.writes(),1);await ads(req(),x.env,x.owner,'default',true);assert.equal(m.writes(),1);}finally{m.restore();x.db.close();}});

test('同期の保存直前に成功したファネル対応付けを上書きしない',async()=>{
 const x=await fixture(),originalFetch=globalThis.fetch,originalBatch=x.env.DB.batch;try{
 x.db.prepare("INSERT INTO documents VALUES('business',1,?,'')").run(JSON.stringify({goals:[],funnels:[{id:'f1',source:'ads'}]}));
 x.db.prepare("INSERT INTO ad_entities VALUES('a','101','campaign',?)").run(JSON.stringify({id:'101',level:'campaign',funnelId:''}));
 globalThis.fetch=async input=>{const path=new URL(String(input)).pathname;if(path.endsWith('/act_123'))return Response.json({id:'act_123',currency:'JPY',timezone_name:'Asia/Tokyo'});if(path.endsWith('/campaigns'))return Response.json({data:[object]});return Response.json({data:[]});};
 let mapped=false;x.env.DB.batch=async statements=>{if(!mapped){mapped=true;assert.equal((await x.call('mapping',{entityId:'101',funnelId:'f1'})).status,200);}return originalBatch(statements);};
 assert.equal((await x.call('sync',{start:'2026-09-01',end:'2026-09-01'})).status,200);
 assert.equal(JSON.parse(String(x.db.prepare("SELECT data FROM ad_entities WHERE id='101'").get()!.data)).funnelId,'f1');
 }finally{globalThis.fetch=originalFetch;x.env.DB.batch=originalBatch;x.db.close();}
});


test('媒体の一覧から消えた広告も対応付けと履歴を残し、再出現時に復旧する',async()=>{
 const x=await fixture(),original=globalThis.fetch;let missing=true;try{
 x.db.prepare("INSERT INTO ad_entities VALUES('a','101','campaign',?)").run(JSON.stringify({id:'101',level:'campaign',funnelId:'saved-funnel',effectiveStatus:'ACTIVE'}));
 globalThis.fetch=async input=>{const path=new URL(String(input)).pathname;if(path.endsWith('/act_123'))return Response.json({id:'act_123',currency:'JPY',timezone_name:'Asia/Tokyo'});return Response.json({data:path.endsWith('/campaigns')&&!missing?[object]:[]});};
 assert.equal((await x.call('sync',{start:'2026-09-01',end:'2026-09-01'})).status,200);
 let saved=JSON.parse(String(x.db.prepare("SELECT data FROM ad_entities WHERE id='101'").get()!.data));
 assert.equal(saved.funnelId,'saved-funnel');assert.equal(saved.syncMissing,true);assert.equal(saved.effectiveStatus,'UNAVAILABLE');
 missing=false;assert.equal((await x.call('sync',{start:'2026-09-01',end:'2026-09-01'})).status,200);
 saved=JSON.parse(String(x.db.prepare("SELECT data FROM ad_entities WHERE id='101'").get()!.data));assert.equal(saved.funnelId,'saved-funnel');assert.equal(saved.syncMissing,false);assert.equal(saved.effectiveStatus,'ACTIVE');
 }finally{globalThis.fetch=original;x.db.close();}
});
