import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {tick} from '../cloud/autonomy-engine.ts';
import {autonomy} from '../cloud/autonomy.ts';
import {defaultPolicy} from '../lib/autonomy/model.ts';
import {emptyBusiness} from '../lib/marketing-business/types.ts';
import {digest} from '../cloud/storage.ts';
import type {Env,Statement} from '../cloud/types.ts';
const owner={id:'owner',companyId:'company',name:'所有者',email:'test@example.test',role:'owner' as const,version:1,grants:[]};
function fixture(){const db=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));
 db.exec("INSERT INTO users(id,company_id,email,name,password_hash,role,created_at) VALUES('owner','company','test@example.test','所有者','unused','owner','2026-01-01')");
 db.prepare('INSERT INTO autonomy_settings(business_id,owner_id,version,policy,next_at,updated_at) VALUES(?,?,?,?,?,?)').run('default','owner',1,JSON.stringify({...defaultPolicy,enabled:true,purpose:'実績を調べて投稿を改善する',internal:['create_post_draft']}),0,'2026-01-01');
 db.prepare("INSERT INTO documents VALUES('business',1,?,'')").run(JSON.stringify({...emptyBusiness,version:1,goals:[{id:'g',title:'成約数',metric:'conversions',baseline:0,target:10,direction:'increase',deadline:'2026-12-31',owner:'担当',baselineDays:14,baselineSource:'記録',comparisonConfirmed:false}]}));
 class Q implements Statement{args:unknown[]=[];sql:string;constructor(sql:string){this.sql=sql;}bind(...a:unknown[]){this.args=a;return this;}async first<T>(){return db.prepare(this.sql).get(...this.args as []) as T??null;}async all<T>(){return{results:db.prepare(this.sql).all(...this.args as []) as T[]};}async run(){return{meta:{changes:Number(db.prepare(this.sql).run(...this.args as []).changes)}};}}
 const env={ASTRA_MODEL:'test-model',ASTRA_OPENAI_KEY:'fake-key',ASTRA_LOOP:{getByName:()=>({wake:async()=>{}})},DB:{prepare:(s:string)=>new Q(s),batch:async(ss:Statement[])=>{db.exec('BEGIN');try{const out=[];for(const s of ss)out.push(await s.run());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}}} as Env;
 return{db,env,job:()=>db.prepare('SELECT * FROM autonomy_jobs ORDER BY created_at DESC LIMIT 1').get()!};}
function mock(sequence:((input:any[])=>any[])[]){const previous=globalThis.fetch;let n=0;globalThis.fetch=async(_url,init)=>{const b=JSON.parse(String(init?.body));assert.equal(b.store,false);assert.deepEqual(b.include,['reasoning.encrypted_content']);return Response.json({status:'completed',output:sequence[n++](b.input),usage:{total_tokens:10}});};return{restore:()=>globalThis.fetch=previous,count:()=>n};}
const call=(name:string,args:object)=>[{type:'function_call',call_id:crypto.randomUUID(),name,arguments:JSON.stringify({arguments_json:JSON.stringify(args)})}];
const final=[{type:'message',content:[{type:'output_text',text:'下書きを作成しました。公開後の実績を確認します。'}]}];
test('モデルが調査→改善案→許可済み下書き→次回観測を選び、永続化して二重作成しない',async()=>{const x=fixture();let caseId='';const m=mock([()=>call('read_business',{}),()=>call('create_improvement',{title:'説明を具体化',goalId:'g',funnelId:'',hypothesis:'説明不足',before:'旧文',after:'新しい投稿本文',operation:'create_post_draft',platform:'x',owner:'担当',due:'2026-12-31',stopRule:'問題時に停止',evidence:{start:'2026-01-01',end:'2026-01-31',source:'仮説',description:'実績未取得のため仮説'}}),input=>{caseId=JSON.parse(input.at(-1).output).caseId;assert.ok(caseId);return call('prepare_improvement',{caseId});},()=>final]);try{for(let i=0;i<7;i++)await tick(x.env,'default');assert.equal(x.job().status,'waiting');const drafts=JSON.parse(x.db.prepare("SELECT data FROM documents WHERE id='drafts'").get()!.data as string);assert.equal(drafts.length,1);assert.equal(drafts[0].reviewState,'editing');assert.deepEqual(drafts[0].remotePostIds,[]);assert.ok(Number(x.db.prepare('SELECT next_at FROM autonomy_settings').get()!.next_at)>Date.now());await tick(x.env,'default');assert.equal(m.count(),4);}finally{m.restore();x.db.close();}});
test('応答台帳の保存後に中断してもモデルを再呼出しせず、途中応答が不明なら停止する',async()=>{for(const status of ['done','started']){const x=fixture(),m=mock([()=>call('read_business',{})]);try{await tick(x.env,'default');const j=x.job(),d=JSON.parse(j.data as string);d.pending=[];d.steps=0;d.calls=0;d.input=d.input.slice(0,1);x.db.prepare('UPDATE autonomy_jobs SET data=?').run(JSON.stringify(d));x.db.prepare('UPDATE autonomy_actions SET status=?').run(status);await tick(x.env,'default');assert.equal(m.count(),1);assert.equal(x.job().status,status==='started'?'needs_input':'running');}finally{m.restore();x.db.close();}}});
test('利用者の停止と設定変更は保留中の操作に反映し、APIで秘密・内部入力を返さない',async()=>{const x=fixture(),m=mock([()=>call('read_business',{})]);try{await tick(x.env,'default');x.db.prepare('UPDATE autonomy_settings SET version=2').run();await tick(x.env,'default');assert.equal(x.job().status,'cancelled');const view=await(await autonomy(new Request('https://test/'),x.env,owner,'default')).text();assert.ok(!view.includes('fake-key'));assert.ok(!view.includes('"input"'));const member={...owner,role:'member' as const,grants:[{businessId:'default',page:'autonomy' as const,edit:true,projects:null}]};assert.equal((await autonomy(new Request('https://test/',{method:'POST',body:JSON.stringify({action:'stop'})}),x.env,member,'default')).status,403);await autonomy(new Request('https://test/',{method:'POST',body:JSON.stringify({action:'stop'})}),x.env,owner,'default');assert.equal(await tick(x.env,'default'),null);assert.equal(m.count(),1);}finally{m.restore();x.db.close();}});
test('追加判断が必要なら次回予約を止め、利用上限でも継続課金しない',async()=>{for(const mode of ['question','limit']){const x=fixture(),m=mock([()=>call(mode==='question'?'request_input':'read_business',mode==='question'?{question:'商品の対象を教えてください。'}:{})]);try{if(mode==='limit')x.db.prepare('UPDATE autonomy_settings SET policy=?').run(JSON.stringify({...defaultPolicy,enabled:true,purpose:'調査',maxModelCalls:1}));await tick(x.env,'default');await tick(x.env,'default');await tick(x.env,'default');assert.equal(x.job().status,'needs_input');assert.equal(x.db.prepare('SELECT next_at FROM autonomy_settings').get()!.next_at,null);assert.equal(m.count(),1);}finally{m.restore();x.db.close();}}});
