// Local-only integration check; uses an isolated business, never production records.
import assert from 'node:assert/strict';
import {observationSignature} from '../lib/marketing-business/types.ts';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const base=process.env.TEST_BASE??'http://127.0.0.1:8787';
assert.ok(['127.0.0.1','localhost'].includes(new URL(base).hostname));
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(base+'/login');await page.getByLabel('メールアドレス',{exact:true}).fill('local-owner@example.test');await page.getByLabel('パスワード',{exact:true}).fill('local-owner-test-password');await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.waitForURL('**/company');
 const id='planning-'+Date.now(),o={id:'o1',label:'検証用観測',start:'2026-01-01',end:'2026-01-31',days:30,collectedAt:'2026-03-02',source:'ローカル検証',visitors:100,registrations:50,bookings:10,meetings:5,conversions:4,adSpend:100,revenue:200,grossProfit:100};
 const g={id:'g1',title:'成約を増やす',baseline:2,target:6,metric:'conversions',direction:'increase',deadline:'2026-09-30',owner:'担当',baselineDays:30,baselineSource:'ローカル検証',comparisonConfirmed:true,comparisonObservation:observationSignature(o)};
 const c={id:'c1',title:'案内文の改善',goalId:'g1',phase:'planned',assignee:'担当A',hypothesis:'理解が進む',change:'案内を見直す',comparison:'比較する',stopRule:'苦情時は停止',start:'2026-09-01',end:'2026-09-30',result:'pending',reason:'',source:'',postIds:[]};
 const data={version:0,name:'画面検証用',objective:'継続して選ばれる事業にする',goals:[g,{...g,id:'g2',title:'粗利を増やす',metric:'grossProfit',baseline:0,target:200}],observations:[o],campaigns:[c],updatedAt:''};
 const seed=await page.evaluate(async({id,data})=>{const headers={'Content-Type':'application/json','X-Astra-Business':id};const a=await fetch('/api/marketing/businesses',{method:'POST',headers,body:JSON.stringify({action:'create',id,name:'画面検証用'})});const b=await fetch('/api/marketing/business',{method:'POST',headers,body:JSON.stringify({requestId:crypto.randomUUID(),expectedVersion:0,data})});return [a.status,b.status,await b.text()];},{id,data});assert.equal(seed[0],200);assert.equal(seed[1],200,seed[2]);
 const f={id:'f1',projectId:'p1',name:'SNSから面談へ',source:'sns',medium:'x',status:'active',goalIds:['g1'],notes:'',stages:[{id:'s1',name:'SNS投稿',action:'',metric:'表示件数',url:''},{id:'s2',name:'LINE登録',action:'',metric:'登録件数',url:''},{id:'s3',name:'面談',action:'',metric:'面談件数',url:''}],connections:[{id:'e1',from:'s1',to:'s2'},{id:'e2',from:'s1',to:'s3'},{id:'e3',from:'s2',to:'s3'}]};
 const imported=await page.evaluate(async({id,f})=>{const headers={'Content-Type':'application/json','X-Astra-Business':id};const before=await (await fetch('/api/marketing/business',{headers})).json();const d={...before.data,projects:[{id:'p1',name:'講座',product:'講座',objective:'受講者を増やす'}],funnels:[f],campaigns:before.data.campaigns.map(c=>({...c,funnelId:'f1'}))};const a=await fetch('/api/marketing/business',{method:'POST',headers,body:JSON.stringify({requestId:crypto.randomUUID(),expectedVersion:d.version,data:d})});const row={source:'ローカル検証',externalId:'test-1',date:'2026-01-10',collectedAt:'2026-01-11',projectId:'p1',funnelId:'f1',sourceType:'sns',platform:'x',content:'投稿A',angle:'案内',format:'本文',definition:'検証の集計',values:{cost:1000,revenue:5000,payments:4000,refunds:500,registrations:20,sales:4},stageCounts:{s1:100,s2:20,s3:4}};const b=await fetch('/api/marketing/analytics',{method:'POST',headers,body:JSON.stringify({action:'import',businessVersion:d.version+1,requestId:crypto.randomUUID(),rows:[row]})});return [a.status,b.status,await b.text()];},{id,f});assert.equal(imported[0],200);assert.equal(imported[1],200,imported[2]);
 await page.goto(base+'/marketing?businessId='+id+'&panel=dashboard&start=2026-01-01&end=2026-01-31');await page.getByRole('heading',{name:'総合ダッシュボード',exact:true}).waitFor();await page.locator('.summary-cards').first().getByText('5,000',{exact:false}).waitFor();assert.equal(await page.locator('.summary-cards').first().locator('button').count(),6);await page.screenshot({path:'.data/summary-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'今日',exact:true}).click();assert.equal(await page.getByRole('button',{name:'今日',exact:true}).getAttribute('aria-pressed'),'true');await page.getByText('この期間の実績はまだありません。実績の取込、または期間を変更してください。',{exact:true}).waitFor();await page.getByLabel('開始日',{exact:true}).fill('2026-01-01');await page.getByLabel('終了日',{exact:true}).fill('2026-01-31');await page.locator('.summary-cards').first().getByText('5,000',{exact:false}).waitFor();
 await page.getByRole('button',{name:'目標のつながり（OKR）',exact:true}).click();await page.getByRole('button',{name:'ファネル全体',exact:true}).click();await page.locator('.funnel-map-scroll g[role=button]').first().waitFor();await page.getByRole('button',{name:'SNS投稿 100件。明細を表示',exact:true}).waitFor();assert.equal(await page.locator('.funnel-map-scroll svg>path').count(),3);await page.getByRole('button',{name:'LINE登録 20件。明細を表示',exact:true}).click();await page.getByText('LINE登録の記録',{exact:true}).waitFor();await page.screenshot({path:'.data/funnel-okr-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('.funnel-map-scroll svg').evaluate(e=>e.getBoundingClientRect().width>=650),'diagram text remains readable');await page.screenshot({path:'.data/funnel-okr-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'funnel page fits mobile');await page.getByLabel('画面を切り替える').selectOption('dashboard');await page.locator('.summary-cards').first().getByText('5,000',{exact:false}).waitFor();await page.screenshot({path:'.data/summary-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'summary page fits mobile');assert.deepEqual(errors,[]);console.log('PASS: summary totals, day/custom ranges, branch/merge funnel OKR, stage records, date preservation, mobile layout');
}catch(e){console.log((await page.locator('body').innerText()).slice(-6000));throw e;}finally{await browser.close();}
