import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {improvements} from '../cloud/improvements.ts';
import {emptyState,detect,experimentResult,gate,type Improvement,type Experiment} from '../lib/improvements/model.ts';
import {emptyBusiness} from '../lib/marketing-business/types.ts';
import type {Fact} from '../lib/analytics/model.ts';
import type {Env,Statement} from '../cloud/types.ts';
import type {Identity} from '../lib/access.ts';
import {commitWithTarget} from '../cloud/improvement-store.ts';
const goal={id:'g',title:'成約数',metric:'conversions',baseline:0,target:10,direction:'increase',deadline:'2026-12-31',owner:'担当',baselineDays:14,baselineSource:'記録',comparisonConfirmed:false};
const c={id:'c',title:'本文を改善',goalId:'g',funnelId:'',hypothesis:'説明不足',before:'旧文',after:'新しい投稿本文',operation:'create_post_draft',platform:'x',owner:'担当',due:'2026-12-31',stopRule:'問題時に停止'} as Improvement;
function fixture(){const db=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));db.prepare("INSERT INTO documents VALUES('business',1,?,'')").run(JSON.stringify({...emptyBusiness,version:1,goals:[goal]}));class Q implements Statement{args:unknown[]=[];sql:string;constructor(sql:string){this.sql=sql;}bind(...a:unknown[]){this.args=a;return this;}async first<T>(){return db.prepare(this.sql).get(...this.args as []) as T??null;}async all<T>(){return{results:db.prepare(this.sql).all(...this.args as []) as T[]};}async run(){return{meta:{changes:Number(db.prepare(this.sql).run(...this.args as []).changes)}};}}
 const env={DB:{prepare:(s:string)=>new Q(s),batch:async(ss:Statement[])=>{db.exec('BEGIN');try{const result=[];for(const s of ss)result.push(await s.run());db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}}} as Env;
 const user:Identity={id:'owner',companyId:'company',name:'owner',email:'test@example.test',role:'owner',version:1,grants:[]};let n=0;const call=async(action:string,extra:object={},who=user)=>{const data=JSON.parse(db.prepare("SELECT data FROM documents WHERE id='improvements'").get()?.data as string??'null');return improvements(new Request('https://test/api/marketing/improvements',{method:'POST',body:JSON.stringify({action,requestId:'r'+(++n),expectedVersion:data?.version??0,...extra})}),env,who,'default');};const stored=()=>JSON.parse(db.prepare("SELECT data FROM documents WHERE id='improvements'").get()!.data as string);return{db,env,user,call,stored};}
test('改善案→承認→SNS下書き→観測→振り返りを保存し、二重作成を拒否する',async()=>{const x=fixture();try{assert.equal((await x.call('save_case',{case:c,evidence:{start:'2026-01-01',end:'2026-01-31',source:'記録',description:'根拠'}})).status,200);assert.equal((await x.call('prepare',{caseId:'c'})).status,200);assert.equal(x.stored().cases[0].phase,'draft');assert.equal(x.stored().runs.at(-1).status,'blocked');assert.equal((await x.call('approve',{caseId:'c'})).status,200);assert.equal((await x.call('prepare',{caseId:'c'})).status,200);assert.equal(x.stored().cases[0].phase,'prepared');const drafts=JSON.parse(x.db.prepare("SELECT data FROM documents WHERE id='drafts'").get()!.data as string);assert.equal(drafts.length,1);assert.equal(drafts[0].content,c.after);assert.deepEqual(drafts[0].remotePostIds,[]);await x.call('prepare',{caseId:'c'});assert.equal(JSON.parse(x.db.prepare("SELECT data FROM documents WHERE id='drafts'").get()!.data as string).length,1);assert.equal((await x.call('observe',{caseId:'c',note:'手動で実施'})).status,200);assert.equal((await x.call('close',{caseId:'c',result:'change',note:'改善を継続',source:'実績表',feedback:'短い文を試す'})).status,200);assert.equal(x.stored().cases[0].phase,'closed');}finally{x.db.close();}});
test('読取担当の保存・他事業の読取・非管理者の方針変更・SNS権限なしの作成を拒否',async()=>{const x=fixture();try{const member={...x.user,role:'member' as const,grants:[{businessId:'default',page:'improvements' as const,edit:true,projects:null}]};assert.equal((await improvements(new Request('https://test/api/marketing/improvements'),x.env,member,'other')).status,403);assert.equal((await x.call('policy',{policy:emptyState.policy},member)).status,403);assert.equal((await x.call('save_case',{case:c,evidence:{start:'2026-01-01',end:'2026-01-31',source:'出典',description:'説明'}},member)).status,200);await x.call('approve',{caseId:'c'},member);assert.equal((await x.call('prepare',{caseId:'c'},member)).status,403);assert.equal((await x.call('approve',{caseId:'c'},{...member,grants:[{...member.grants[0],edit:false}]})).status,403);}finally{x.db.close();}});
test('下書きの版競合では改善案件だけを完了させず、両方を保全する',async()=>{const x=fixture();try{x.db.prepare("INSERT INTO documents VALUES('improvements',1,?,'')").run(JSON.stringify({...emptyState,version:1}));x.db.prepare("INSERT INTO documents VALUES('drafts',2,'[]','')").run();await assert.rejects(commitWithTarget(x.env.DB,{id:'improvements',version:1,data:{changed:true}},{id:'drafts',version:1,data:[{fake:true}]},'r','s'));assert.equal(x.stored().version,1);assert.equal(x.db.prepare("SELECT data FROM documents WHERE id='drafts'").get()!.data,'[]');}finally{x.db.close();}});
test('自動作成は操作・ファネル・日次上限・一時停止で判定する',()=>{const p={...emptyState.policy,mode:'auto' as const,allowed:['record_campaign' as const],funnelIds:['f']},v={...c,phase:'draft' as const,funnelId:'f',operation:'record_campaign' as const};assert.equal(gate(p,v,0),null);assert.ok(gate(p,{...v,operation:'external'},0));assert.ok(gate(p,{...v,funnelId:'other'},0));assert.ok(gate(p,v,3));assert.ok(gate({...p,paused:true},v,0));});
const row=(date:string,sales:number,content='A')=>({id:date+content,date,source:'記録',definition:'同じ定義',funnelId:'f',content,values:{cost:10,revenue:sales*100,payments:null,refunds:0,registrations:100,sales},funnel:{id:'f'},stageCounts:{}} as Fact);
test('欠測・異なる出典をゼロで埋めず、完全な期間だけ異常検出する',()=>{const rows=Array.from({length:14},(_,i)=>row('2026-01-'+String(i+1).padStart(2,'0'),i<7?20:5));assert.ok(detect(rows,'2026-01-08','2026-01-14').length);assert.equal(detect(rows.slice(1),'2026-01-08','2026-01-14').length,0);assert.equal(detect(rows.map((r,i)=>({...r,source:i<7?'旧':'新'})),'2026-01-08','2026-01-14').length,0);});
test('比較実験は指定された分母で評価し、期間中・少数・条件未確認は保留する',()=>{const e={id:'e',caseId:'c',name:'実験',funnelId:'f',start:'2026-01-01',end:'2026-01-31',numerator:'sales',denominator:'registrations',variantA:'A',variantB:'B',minTrials:30,comparable:true,assignment:'無作為割付'} as Experiment;const rs=[row('2026-01-01',80,'A'),row('2026-01-01',10,'B')];const result=experimentResult(e,rs,'2026-02-01');assert.equal(result.a.trials,100);assert.equal(result.outcome,'Aが高い傾向');assert.equal(experimentResult(e,rs,'2026-01-20').outcome,'観測期間中です');assert.equal(experimentResult({...e,comparable:false},rs,'2026-02-01').outcome,'比較条件を確認してください');assert.equal(experimentResult({...e,minTrials:1000},rs,'2026-02-01').outcome,'観測量が不足しています');});
test('毎日の診断は同日の再起動で重複せず、定期実行者を記録する',async()=>{const x=fixture();try{x.db.prepare("INSERT INTO users(id,company_id,email,name,password_hash,role,created_at) VALUES('owner','company','test@example.test','owner','unused','owner','2026-09-10')").run();x.env.ASTRA_SCHEDULE_ENABLED='true';await x.call('policy',{policy:{...emptyState.policy,scheduled:true,hour:0}});const {scheduledImprovements}=await import('../cloud/improvement-schedule.ts');await scheduledImprovements(x.env);await scheduledImprovements(x.env);assert.equal(x.stored().runs.filter((r:any)=>r.kind==='diagnose').length,1);assert.equal(x.stored().runs.at(-1).actor,'scheduler:owner');assert.equal(x.db.prepare("SELECT count(*) n FROM receipts WHERE signature='scheduled-complete'").get()!.n,1);}finally{x.db.close();}});
test('広告の観測開始は同事業・同改善案の反映確認済み変更だけに許可する',async()=>{const x=fixture();try{await x.call('save_case',{case:c,evidence:{start:'2026-01-01',end:'2026-01-31',source:'記録',description:'根拠'}});assert.equal((await x.call('observe_ad',{caseId:'c',changeId:'ad1'})).status,400);x.db.exec("INSERT INTO ad_accounts(id,business_id,provider,external_id,name,currency,timezone,credential,policy,created_at) VALUES('a','default','meta','act_test','検証','JPY','Asia/Tokyo','unused','{}','2026-01-01')");x.db.prepare("INSERT INTO ad_changes(id,account_id,business_id,signature,data,status,created_by,created_at,finished_at) VALUES('ad1','a','default','s',?,'uncertain','owner','2026-01-01','2026-01-02')").run(JSON.stringify({caseId:'c'}));assert.equal((await x.call('observe_ad',{caseId:'c',changeId:'ad1'})).status,400);x.db.prepare("UPDATE ad_changes SET status='succeeded'").run();assert.equal((await x.call('observe_ad',{caseId:'c',changeId:'ad1'})).status,200);assert.equal(x.stored().cases[0].phase,'observing');assert.equal((await x.call('close',{caseId:'c',result:'change',note:'次の訴求を検証',source:'広告実績',feedback:'改善継続'})).status,200);}finally{x.db.close();}});
