import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';
import {journey,ingestJourney} from '../cloud/journey.ts';import {history} from '../cloud/history.ts';import {savedViews} from '../cloud/saved-views.ts';import {primaryUrl,fetchPrimary} from '../cloud/primary-source.ts';import {digest,commitDocument} from '../cloud/storage.ts';import {journeyDetailEvents,summarizeJourney,validateEvent,type JourneySource,type JourneyEvent} from '../lib/journey/model.ts';import {emptyBusiness} from '../lib/marketing-business/types.ts';import type {Env,Statement} from '../cloud/types.ts';import type {Identity} from '../lib/access.ts';
const source:JourneySource={id:'11111111-1111-4111-a111-111111111111',name:'LP',projectId:'p',funnelId:'f',stageId:'s',provider:'external',url:'https://lp.example.test/path',connectionId:'',nativeFunnelId:'',pageId:'',adConnectionId:'',campaignId:'',adId:'',enabled:true,updatedAt:''};
function fixture(){const db=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));db.exec(readFileSync(new URL('./journey-schema.sql',import.meta.url),'utf8'));class Q implements Statement{args:unknown[]=[];sql:string;constructor(sql:string){this.sql=sql;}bind(...a:unknown[]){this.args=a;return this;}async first<T>(){return db.prepare(this.sql).get(...this.args as []) as T??null;}async all<T>(){return{results:db.prepare(this.sql).all(...this.args as []) as T[]};}async run(){return{meta:{changes:Number(db.prepare(this.sql).run(...this.args as []).changes)}};}}const env={DB:{prepare:(s:string)=>new Q(s),batch:async(ss:Statement[])=>{db.exec('BEGIN');try{const result=[];for(const s of ss)result.push(await s.run());db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}}} as Env;
 const user:Identity={id:'owner',companyId:'company',name:'owner',email:'test@example.test',role:'owner',version:1,grants:[]};const business={...emptyBusiness,version:1,projects:[{id:'p',name:'P',product:'',objective:''}],funnels:[{id:'f',projectId:'p',name:'F',source:'ads',medium:'',status:'active',goalIds:[],notes:'',stages:[{id:'s',name:'登録',action:'',metric:'登録',url:''},{id:'end',name:'成約',action:'',metric:'成約',url:''}]}]};db.prepare("INSERT INTO documents VALUES('business',1,?,'')").run(JSON.stringify(business));db.prepare("INSERT INTO documents VALUES('journey-sources',1,?,'')").run(JSON.stringify({version:1,sources:[source]}));const now=new Date().toISOString();let n=0;const call=(event:object,who=user)=>journey(new Request('https://test',{method:'POST',body:JSON.stringify({action:'record',sourceId:source.id,event})}),env,who,'default');const event=(kind='registration',more:object={})=>({externalId:'event-'+(++n),kind,occurredAt:now,leadId:'lead-1',...more});return{db,env,user,call,event,now};}
test('成果の再送は一件、内容差は409、訂正は追加記録して集計を置き換える',async()=>{const x=fixture();try{const e=x.event('payment',{amount:100});const r=await x.call(e),id=(await r.json()).id;assert.equal(r.status,200);assert.equal((await x.call(e)).status,200);assert.equal((await x.call({...e,amount:101})).status,409);assert.equal((await x.call(x.event('payment',{amount:50,supersedes:id,reason:'金額訂正'}))).status,200);assert.equal((await x.call(x.event('payment',{amount:30,supersedes:id,reason:'再訂正'}))).status,409);const day=new Date(Date.parse(x.now)+9*3600000).toISOString().slice(0,10);const result=await journey(new Request('https://test?start='+day+'&end='+day),x.env,x.user,'default'),b=await result.json();assert.equal(b.summary.payments,50);assert.equal(b.events.length,2);assert.equal(b.summary.counts.payment,1);assert.equal(b.state.sources[0].tokenHash,undefined);}finally{x.db.close();}});
test('ブラウザーから成果は作れず、LP原点・キー・読取権限・案件範囲を守る',async()=>{const x=fixture();try{const post=(event:object,headers:Record<string,string>={Origin:'https://lp.example.test'})=>ingestJourney(new Request('https://test',{method:'POST',headers,body:JSON.stringify({sourceId:source.id,event:{...event,path:'/path'}})}),x.env);assert.equal((await post(x.event())).status,400);assert.equal((await post(x.event('visit',{leadId:''}))).status,200);assert.equal((await post(x.event('visit',{leadId:''}),{Origin:'https://other.test'})).status,400);assert.equal((await post(x.event(),{Authorization:'Bearer invalid'})).status,401);x.db.prepare("UPDATE documents SET data=? WHERE id='journey-sources'").run(JSON.stringify({version:1,sources:[{...source,tokenHash:await digest('secret-test-token')}]}));assert.equal((await post(x.event(),{Authorization:'Bearer secret-test-token'})).status,200);const member={...x.user,id:'member',role:'member' as const,grants:[{businessId:'default',page:'analytics' as const,edit:false,projects:['other']}]};assert.equal((await x.call(x.event(),member)).status,403);const day=new Date(Date.parse(x.now)+9*3600000).toISOString().slice(0,10),r=await journey(new Request('https://test?start='+day+'&end='+day),x.env,member,'default'),b=await r.json();assert.equal(b.summary,null);assert.deepEqual(b.events,[]);assert.deepEqual(b.state.sources,[]);}finally{x.db.close();}});
test('同一顧客IDでも別案件を突合せず、期間後の成果を登録集団で追跡',()=>{const make=(id:string,kind:string,occurredAt:string,projectId='p')=>({...validateEvent({externalId:id,kind,occurredAt,leadId:'same',amount:kind==='sale'?100:null},source,true,new Date('2026-10-06')),id,projectId,receivedAt:occurredAt}) as JourneyEvent;const r=summarizeJourney([make('1','registration','2026-09-01T00:00:00Z'),make('2','sale','2026-09-10T00:00:00Z'),make('3','sale','2026-09-10T00:00:00Z','other')],'2026-09-01','2026-09-01');assert.equal(r.cohortCounts.sale,1);assert.equal(r.people.sale,0);});
test('保存履歴は更新後も元の版を保管し、復元は版競合を拒否する',async()=>{const x=fixture();try{const doc={...emptyBusiness,version:2,name:'changed'};await commitDocument(x.env.DB,'business',1,doc,'change','s');assert.equal(x.db.prepare("SELECT COUNT(*) n FROM document_revisions WHERE document_id='business'").get()!.n,2);const call=(expectedVersion:number)=>history(new Request('https://test?document=business',{method:'POST',body:JSON.stringify({version:1,expectedVersion,reason:'復旧テスト',requestId:'restore-'+expectedVersion})}),x.env,x.user,'default');assert.equal((await call(1)).status,409);assert.equal((await call(2)).status,200);const list=await history(new Request('https://test?document=business'),x.env,x.user,'default');assert.equal((await list.json()).revisions.length,3);assert.equal((await history(new Request('https://test'),x.env,{...x.user,role:'member'},'default')).status,403);}finally{x.db.close();}});
test('保存表示は利用者・事業ごとに隔離し、任意URLや未知の項目は保存しない',async()=>{const x=fixture();try{const body={expectedVersion:0,requestId:'v',views:[{id:'v1',name:'自分の分析',params:{start:'2026-09-01',metric:'revenue'}}]};const save=(b:object)=>savedViews(new Request('https://test',{method:'POST',body:JSON.stringify(b)}),x.env,x.user,'default');assert.equal((await save(body)).status,200);assert.equal((await save(body)).status,200);assert.equal((await save({...body,expectedVersion:1,requestId:'bad',views:[{...body.views[0],params:{url:'https://evil.test'}}]})).status,400);const other=await savedViews(new Request('https://test'),x.env,{...x.user,id:'other'},'default');assert.deepEqual((await other.json()).views,[]);}finally{x.db.close();}});
test('一次資料のURLは公式HTTPSのみ、転送先も検証しHTMLの指示は実行しない',async()=>{assert.throws(()=>primaryUrl('http://developers.google.com/docs'));assert.throws(()=>primaryUrl('https://127.0.0.1'));assert.throws(()=>primaryUrl('https://developers.google.com.evil.test'));assert.throws(()=>primaryUrl('https://user:pass@developers.google.com/docs'));const original=globalThis.fetch;try{globalThis.fetch=async()=>new Response(null,{status:302,headers:{Location:'https://127.0.0.1/private'}});await assert.rejects(fetchPrimary('https://developers.google.com/docs'));}finally{globalThis.fetch=original;}});
test('広告費はキャンペーン単位で一度だけ集計し、未取得日と複数帰属をCPAにしない',async()=>{const {journeyAttribution}=await import('../cloud/journey-attribution.ts');const x=fixture();try{x.db.prepare("INSERT INTO ad_reporting_connections(id,business_id,provider,external_id,name,currency,timezone,credential,created_at) VALUES('ads','default','meta','act_test','Meta','JPY','Asia/Tokyo','unused','2026-01-01')").run();const day=new Date(Date.parse(x.now)+9*3600000).toISOString().slice(0,10);x.db.prepare("INSERT INTO ad_reporting_days(connection_id,day,data,collected_at) VALUES('ads',?,?,?)").run(day,JSON.stringify([{campaignId:'c',spend:100}]),x.now);const s={...source,adConnectionId:'ads',campaignId:'c'},other={...s,id:'22222222-2222-4222-a222-222222222222'};const make=(id:string,kind:string,sourceId=s.id,campaignId='c')=>({...validateEvent({externalId:id,kind,occurredAt:x.now,leadId:'lead-1',amount:kind==='sale'?10:null},{...s,id:sourceId,campaignId},true),id,receivedAt:x.now}) as JourneyEvent;const es=[make('1','registration'),make('2','registration',other.id),make('3','sale')];const a=await journeyAttribution(x.env,'default',[s,other],es,day,day);assert.equal(a.length,1);assert.equal(a[0].spend,100);assert.equal(a[0].registrations,1);assert.equal(a[0].saleCost,100);const withDetail=await journeyAttribution(x.env,'default',[s,other],es,day,day,JSON.stringify(['ads','c']));const detail=withDetail[0].detail as {rows:(string|number|null)[][]};assert.equal(detail.rows.filter(r=>r[1]==='広告費').reduce((n,r)=>n+Number(r[2]),0),withDetail[0].spend);assert.equal(detail.rows.filter(r=>r[1]==='登録者').reduce((n,r)=>n+Number(r[2]),0),withDetail[0].registrations);assert.equal(detail.rows.filter(r=>r[1]==='成約者').reduce((n,r)=>n+Number(r[2]),0),withDetail[0].sales);assert.ok(!JSON.stringify(detail).includes('lead-1'));assert.equal(a[0].detail,undefined);const next=new Date(Date.parse(day)+86400000).toISOString().slice(0,10);assert.equal((await journeyAttribution(x.env,'default',[s,other],es,day,next))[0].saleCost,null);const ambiguous=await journeyAttribution(x.env,'default',[s,other],[...es,make('4','registration',other.id,'other-campaign')],day,day);assert.equal(ambiguous.find(a=>a.campaignId==='c')!.ambiguous,1);assert.equal(ambiguous.find(a=>a.campaignId==='c')!.saleCost,null);}finally{x.db.close();}});
test('キーは一度だけ返し、再発行と停止で旧接続を拒否して記録は保管する',async()=>{const x=fixture();try{const command=(action:string,expectedVersion:number,requestId:string,more:object={})=>journey(new Request('https://test',{method:'POST',body:JSON.stringify({action,sourceId:source.id,expectedVersion,requestId,...more})}),x.env,x.user,'default');const first=await command('issue_token',1,'mint1'),a=await first.json();assert.equal(first.status,200);assert.equal(typeof a.token,'string');assert.equal(a.state.sources[0].tokenHash,undefined);assert.equal((await(await command('issue_token',1,'mint1')).json()).token,undefined);const b=await(await command('issue_token',2,'mint2')).json();assert.notEqual(a.token,b.token);const post=(token:string)=>ingestJourney(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer '+token},body:JSON.stringify({sourceId:source.id,event:x.event()})}),x.env);assert.equal((await post(a.token)).status,401);assert.equal((await post(b.token)).status,200);assert.equal((await command('save_source',3,'move',{source:{...source,stageId:'end'}})).status,400);assert.equal((await command('stop_source',3,'stop')).status,200);assert.equal((await post(b.token)).status,404);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM journey_events').get()!.n,1);}finally{x.db.close();}});
test('再送と訂正は取得元の広告対応変更後も元の広告IDを保持する',async()=>{const x=fixture();try{x.db.prepare("UPDATE documents SET data=? WHERE id='journey-sources'").run(JSON.stringify({version:1,sources:[{...source,adConnectionId:'ads-old',campaignId:'campaign-old'}]}));const event=x.event(),result=await x.call(event),id=(await result.json()).id;assert.equal(result.status,200);x.db.prepare("UPDATE documents SET data=? WHERE id='journey-sources'").run(JSON.stringify({version:1,sources:[{...source,adConnectionId:'ads-new',campaignId:'campaign-new'}]}));assert.equal((await x.call(event)).status,200);assert.equal((await x.call({...event,externalId:'corrected',supersedes:id,reason:'時刻を訂正'})).status,200);const rows=x.db.prepare('SELECT data FROM journey_events').all().map(r=>JSON.parse(r.data as string));assert.ok(rows.every(r=>r.campaignId==='campaign-old'));}finally{x.db.close();}});

test('成果の内訳は重複人数と全記録を分け、訂正・金額・期間後の成果を元の集計と揃える',()=>{
 const event=(id:string,kind:JourneyEvent['kind'],day:string,leadId='one',amount:number|null=null)=>({id,kind,occurredAt:day+'T03:00:00Z',projectId:'p',leadId,amount,verified:true,supersedes:'',sourceId:'s'} as JourneyEvent);
 const rows=[event('reg','registration','2026-10-01'),event('reg2','registration','2026-10-01'),event('paid','payment','2026-10-02','one',100),{...event('correct','payment','2026-10-02','one',60),supersedes:'paid'},event('later','sale','2026-10-04','one',200),event('other','payment','2026-10-02','other',20),{...event('visit','visit','2026-10-02',''),verified:false}];
 const start='2026-10-01',end='2026-10-02',summary=summarizeJourney(rows,start,end);
 assert.equal(journeyDetailEvents(rows,'registration',start,end).length,summary.people.registration);
 assert.equal(journeyDetailEvents(rows,'events_registration',start,end).length,summary.counts.registration);
 assert.equal(journeyDetailEvents(rows,'payments',start,end).reduce((n,r)=>n+r.amount!,0),summary.payments);
 assert.equal(journeyDetailEvents(rows,'cohort_sale',start,end).length,summary.cohortCounts.sale);
 assert.equal(journeyDetailEvents(rows,'unmatched',start,end).length,summary.unmatched);
 assert.equal(journeyDetailEvents(rows,'visit',start,end).length,summary.counts.visit);
 assert.equal(journeyDetailEvents(rows,'payments',start,end).some(e=>e.id==='paid'),false);
});
test('成果明細は200件で切らず、所有者以外へ顧客ID・元記録・認証情報を返さない',async()=>{
 const f=fixture();try{for(let i=0;i<205;i++)assert.equal((await f.call(f.event('registration',{leadId:'lead-'+i}))).status,200);
 const day=new Date(Date.parse(f.now)+9*3600000).toISOString().slice(0,10),url='https://test?start='+day+'&end='+day+'&detail=registration';
 const own=await(await journey(new Request(url),f.env,f.user,'default')).json();assert.equal(own.detail.rows.length,205);assert.equal(own.summary.people.registration,205);assert.equal(own.events.length,200);
 const member={...f.user,role:'member' as const,grants:[{businessId:'default',page:'analytics' as const,edit:false,projects:['p']}]};
 const permitted=await(await journey(new Request(url),f.env,member,'default')).json();assert.equal(permitted.detail.rows.reduce((n:number,row:unknown[])=>n+Number(row[2]),0),205);assert.equal(permitted.events.length,0);assert.ok(!JSON.stringify(permitted.detail).includes('lead-'));assert.ok(!JSON.stringify(permitted.detail).includes('externalId'));assert.equal(permitted.state.sources[0].tokenHash,undefined);
 const denied=await(await journey(new Request(url),f.env,{...member,grants:[{...member.grants[0],projects:['other']}]},'default')).json();assert.deepEqual(denied.detail.rows,[]);
 assert.equal((await journey(new Request(url+'&sourceId=unknown'),f.env,member,'default')).status,400);assert.equal((await journey(new Request(url.replace('detail=registration','detail=tokenHash')),f.env,f.user,'default')).status,400);
 }finally{f.db.close();}
});
