// Local-only integration check; uses an isolated business, never production records.
import assert from 'node:assert/strict';
import {observationSignature} from '../lib/marketing-business/types.ts';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const base=process.env.TEST_BASE??'http://127.0.0.1:8787';
assert.ok(['127.0.0.1','localhost'].includes(new URL(base).hostname));
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(base+'/login');await page.getByLabel('メールアドレス',{exact:true}).fill('local-owner@example.test');await page.getByLabel('パスワード',{exact:true}).fill('local-owner-test-password');await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.waitForURL('**/company');
 const id='planning-'+Date.now(),o={id:'o1',label:'検証用観測',start:'2026-01-01',end:'2026-01-31',days:30,collectedAt:'2026-03-02',source:'ローカル検証',visitors:100,registrations:50,bookings:10,meetings:5,conversions:4,adSpend:100,revenue:200,grossProfit:100};
 const g={id:'g1',title:'成約を増やす',baseline:2,target:6,metric:'conversions',direction:'increase',deadline:'2026-09-30',owner:'担当',baselineDays:30,baselineSource:'ローカル検証',comparisonConfirmed:true,comparisonObservation:observationSignature(o)};
 const c={id:'c1',title:'案内文の改善',goalId:'g1',phase:'planned',assignee:'担当A',hypothesis:'理解が進む',change:'案内を見直す',comparison:'比較する',stopRule:'苦情時は停止',start:'2026-09-01',end:'2026-09-30',result:'pending',reason:'',source:'',postIds:[]};
 const data={version:0,name:'画面検証用',objective:'継続して選ばれる事業にする',goals:[g,{...g,id:'g2',title:'粗利を増やす',metric:'grossProfit',baseline:0,target:200}],observations:[o],campaigns:[c],updatedAt:''};
 const seed=await page.evaluate(async({id,data})=>{const headers={'Content-Type':'application/json','X-Astra-Business':id};const a=await fetch('/api/marketing/businesses',{method:'POST',headers,body:JSON.stringify({action:'create',id,name:'画面検証用'})});const b=await fetch('/api/marketing/business',{method:'POST',headers,body:JSON.stringify({requestId:crypto.randomUUID(),expectedVersion:0,data})});return [a.status,b.status,await b.text()];},{id,data});assert.equal(seed[0],200);assert.equal(seed[1],200,seed[2]);
 await page.goto(base+'/marketing?businessId='+id+'&panel=okr');await page.getByRole('button',{name:/数値目標.*成約を増やす/}).waitFor();assert.equal(await page.getByText('基準からの改善 50%',{exact:true}).count(),2);
 await page.screenshot({path:'.data/planning-okr-desktop.png',fullPage:true});
 await page.locator('.mp-campaign-node').click();await page.getByRole('heading',{name:'実行管理',exact:true}).waitFor();assert.equal(await page.getByLabel('目標',{exact:true}).inputValue(),'g1');
 await page.locator('.mp-task').click();await page.getByRole('region',{name:'施策の詳細'}).getByLabel('作業状況',{exact:true}).selectOption('running');await page.getByRole('button',{name:'施策を保存',exact:true}).click();await page.getByText('施策の状況を保存しました。',{exact:true}).waitFor();await page.reload();await page.locator('.mp-task').waitFor();assert.equal(await page.locator('.mp-board>section').filter({has:page.getByRole('heading',{name:/実行中/})}).locator('.mp-task').count(),1);
 await page.screenshot({path:'.data/planning-work-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'タスク管理',exact:true}).click();await page.getByRole('heading',{name:'タスク管理',exact:true}).waitFor();await page.getByRole('button',{name:'＋ タスクを追加',exact:true}).click();await page.getByLabel('タスク名',{exact:true}).fill('公開前に案内文を確認する');await page.getByLabel('優先度',{exact:true}).selectOption('high');await page.getByLabel('期限',{exact:true}).fill('2026-09-20');await page.getByLabel('関連する施策',{exact:true}).selectOption('c1');await page.getByRole('button',{name:'タスクを保存',exact:true}).click();await page.getByText('タスクを保存しました。',{exact:true}).waitFor();const taskRow=page.locator('.task-table tbody tr').filter({hasText:'公開前に案内文を確認する'});await taskRow.getByRole('button',{name:'完了',exact:true}).click();await page.getByText('タスクを完了にしました。',{exact:true}).waitFor();await page.getByRole('button',{name:'完了',exact:true}).click();await taskRow.waitFor();await page.reload();await page.getByRole('button',{name:'完了',exact:true}).click();await page.locator('.task-table tbody tr').filter({hasText:'公開前に案内文を確認する'}).waitFor();
 await page.screenshot({path:'.data/planning-tasks-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'目標の設定',exact:true}).click();await page.getByLabel('目標名',{exact:true}).waitFor();assert.equal(await page.getByLabel('目標名',{exact:true}).count(),1);await page.getByRole('button',{name:'観測と比較',exact:true}).click();assert.equal(await page.getByRole('checkbox').count(),2);await page.getByRole('button',{name:'施策の詳細設定',exact:true}).click();await page.getByLabel('編集する施策',{exact:true}).selectOption('c1');assert.equal(await page.getByRole('combobox').filter({has:page.locator('option[value="g1"]')}).count(),1);await page.locator('label').filter({hasText:'使うファネル'}).locator('select').waitFor();
 await page.getByRole('button',{name:'目標のつながり（OKR）',exact:true}).click();await page.locator('.mp-goal-node').first().waitFor();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.data/planning-okr-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile must fit');
 assert.deepEqual(errors,[]);console.log('PASS: real-data OKR, goal-to-work navigation, campaign and task persistence, one goal editor, comparison controls, mobile width');
}catch(e){console.log((await page.locator('body').innerText()).slice(-7000));await page.screenshot({path:'.data/planning-failure.png',fullPage:true});throw e;}finally{await browser.close();}
