import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {planning} from '../cloud/planning.ts';
import {goalProgress,campaignPhase} from '../lib/marketing-business/planning.ts';
import {observationSignature,type BusinessData,type Campaign} from '../lib/marketing-business/types.ts';
import type {Identity} from '../lib/access.ts';
import type {Env,Statement} from '../cloud/types.ts';
const observation={id:'o1',label:'観測',start:'2026-01-01',end:'2026-01-31',days:30,collectedAt:'2026-03-02',source:'集計表',visitors:100,registrations:50,bookings:10,meetings:5,conversions:4,adSpend:100,revenue:200,grossProfit:100};
const goal={id:'g1',title:'成約を増やす',baseline:2,target:6,metric:'conversions' as const,direction:'increase' as const,deadline:'2026-09-30',owner:'担当',baselineDays:30,baselineSource:'基準の集計',comparisonConfirmed:true,comparisonObservation:observationSignature(observation)};
const campaign:Campaign={id:'c1',title:'案内文の改善',goalId:'g1',hypothesis:'理解が進む',change:'案内を見直す',comparison:'比較する',stopRule:'苦情時は停止',start:'2026-09-01',end:'2026-09-30',result:'pending',reason:'',source:'',postIds:[]};
const business:BusinessData={version:1,name:'事業',objective:'継続して選ばれる',goals:[goal],observations:[observation],campaigns:[campaign],updatedAt:'2026-09-10'};
function fixture(){const db=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));db.prepare("INSERT INTO documents VALUES('business',1,?,'')").run(JSON.stringify(business));class Q implements Statement{args:unknown[]=[];sql:string;constructor(sql:string){this.sql=sql;}bind(...a:unknown[]){this.args=a;return this;}async first<T>(){return db.prepare(this.sql).get(...this.args as []) as T??null;}async all<T>(){return {results:db.prepare(this.sql).all(...this.args as []) as T[]};}async run(){return {meta:{changes:Number(db.prepare(this.sql).run(...this.args as []).changes)}};}}
 const env={DB:{prepare:(sql:string)=>new Q(sql),batch:async(rows:Statement[])=>{db.exec('BEGIN');try{const r=[];for(const row of rows)r.push(await row.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}}} as Env;
 const user:Identity={id:'staff',companyId:'company',name:'担当',email:'staff@example.test',role:'member',version:1,grants:[{businessId:'default',page:'work',edit:true,projects:null}]};
 const request=(body?:unknown,view='work')=>new Request('https://test/api/marketing/plan?view='+view,{method:body?'POST':'GET',body:body?JSON.stringify(body):undefined});return{db,env,user,request};}
test('OKR進捗は実測から計算し、施策完了や比較未確認を達成扱いしない',()=>{assert.equal(goalProgress(goal,observation).value,50);assert.equal(goalProgress(goal,undefined).value,null);assert.equal(goalProgress({...goal,comparisonConfirmed:false},observation).value,null);assert.equal(campaignPhase(campaign),'unrecorded');assert.equal(campaignPhase({...campaign,phase:'done'}),'done');assert.equal(goalProgress(goal,observation).value,50);});
test('実行担当へ数値・観測・事業目標を返さず、別事業やOKRを許可なく読ませない',async()=>{const {db,env,user,request}=fixture();try{const r=await planning(request(),env,user,'default'),body=await r.json() as any;assert.equal(r.status,200);assert.deepEqual(body.data.goals,[{id:'g1',title:goal.title}]);assert.equal(body.data.observations,undefined);assert.equal(body.data.objective,undefined);assert.equal((await planning(request(undefined,'okr'),env,user,'default')).status,403);assert.equal((await planning(request(),env,user,'another')).status,403);const reader={...user,grants:[{businessId:'default',page:'okr' as const,edit:false,projects:null}]};assert.equal((await planning(request(undefined,'okr'),env,reader,'default')).status,200);assert.equal((await planning(request({}),env,reader,'default')).status,403);}finally{db.close();}});
test('施策状況を永続化し、再送・競合・不正値を扱い、目標や観測への上書きを防ぐ',async()=>{const {db,env,user,request}=fixture();try{const body={requestId:'r1',expectedVersion:1,campaign:{...campaign,phase:'running',assignee:'担当A',observations:[],objective:'overwrite'},data:{...business,goals:[]}};const r=await planning(request(body),env,user,'default');assert.equal(r.status,200);assert.equal((await r.json() as any).data.campaigns[0].phase,'running');assert.equal((await planning(request(body),env,user,'default')).status,200);await assert.rejects(planning(request({...body,requestId:'r2'}),env,user,'default'),/更新/);const stored=JSON.parse(db.prepare("SELECT data FROM documents WHERE id='business'").get()!.data as string);assert.deepEqual(stored.observations,business.observations);assert.deepEqual(stored.goals,business.goals);assert.equal(stored.objective,business.objective);await assert.rejects(planning(request({...body,requestId:'bad',expectedVersion:2,campaign:{...campaign,phase:'fake'}}),env,user,'default'));assert.equal(JSON.parse(db.prepare("SELECT data FROM documents WHERE id='business'").get()!.data as string).version,2);}finally{db.close();}});
