import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {trackingDiagnostics} from '../cloud/tracking-diagnostics.ts';
import type {Env,Statement} from '../cloud/types.ts';
import type {Identity} from '../lib/access.ts';
import type {JourneyEvent,JourneySource} from '../lib/journey/model.ts';
function fixture(){
 const db=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));db.exec(readFileSync(new URL('./journey-schema.sql',import.meta.url),'utf8'));
 class Q implements Statement{args:unknown[]=[];sql:string;constructor(sql:string){this.sql=sql;}bind(...a:unknown[]){this.args=a;return this;}async first<T>(){return db.prepare(this.sql).get(...this.args as []) as T??null;}async all<T>(){return {results:db.prepare(this.sql).all(...this.args as []) as T[]};}async run(){return {meta:{changes:Number(db.prepare(this.sql).run(...this.args as []).changes)}};}}
 const env={DB:{prepare:(s:string)=>new Q(s)}} as Env,user:Identity={id:'owner',companyId:'company',name:'owner',email:'test@example.test',role:'owner',version:1,grants:[]};
 const now=new Date().toISOString(),day=new Date(Date.parse(now)+9*3600000).toISOString().slice(0,10);
 const source:JourneySource={id:'s',name:'外部LP',projectId:'p',funnelId:'f',stageId:'stage',provider:'external',url:'https://example.test/lp',connectionId:'',nativeFunnelId:'',pageId:'',adConnectionId:'ads',campaignId:'new',adId:'',enabled:true,tokenHash:'private-hash',updatedAt:now};
 db.prepare("INSERT INTO documents VALUES('journey-sources',1,?,'')").run(JSON.stringify({version:1,sources:[source]}));
 db.prepare("INSERT INTO ad_reporting_connections(id,business_id,provider,external_id,name,currency,timezone,credential,created_at) VALUES('ads','default','meta','act_1','Meta','JPY','Asia/Tokyo','secret-credential',?)").run(now);
 const add=(id:string,patch:Partial<JourneyEvent>={})=>{const e:JourneyEvent={id,externalId:id,sourceId:'s',projectId:'p',funnelId:'f',stageId:'stage',kind:'sale',occurredAt:now,leadId:'private-person',sessionId:'',amount:100,reason:'',supersedes:'',verified:true,receivedAt:now,adConnectionId:'ads',campaignId:'old',...patch};const eventDay=new Date(Date.parse(e.occurredAt)+9*3600000).toISOString().slice(0,10);db.prepare('INSERT INTO journey_events(id,business_id,project_id,source_id,external_id,day,lead_id,signature,data,supersedes) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,'default','p','s',id,eventDay,e.leadId,'sig',JSON.stringify(e),e.supersedes||null);};
 const report=(rows:unknown[])=>db.prepare('INSERT INTO ad_reporting_days(connection_id,day,data,collected_at) VALUES(?,?,?,?) ON CONFLICT(connection_id,day) DO UPDATE SET data=excluded.data').run('ads',day,JSON.stringify(rows),now);
 const call=(who=user,method='GET',start=day,end=day)=>trackingDiagnostics(new Request(`https://test?start=${start}&end=${end}`,{method}),env,who,'default');
 return {db,env,user,day,now,source,add,report,call};
}
test('受信なしを成功やゼロとせず、キー・個人情報を返さない',async()=>{const f=fixture();try{const b=await(await f.call()).json();assert.equal(b.routes[0].browserReception,'未確認');assert.equal(b.routes[0].outcomes,null);assert.equal(b.routes[0].serverKey,'発行済み');assert.equal(b.comparisons[0].ownSales,null);assert.equal(b.comparisons[0].difference,null);assert.equal(JSON.stringify(b).includes('private-hash'),false);assert.equal(JSON.stringify(b).includes('secret-credential'),false);}finally{f.db.close();}});
test('過去イベントの広告対応を現在の取得元設定で付け替えず、同じ成果の比較と断定しない',async()=>{const f=fixture();try{f.add('sale');f.report([{campaignId:'old',campaignName:'旧キャンペーン',conversions:2},{campaignId:'new',campaignName:'新キャンペーン',conversions:0}]);const b=await(await f.call()).json(),old=b.comparisons.find((c:any)=>c.campaignId==='old'),current=b.comparisons.find((c:any)=>c.campaignId==='new');assert.equal(old.ownSales,1);assert.equal(old.metaPurchases,2);assert.equal(old.difference,null);assert.equal(old.status,'条件未確認');assert.equal(current.ownSales,null);assert.equal(current.metaPurchases,0);assert.equal(JSON.stringify(b).includes('private-person'),false);assert.equal(b.routes[0].outcomeReception,'認証付き記録あり');}finally{f.db.close();}});
test('期間外へ移した訂正は元期間の成約を取り消し、欠測値を合算しない',async()=>{const f=fixture();try{f.add('original');f.add('corrected',{supersedes:'original',occurredAt:new Date(Date.parse(f.now)+86400000).toISOString()});f.report([{campaignId:'old',conversions:1},{campaignId:'old',conversions:null}]);const b=await(await f.call()).json(),row=b.comparisons.find((c:any)=>c.campaignId==='old');assert.equal(row.ownSales,null);assert.equal(row.metaPurchases,null);assert.equal(row.difference,null);assert.ok(row.reasons.some((r:string)=>r.includes('欠測')));}finally{f.db.close();}});
test('広告なし・案件限定・別事業・更新・期間不正の権限を守る',async()=>{const f=fixture();try{const member={...f.user,role:'member' as const,grants:[{businessId:'default',page:'analytics' as const,edit:false,projects:null}]};const b=await(await f.call(member)).json();assert.equal(b.adsAccess,false);assert.deepEqual(b.comparisons,[]);assert.equal(b.unmappedSales,null);assert.equal((await f.call({...member,grants:[{...member.grants[0],projects:['p']}]})).status,403);assert.equal((await f.call({...member,grants:[]})).status,403);assert.equal((await f.call(f.user,'POST')).status,405);assert.equal((await f.call(f.user,'GET','bad')).status,400);const other=await trackingDiagnostics(new Request(`https://test?start=${f.day}&end=${f.day}`),f.env,f.user,'other');assert.deepEqual((await other.json()).routes,[]);}finally{f.db.close();}});
test('媒体の応答が大きすぎると集計を保留し、保存データを削除しない',async()=>{const f=fixture();try{f.report([]);const large=' '.repeat(4*1024*1024+1)+'[]';f.db.prepare('UPDATE ad_reporting_days SET data=?').run(large);const b=await(await f.call()).json();assert.equal(b.comparisons[0].metaPurchases,null);assert.equal(b.mediaPartial,true);assert.equal(f.db.prepare('SELECT length(data) AS n FROM ad_reporting_days').get()!.n,large.length);}finally{f.db.close();}});
