import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {whiteboard} from '../cloud/whiteboard.ts';
import {validateWhiteboard,type WhiteboardData} from '../lib/whiteboard.ts';
import type {Env,Statement} from '../cloud/types.ts';
import type {Identity} from '../lib/access.ts';
function setup(){const db=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(file=>file.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));class Q implements Statement{args:unknown[]=[];sql:string;constructor(sql:string){this.sql=sql;}bind(...args:unknown[]){this.args=args;return this;}async first<T>(){return db.prepare(this.sql).get(...this.args as []) as T??null;}async all<T>(){return{results:db.prepare(this.sql).all(...this.args as []) as T[]};}async run(){return{meta:{changes:Number(db.prepare(this.sql).run(...this.args as []).changes)}};}}const env={DB:{prepare:(sql:string)=>new Q(sql),batch:async(rows:Statement[])=>{db.exec('BEGIN');try{const results=[];for(const row of rows)results.push(await row.run());db.exec('COMMIT');return results;}catch(error){db.exec('ROLLBACK');throw error;}}}} as Env,user:Identity={id:'staff',companyId:'company',name:'担当',email:'staff@example.test',role:'member',version:1,grants:[{businessId:'default',page:'work',edit:true,projects:null}]};return{db,env,user};}
const card=(id:string,x=0)=>({id,type:'sticky' as const,title:id,body:'メモ',color:'yellow' as const,x,y:20,width:220,height:150});
test('ホワイトボードを事業単位で保存し、再送と競合を処理する',async()=>{const {db,env,user}=setup();try{const data:WhiteboardData={version:0,cards:[card('a'),card('b',300)],edges:[{id:'e',from:'a',to:'b',label:'次'}],updatedAt:''},body={requestId:'save-1',expectedVersion:0,data};const request=()=>new Request('https://test/api/marketing/whiteboard',{method:'POST',body:JSON.stringify(body)});const saved=await whiteboard(request(),env,user,'default');assert.equal(saved.status,200);const savedBody=await saved.json() as any;assert.equal(savedBody.data.version,1);assert.equal((await whiteboard(request(),env,user,'default')).status,200);assert.equal((await whiteboard(new Request('https://test/api/marketing/whiteboard',{method:'POST',body:JSON.stringify({...body,requestId:'save-2'})}),env,user,'default')).status,409);const loaded=await (await whiteboard(new Request('https://test/api/marketing/whiteboard'),env,user,'default')).json() as any;assert.equal(loaded.data.cards.length,2);assert.equal(loaded.data.edges[0].label,'次');assert.ok(db.prepare("SELECT data FROM documents WHERE id='whiteboard'").get());}finally{db.close();}});
test('閲覧権限と不正なカード・つながりを拒否する',async()=>{const {db,env,user}=setup();try{const reader={...user,grants:[{businessId:'default',page:'work' as const,edit:false,projects:null}]};assert.equal((await whiteboard(new Request('https://test/api/marketing/whiteboard'),env,reader,'default')).status,200);assert.equal((await whiteboard(new Request('https://test/api/marketing/whiteboard',{method:'POST',body:'{}'}),env,reader,'default')).status,403);assert.throws(()=>validateWhiteboard({version:0,cards:[card('a')],edges:[{id:'e',from:'a',to:'missing',label:''}],updatedAt:''}));assert.throws(()=>validateWhiteboard({version:0,cards:[{...card('a'),x:6000}],edges:[],updatedAt:''}));}finally{db.close();}});
