import {validDate,type Fact,type Measure,total} from '../analytics/model.ts';
export const phases={draft:'改善案',approved:'実行待ち',prepared:'下書き作成済み',observing:'結果を観測中',review:'判断待ち',closed:'振り返り完了',rejected:'見送り'} as const;
export type Operation='record_campaign'|'create_post_draft'|'external';
export const operations={record_campaign:'施策として登録',create_post_draft:'SNS下書きを作成',external:'外部サービスへの公開・変更'};
export type Evidence={start:string;end:string;source:string;description:string;factIds:string[];digest:string};
export type Improvement={id:string;title:string;goalId:string;funnelId:string;hypothesis:string;before:string;after:string;operation:Operation;platform:string;phase:keyof typeof phases;owner:string;due:string;stopRule:string;evidence:Evidence;result:'pending'|'continue'|'change'|'stop';resultNote:string;resultSource:string;feedback:string;rejectionReason:string;createdAt:string;updatedAt:string;preparedRef?:string};
export type Experiment={allocationA?:number;lockedAt?:string;protocolHash?:string;id:string;caseId:string;name:string;start:string;end:string;funnelId:string;numerator:string;denominator:string;variantA:string;variantB:string;minTrials:number;comparable:boolean;assignment:string;outcome?:string;resultAt?:string};
export type Policy={mode:'diagnose'|'review'|'auto';allowed:Operation[];funnelIds:string[];maxPerDay:number;paused:boolean;scheduled:boolean;hour:number;lookback:number;purpose:string;allowModel:boolean};
export type Run={id:string;at:string;kind:string;status:'success'|'failed'|'blocked'|'running';actor:string;caseId?:string;model?:string;inputHash?:string;inputVersion?:number;output:string;tokens?:number;costUsd?:number|null;references?:string[]};
export type Knowledge={kind?:'primary'|'internal'|'hypothesis';retrievedAt?:string;contentHash?:string;relevance?:string;id:string;title:string;content:string;source:string;updatedAt:string};
export type State={version:number;cases:Improvement[];experiments:Experiment[];policy:Policy;runs:Run[];knowledge:Knowledge[];features:{id:string;funnelId:string;platform:string;content:string;tags:string[];hour:number|null}[]};
export const emptyState:State={version:0,cases:[],experiments:[],policy:{mode:'review',allowed:[],funnelIds:[],maxPerDay:3,paused:false,scheduled:false,hour:9,lookback:14,purpose:'数字の変化と改善候補を調べる',allowModel:false},runs:[],knowledge:[],features:[]};
export const text=(v:unknown,max=4000):v is string=>typeof v==='string'&&v.length<=max;
export function validateCase(c:Improvement){if(!c||!text(c.id,100)||!c.id||!text(c.title,100)||!c.title.trim()||!Object.hasOwn(operations,c.operation)||!text(c.goalId,100)||!text(c.funnelId,100)||!validDate(c.due)||![c.hypothesis,c.before,c.after,c.stopRule,c.owner].every(v=>text(v))||!['x','threads','instagram','youtube',''].includes(c.platform))throw new Error('改善案の項目・期限を確認してください。');}
export function validatePolicy(p:Policy){if(!p||!['diagnose','review','auto'].includes(p.mode)||!Array.isArray(p.allowed)||p.allowed.some(v=>!['record_campaign','create_post_draft'].includes(v))||!Array.isArray(p.funnelIds)||p.funnelIds.some(v=>!text(v,100))||!Number.isInteger(p.maxPerDay)||p.maxPerDay<1||p.maxPerDay>30||!Number.isInteger(p.hour)||p.hour<0||p.hour>23||!Number.isInteger(p.lookback)||p.lookback<7||p.lookback>90||!text(p.purpose,2000)||!p.purpose.trim()||[p.paused,p.scheduled,p.allowModel].some(v=>typeof v!=='boolean'))throw new Error('実行範囲・上限・診断時刻を確認してください。');}
export function gate(p:Policy,c:Improvement,count:number){if(p.paused)return '一時停止中です。';if(p.mode==='diagnose')return '診断のみの設定です。';if(c.operation==='external')return '外部への公開・変更は未接続です。';if(p.funnelIds.length&&!p.funnelIds.includes(c.funnelId))return '許可されたファネルの範囲外です。';if(count>=p.maxPerDay)return '本日の実行上限に達しました。';if(c.phase!=='approved'&&!(p.mode==='auto'&&p.allowed.includes(c.operation)&&c.phase==='draft'))return '変更内容の確認・承認が必要です。';return null;}
export type Finding={funnelId:string;metric:Measure;current:number;baseline:number;change:number;currentDays:number;baselineDays:number;source:string;definition:string;message:string};
export function detect(rows:Fact[],start:string,end:string):Finding[]{const n=Math.floor((Date.parse(end)-Date.parse(start))/86400000)+1,cut=new Date(Date.parse(start)-n*86400000).toISOString().slice(0,10),out:Finding[]=[];const keys=[...new Set(rows.map(r=>JSON.stringify([r.funnelId,r.source,r.definition])))];for(const key of keys){const rs=rows.filter(r=>JSON.stringify([r.funnelId,r.source,r.definition])===key),now=rs.filter(r=>r.date>=start&&r.date<=end),old=rs.filter(r=>r.date>=cut&&r.date<start),nd=new Set(now.map(r=>r.date)).size,od=new Set(old.map(r=>r.date)).size;if(nd!==n||od!==n||n<7)continue;for(const metric of ['cost','revenue','registrations','sales'] as Measure[]){const a=total(now,metric),b=total(old,metric);if(a.missing||b.missing||a.value===null||b.value===null||b.value<=0)continue;const change=(a.value-b.value)/b.value;if(metric==='cost'?change<0.3:change>-0.3)continue;out.push({funnelId:rs[0].funnelId,source:rs[0].source,definition:rs[0].definition,metric,current:a.value,baseline:b.value,change,currentDays:nd,baselineDays:od,message:'同じ出典・定義の前期間から30%以上変化。原因は未確定です。'});}}return out.sort((a,b)=>Math.abs(b.change)-Math.abs(a.change));}
export function experimentResult(e:Experiment,rows:Fact[],today:string){const rs=rows.filter(r=>r.funnelId===e.funnelId&&r.date>=e.start&&r.date<=e.end),read=(r:Fact,id:string)=>id.startsWith('stage:')?r.stageCounts[id.slice(6)]??null:r.values[id as Measure]??null;const value=(name:string)=>{const list=rs.filter(r=>r.content===name),missing=list.some(r=>read(r,e.numerator)===null||read(r,e.denominator)===null);return{success:list.reduce((n,r)=>n+(read(r,e.numerator)??0),0),trials:list.reduce((n,r)=>n+(read(r,e.denominator)??0),0),missing:missing||!list.length};};const a=value(e.variantA),b=value(e.variantB),conditions=new Set(rs.map(r=>JSON.stringify([r.source,r.definition,r.funnel])));const allocation=e.allocationA??0.5,expectedA=(a.trials+b.trials)*allocation,expectedB=(a.trials+b.trials)*(1-allocation),imbalance=expectedA>0&&expectedB>0?(a.trials-expectedA)**2/expectedA+(b.trials-expectedB)**2/expectedB:0;const expectedDays=(Date.parse(e.end)-Date.parse(e.start))/86400000+1,missingDays=[e.variantA,e.variantB].some(name=>new Set(rs.filter(r=>r.content===name).map(r=>r.date)).size!==expectedDays);let outcome='判断保留';if(!e.comparable||!e.assignment.trim()||conditions.size!==1)outcome='比較条件を確認してください';else if(a.missing||b.missing||a.trials<e.minTrials||b.trials<e.minTrials)outcome='観測量が不足しています';else if(a.success>a.trials||b.success>b.trials)outcome='分子と分母の定義を確認してください';else if(today<=e.end)outcome='観測期間中です';else if(missingDays)outcome='未記録日があります';else if(imbalance>10.828)outcome='割付比率の偏りを確認してください';else{const interval=(s:number,n:number)=>{const z=1.96,p=s/n,d=1+z*z/n,center=(p+z*z/(2*n))/d,half=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return[center-half,center+half];};const ai=interval(a.success,a.trials),bi=interval(b.success,b.trials);outcome=ai[0]>bi[1]?'Aが高い傾向':bi[0]>ai[1]?'Bが高い傾向':'差を確定できません';}return{a,b,outcome,imbalance,missingDays,note:'95%区間の重なりによる慎重な比較。割付の無作為性や因果を保証しません。'};}
