'use client';
import {MetricIcon,BreakdownChart} from '../components/dashboard-ui';
import {DataChart} from '../components/data-charts';
import {useEffect,useState} from 'react';
import {useIdentity} from '../company/session';
import {useBusinessFetch,usePageAccess} from './business-context';
import {adProviders,adProviderNames,adProviderHelp,credentialFields,conversionDefinitions,sumAdMetrics,adRatio,dayAfter,daysIn,type AdProvider,type ReportingData,type AdConnection,type AdReport,type AdMetrics} from '@/lib/ads/reporting';
import './ad-reporting.css';
import {DetailValue,useDataDetail} from './data-detail';
import TrackingDiagnostics from './tracking-diagnostics';
const initial=()=>{const end=dayAfter(new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}),-1);return {start:dayAfter(end,-6),end};};
const fmt=(v:number|null)=>v===null?'未取得':v.toLocaleString('ja-JP',{maximumFractionDigits:2});
const stamp=(v:string|null)=>v?new Date(v).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'未取得';
function MetricsTable({connections,reports,start,end}:{connections:AdConnection[];reports:ReportingData['reports'];start:string;end:string}){
 const detail=useDataDetail();
 useEffect(()=>{detail.show(null);},[start,end,reports,connections]);
 const days=daysIn(start,end).length;
 function openMetric(c:AdConnection,title:string,shown:string,rows:ReportingData['reports'],key:keyof AdMetrics|'ctr'|'cpc'|'coverage'){
 const derived=key==='ctr'||key==='cpc'||key==='coverage';
 detail.show({title:c.name+' / '+title,value:shown,context:[start+'〜'+end,adProviderNames[c.provider]+' / '+c.external_id,c.currency+' / '+c.timezone,'最終取得：'+stamp(c.last_sync),...(c.last_error?['前回の取得エラー：'+c.last_error]:[])],columns:key==='coverage'?['配信日','取得日時']:derived?['配信日','キャンペーン','キャンペーンID','配信面','広告費','表示','クリック']:['配信日','キャンペーン','キャンペーンID','配信面',title],rows:key==='coverage'?c.coverage.map(d=>[d.day,d.collected_at]):rows.map(r=>derived?[r.day,r.campaignName,r.campaignId,r.placement,r.spend,r.impressions,r.clicks]:[r.day,r.campaignName,r.campaignId,r.placement,r[key as keyof AdMetrics]]),note:key==='ctr'?'CTR = クリック合計 ÷ 表示合計 × 100。日別CTRの平均ではありません。':key==='cpc'?'CPC = 広告費合計 ÷ クリック合計。欠測や分母0では算出しません。':key==='conversions'?conversionDefinitions[c.provider]:'媒体の報告値です。UTAGEや自社売上へ自動で合算しません。未取得は0にしません。'});
 }

 const value=(rs:AdReport[],key:keyof AdMetrics)=>{const known=rs.map(r=>r[key]).filter((v):v is number=>v!==null);return known.length?fmt(known.reduce((a,b)=>a+b,0))+(known.length<rs.length?' *':''):'未取得';};
 return <><div className="mp-table"><table><caption>媒体別の取得実績（* は一部指標が未取得の合計）</caption><thead><tr><th>媒体 / アカウント</th><th>取得日数</th><th>広告費</th><th>表示</th><th>クリック</th><th>CTR</th><th>CPC</th><th>成果数</th></tr></thead><tbody>{connections.map(c=>{const rows=reports.filter(r=>r.connectionId===c.id),m=sumAdMetrics(rows);return <tr key={c.id}><th>{adProviderNames[c.provider]}<small>{c.name} / {c.currency}<br/>{c.timezone}</small></th><td><DetailValue label={c.name+'の取得日数'} onClick={()=>openMetric(c,'取得日数',c.coverage.length+' / '+days+'日',rows,'coverage')}>{c.coverage.length} / {days}日</DetailValue>{c.coverage.length<days&&<small>未取得の日あり</small>}</td><td><DetailValue label={c.name+'の広告費'} onClick={()=>openMetric(c,'広告費',value(rows,'spend'),rows,'spend')}>{value(rows,'spend')}</DetailValue></td><td><DetailValue label={c.name+'の表示'} onClick={()=>openMetric(c,'表示',value(rows,'impressions'),rows,'impressions')}>{value(rows,'impressions')}</DetailValue></td><td><DetailValue label={c.name+'のクリック'} onClick={()=>openMetric(c,'クリック',value(rows,'clicks'),rows,'clicks')}>{value(rows,'clicks')}</DetailValue></td><td><DetailValue label={c.name+'のCTR'} onClick={()=>openMetric(c,'CTR',fmt(adRatio(m.clicks,m.impressions,100))+(m.clicks!==null&&!!m.impressions?'%':''),rows,'ctr')}>{fmt(adRatio(m.clicks,m.impressions,100))}{m.clicks!==null&&!!m.impressions?'%':''}</DetailValue></td><td><DetailValue label={c.name+'のCPC'} onClick={()=>openMetric(c,'CPC',fmt(adRatio(m.spend,m.clicks)),rows,'cpc')}>{fmt(adRatio(m.spend,m.clicks))}</DetailValue></td><td><DetailValue label={c.name+'の成果数'} onClick={()=>openMetric(c,'成果数',value(rows,'conversions'),rows,'conversions')}>{value(rows,'conversions')}</DetailValue><small>{conversionDefinitions[c.provider]}</small></td></tr>;})}</tbody></table></div>{detail.drawer}</>;
}
export function AdReportSummary({start,end,refresh=0,onOpen}:{start:string;end:string;refresh?:number;onOpen:()=>void}){
 const fetch=useBusinessFetch(),allowed=usePageAccess('ads');const [data,setData]=useState<ReportingData|null>(null),[error,setError]=useState('');
 useEffect(()=>{if(!allowed)return;const c=new AbortController();setData(null);setError('');void fetch('/api/marketing/ad-reporting?'+new URLSearchParams({start,end}),{signal:c.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);if(!c.signal.aborted)setData(b);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[fetch,start,end,refresh,allowed]);
 if(!allowed)return null;
 return <section className="ad-reporting"><div className="mp-toolbar"><h3>広告媒体の実績</h3><button onClick={onOpen}>媒体の接続と実績へ</button></div><details><summary>集計について</summary><p>媒体が計測した値です。取込実績やUTAGEの売上には合算しません。</p></details>{error?<p role="alert">{error}</p>:!data?<p role="status">広告実績を読み込み中…</p>:!data.connections.length?<p className="mp-empty">広告APIが未接続です</p>:<><MetricsTable {...data} start={start} end={end}/>{data.connections.map(c=><p key={c.id}>{c.name}：最終取得 {stamp(c.last_sync)}{c.last_error&&<strong> / 前回の取得に失敗：{c.last_error}</strong>}</p>)}</>}</section>;
}
export default function AdReportingPanel({settingsOnly=false,setupProvider='google',onSettings,onDirtyChange}:{settingsOnly?:boolean;setupProvider?:AdProvider;onSettings?:(provider?:AdProvider)=>void;onDirtyChange?:(v:boolean)=>void}){
 const fetch=useBusinessFetch(),user=useIdentity(),edit=usePageAccess('ads',true);
 const [range,setRange]=useState(initial),[syncRange,setSyncRange]=useState(initial),[provider,setProvider]=useState<AdProvider>(setupProvider),[externalId,setExternalId]=useState(''),[credentials,setCredentials]=useState<Record<string,string>>({}),[data,setData]=useState<ReportingData|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[account,setAccount]=useState(''),[refresh,setRefresh]=useState(0);
 const dirty=!!externalId||Object.values(credentials).some(Boolean);
 useEffect(()=>{onDirtyChange?.(dirty);const guard=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',guard);return()=>{onDirtyChange?.(false);window.removeEventListener('beforeunload',guard);};},[dirty,onDirtyChange]);
 useEffect(()=>{const c=new AbortController();setData(null);setError('');void fetch('/api/marketing/ad-reporting?'+new URLSearchParams(range),{signal:c.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);if(!c.signal.aborted)setData(b);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[range.start,range.end,fetch,refresh]);
 async function run(body:object){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/marketing/ad-reporting',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),b=await r.json();if(!r.ok)throw new Error(b.error);setNotice(b.message);setRefresh(v=>v+1);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const selected=data?.connections.filter(c=>!account||c.id===account)??[],rows=data?.reports.filter(r=>!account||r.connectionId===account)??[];
 return <section className="ad-reporting"><details><summary>データ取得について</summary><p>「今すぐ取得」で1回7日以内の実績を取得します。保存分は最大366日表示できます。未取得は0にしません。成果の定義は媒体ごとに異なります。配信や予算は変更しません。</p></details>{error&&<p role="alert" className="ad-error">{error}</p>}{notice&&<p role="status" className="ad-notice">{notice}</p>}
 {settingsOnly&&user.role==='owner'&&<form className="ad-connect-form" onSubmit={async e=>{e.preventDefault();if(await run({action:'connect',provider,externalId,credentials})){setExternalId('');setCredentials({});}}}><h3>媒体APIを接続 / キーを更新</h3><fieldset disabled={busy||!data?.ready}><label>広告媒体<select value={provider} onChange={e=>{setProvider(e.target.value as AdProvider);setCredentials({});setExternalId('');}}>{adProviders.map(p=><option key={p} value={p}>{adProviderNames[p]}</option>)}</select></label><p>{adProviderHelp[provider]}</p><label>広告アカウントID<input required value={externalId} maxLength={120} onChange={e=>setExternalId(e.target.value.trim())} placeholder={provider==='meta'?'act_123456789':provider==='chatgpt'?'adacct_…':undefined}/></label><div className="ad-fields">{credentialFields[provider].map(f=><label key={f.key}>{f.label}{f.optional?'（任意）':''}<input required={!f.optional} type={['currency','timezone','loginCustomerId','clientId'].includes(f.key)?'text':'password'} autoComplete="off" maxLength={10000} value={credentials[f.key]??''} onChange={e=>setCredentials(v=>({...v,[f.key]:e.target.value}))}/></label>)}</div><details><summary>認証情報の保存について</summary><p>認証後に暗号化して保存します。同じアカウントIDの登録はキーの更新になります。</p></details><button type="submit">認証を確認して保存</button></fieldset>{data&&!data.ready&&<p role="alert">暗号化キーが未設定です。管理者によるサーバー設定が必要です。</p>}</form>}
 {settingsOnly&&user.role!=='owner'&&<p>API接続の登録とキー更新は全体管理者が行います。</p>}
 {!settingsOnly&&onSettings&&<button onClick={()=>onSettings()}>媒体APIを接続する</button>}
 <details open={settingsOnly}><summary>接続アカウントとデータ取得</summary>{!!data?.connections.length&&<h3>接続アカウント</h3>}{!!data?.connections.length&&<div className="ad-range"><label>取得開始<input type="date" value={syncRange.start} onChange={e=>setSyncRange(v=>({...v,start:e.target.value}))}/></label><label>取得終了<input type="date" value={syncRange.end} onChange={e=>setSyncRange(v=>({...v,end:e.target.value}))}/></label><span>昨日まで・最大7日間</span></div>}
 <div className="ad-accounts">{(settingsOnly?adProviders:adProviders.filter(p=>data?.connections.some(c=>c.provider===p))).map(p=>{const cs=data?.connections.filter(c=>c.provider===p)??[];return <article key={p}><h4>{adProviderNames[p]}</h4>{!cs.length?<p>{data?'未接続':'確認中…'}</p>:cs.map(c=><div key={c.id}><strong>{c.name}</strong><p>{c.external_id} / {c.currency} / {c.timezone}</p><p>最終取得：{stamp(c.last_sync)}</p>{c.last_error&&<p role="alert" className="ad-error">前回の取得失敗：{c.last_error}</p>}<button disabled={busy||!edit} onClick={()=>void run({action:'sync',id:c.id,...syncRange})}>{busy?'処理中…':'今すぐ取得'}</button>{settingsOnly&&user.role==='owner'&&<button disabled={busy} onClick={()=>{setProvider(c.provider);setExternalId(c.external_id);setCredentials({});document.querySelector<HTMLInputElement>('.ad-connect-form input')?.focus();}}>キーを更新</button>}</div>)}</article>;})}</div>
 </details>
 {!settingsOnly&&<><h3>保存済みの実績</h3><div className="ad-range"><label>表示開始<input type="date" value={range.start} onChange={e=>setRange(v=>({...v,start:e.target.value}))}/></label><label>表示終了<input type="date" value={range.end} onChange={e=>setRange(v=>({...v,end:e.target.value}))}/></label><label>媒体 / アカウント<select value={account} onChange={e=>setAccount(e.target.value)}><option value="">すべて</option>{data?.connections.map(c=><option key={c.id} value={c.id}>{adProviderNames[c.provider]} / {c.name}</option>)}</select></label></div>{data&&<>{!!selected.length&&<ReportingDashboard connections={selected} reports={rows} {...range}/>} {!!selected.length&&<MetricsTable connections={selected} reports={rows} {...range}/>}{!rows.length&&<p className="mp-empty">この期間の実績はありません</p>}{!!rows.length&&<details><summary>日別とキャンペーンの内訳（{rows.length}行）</summary><DetailRows rows={rows} connections={selected}/></details>}</>}</>}
 {!settingsOnly&&<TrackingDiagnostics range={range} view="comparison" onSetup={onSettings?()=>onSettings('meta'):undefined}/>}
 </section>;
}
function DetailRows({rows,connections}:{rows:ReportingData['reports'];connections:AdConnection[]}){const [limit,setLimit]=useState(100),detail=useDataDetail();useEffect(()=>{detail.show(null);setLimit(100);},[rows,connections]);function openRow(r:ReportingData['reports'][number]){const c=connections.find(c=>c.id===r.connectionId);detail.show({title:r.campaignName+' / '+r.day,context:[(c?.name??'')+' / '+(c?.currency??'')+' / '+(c?.timezone??''),r.campaignId+' / '+r.placement],columns:['指標','保存値'],rows:[['広告費',r.spend],['表示',r.impressions],['クリック',r.clicks],['成果数',r.conversions],['成果価値',r.conversionValue]],note:c?conversionDefinitions[c.provider]:undefined});}return <><div className="mp-table"><table><thead><tr><th>日付</th><th>アカウント / 通貨</th><th>キャンペーン</th><th>配信面</th><th>広告費</th><th>表示</th><th>クリック</th><th>成果数</th><th>成果価値</th></tr></thead><tbody>{rows.slice(0,limit).map(r=>{const c=connections.find(c=>c.id===r.connectionId);return <tr key={[r.connectionId,r.day,r.campaignId,r.placement].join(':')}><td>{r.day}</td><td>{c?.name} / {c?.currency}</td><td><DetailValue label={r.campaignName} onClick={()=>openRow(r)}>{r.campaignName}</DetailValue><small>{r.campaignId}</small></td><td>{r.placement}</td><td><DetailValue label={r.campaignName+'の広告費'} onClick={()=>openRow(r)}>{fmt(r.spend)}</DetailValue></td><td><DetailValue label={r.campaignName+'の表示'} onClick={()=>openRow(r)}>{fmt(r.impressions)}</DetailValue></td><td><DetailValue label={r.campaignName+'のクリック'} onClick={()=>openRow(r)}>{fmt(r.clicks)}</DetailValue></td><td><DetailValue label={r.campaignName+'の成果数'} onClick={()=>openRow(r)}>{fmt(r.conversions)}</DetailValue></td><td><DetailValue label={r.campaignName+'の成果価値'} onClick={()=>openRow(r)}>{fmt(r.conversionValue)}</DetailValue></td></tr>;})}</tbody></table></div>{rows.length>limit&&<button onClick={()=>setLimit(v=>v+100)}>次の100行を表示</button>}<p>成果価値は媒体のアトリビューションによる値です。会計上の確定売上とは異なります。</p>{detail.drawer}</>;}

function ReportingDashboard({connections,reports,start,end}:{connections:AdConnection[];reports:ReportingData['reports'];start:string;end:string}){
 const [accountId,setAccountId]=useState(''),detail=useDataDetail(),c=connections.find(c=>c.id===accountId)??connections[0];
 useEffect(()=>{detail.show(null);},[reports,accountId,start,end]);if(!c)return null;
 const rows=reports.filter(r=>r.connectionId===c.id),dates=daysIn(start,end),covered=new Set(c.coverage.map(d=>d.day)),complete=dates.every(d=>covered.has(d));
 const m=rows.length?sumAdMetrics(rows):{spend:complete?0:null,impressions:complete?0:null,clicks:complete?0:null,conversions:null,conversionValue:null};
 function open(title:string,id?:string,day?:string){detail.show({title:c.name+' / '+title,context:[start+'〜'+end,adProviderNames[c.provider]+' / '+c.currency+' / '+c.timezone],columns:['日付','キャンペーン','広告費','表示','クリック','成果'],rows:rows.filter(r=>(!id||r.campaignId===id)&&(!day||r.day===day)).map(r=>[r.day,r.campaignName,r.spend,r.impressions,r.clicks,r.conversions]),note:conversionDefinitions[c.provider]});}
 const campaigns=[...new Set(rows.map(r=>r.campaignId))];
 return <section className="dash-section"><div className="mp-toolbar"><h3>広告の主要な数字</h3><label>グラフのアカウント<select value={c.id} onChange={e=>setAccountId(e.target.value)}>{connections.map(c=><option value={c.id} key={c.id}>{adProviderNames[c.provider]} / {c.name}</option>)}</select></label></div><small>{c.currency} / {c.timezone} / 取得 {dates.filter(d=>covered.has(d)).length} / {dates.length}日</small><div className="dash-kpi-grid">{([['cost','広告費',m.spend,c.currency],['impressions','表示回数',m.impressions,'回'],['clicks','クリック数',m.clicks,'回'],['sales','成果数',m.conversions,'件'],['cpa','CPA',adRatio(m.spend,m.conversions),c.currency]] as const).map(([key,label,value,unit])=><article className="dash-kpi" key={key}><span><MetricIcon metric={key}/>{label}</span><strong><DetailValue label={label} onClick={()=>open(label)}>{fmt(complete?value:null)}</DetailValue></strong><small>{unit} / {complete?'保存済み':'期間内に未取得あり'}</small></article>)}</div><div className="dc-layout"><DataChart title="広告費の日別推移" kind="line" tone="blue" unit={c.currency} points={dates.map(day=>{const rs=rows.filter(r=>r.day===day);return {id:day,date:day,label:day,value:!covered.has(day)?null:rs.length?sumAdMetrics(rs).spend:0};})} onSelect={day=>open('日別実績',undefined,day)}/><BreakdownChart title="キャンペーン別の広告費" unit={c.currency} points={campaigns.map(id=>({id,label:rows.find(r=>r.campaignId===id)!.campaignName,value:sumAdMetrics(rows.filter(r=>r.campaignId===id)).spend,partial:!complete}))} onSelect={id=>open('キャンペーンの内訳',id)}/></div>{detail.drawer}</section>;
}
