'use client';
import {CountChart} from './data-visuals';
import {SelectableChart} from '../components/data-charts';
import {useEffect,useState} from 'react';
import {useIdentity} from '../company/session';
import {useBusinessFetch,usePageAccess} from './business-context';
import RangePicker from './date-range';
import {initialRange,rememberRange} from '@/lib/date-range';
import {aggregate,levels,statuses,changeStates,money,offset,defaultPolicy,type Policy,type Entity,type Report,type Change,type Level} from '@/lib/ads/model';
type Account={id:string;name:string;external_id:string;currency:string;timezone:string;policy:Policy;version:number;busy_id:string|null;last_sync:string|null};
type Row={id:string;account_id:string;status:string;data:Change;created_at:string;message:string};
type Data={accounts:Account[];selectedId:string;entities:Entity[];reports:Report[];changes:Row[];funnels:{id:string;name:string;source:string}[];cases:{id:string;title:string}[];ready:boolean};
const tabs={objects:'配信中の広告',numbers:'数字の比較',changes:'変更案',history:'実行履歴',settings:'接続・上限設定'};
const fmt=(n:number|null)=>n===null?'未取得':n.toLocaleString('ja-JP',{maximumFractionDigits:2});
const resultNames:Record<string,string>={link_click:'リンクのクリック',lead:'見込み客の登録',purchase:'購入',offsite_conversion_fb_pixel_purchase:'購入', 'offsite_conversion.fb_pixel_purchase':'ウェブサイト購入', 'offsite_conversion.fb_pixel_lead':'ウェブサイト登録',landing_page_view:'ページの表示',complete_registration:'登録完了'};
export default function AdsPanel({onDirtyChange,onImprovement,onSettings,settingsOnly=false}:{onSettings?:()=>void;settingsOnly?:boolean;onDirtyChange:(v:boolean)=>void;onImprovement:()=>void}){
 const fetch=useBusinessFetch(),user=useIdentity(),editable=usePageAccess('ads',true),[value,setValue]=useState<Data|null>(null),[range,setRange]=useState(initialRange),[accountId,setAccountId]=useState(''),[tab,setTab]=useState<keyof typeof tabs>(settingsOnly?'settings':'objects'),[level,setLevel]=useState<Level>('campaign'),[action,setAction]=useState(''),[filter,setFilter]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[dirty,setDirty]=useState(false),[selected,setSelected]=useState<Entity|null>(null),[field,setField]=useState('status'),[policy,setPolicy]=useState(defaultPolicy);
 useEffect(()=>{const controller=new AbortController();setValue(null);fetch('/api/marketing/ads?'+new URLSearchParams({...range,...(accountId?{accountId}:{})}),{signal:controller.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);return b;}).then(b=>{setValue(b);setPolicy(b.accounts.find((a:Account)=>a.id===b.selectedId)?.policy??defaultPolicy);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[fetch,accountId,range.start,range.end,reload]);
 useEffect(()=>{onDirtyChange(dirty);const f=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',f);return()=>{onDirtyChange(false);window.removeEventListener('beforeunload',f);};},[dirty,onDirtyChange]);
 const a=value?.accounts.find(a=>a.id===value.selectedId),unit=a?offset(a.currency):null;
 function guard(){if(dirty&&!confirm('未保存の編集を破棄しますか？'))return false;setDirty(false);setSelected(null);return true;}
 async function mutate(operation:string,extra:object={}){if(!value)return false;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/marketing/ads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:operation,requestId:crypto.randomUUID(),accountId:a?.id,...extra})}),b=await r.json();if(!r.ok)throw new Error(b.error);setNotice(b.message);if(b.needsAcknowledgement)return false;setDirty(false);setSelected(null);if(b.accountId)setAccountId(b.accountId);setReload(n=>n+1);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const actionTypes=[...new Set(value?.reports.flatMap(r=>Object.keys(r.actions))??[])],rows=value?.reports??[],totals=aggregate(rows,action);
 const subset=(o:Entity)=>rows.filter(r=>o.level==='campaign'?r.campaignId===o.id:o.level==='adset'?r.adsetId===o.id:r.adId===o.id);
 const objects=value?.entities.filter(o=>o.level===level&&(!filter||o.name.includes(filter)||o.id.includes(filter)))??[];
 const chartRows=rows.filter(r=>objects.some(o=>o.level==='campaign'?r.campaignId===o.id:o.level==='adset'?r.adsetId===o.id:r.adId===o.id));
 const chartMetrics=[['spend','広告費',a?.currency??''],['impressions','表示回数','回'],['clicks','クリック数','回'],['results','選んだ成果','件'],['cpa','成果1件の費用',a?.currency??''],['ctr','クリック率','%']] as const;
 const amount=(n:number|null)=>a?money(n,a.currency):'未取得';
 const changeValue=(c:Change,v:string|number)=>c.field==='status'?(statuses[String(v)]??String(v)):offset(c.currency)?money(Number(v)/offset(c.currency)!,c.currency):String(v);
 return <section>{!settingsOnly&&<div className="mp-tabs">{Object.entries(tabs).map(([k,n])=><button key={k} aria-pressed={tab===k} disabled={busy} onClick={()=>{if(k==='settings'&&onSettings){onSettings();return;}if(guard())setTab(k as keyof typeof tabs);}}>{n}</button>)}</div>}{error&&<p role="alert" className="ao-error">{error}<button onClick={()=>{if(guard()){setError('');setReload(n=>n+1);}}}>再取得</button></p>}{notice&&<p role="status" className="ao-note">{notice}</p>}{!value&&!error&&<p>広告の情報を取得中…</p>}{value&&<>
 <div className="mp-toolbar"><label>広告アカウント<select value={value.selectedId} disabled={busy} onChange={e=>{if(guard()){setAccountId(e.target.value);setAction('');}}}><option value="">接続を選択</option>{value.accounts.map(a=><option key={a.id} value={a.id}>{a.name}（{a.currency}）</option>)}</select></label>{a&&<p>Meta広告 / 集計時刻：{a.timezone} / 最終取得：{a.last_sync?new Date(a.last_sync).toLocaleString('ja-JP'):'未取得'}</p>}</div>
 {!a&&tab!=='settings'&&<div className="mp-empty"><h3>Meta広告を接続すると運用を始められます</h3><p>アカウントを接続し、広告の一覧と数字を取得してください。接続だけでは配信設定は変わりません。</p><button onClick={()=>onSettings?onSettings():setTab('settings')}>接続・上限設定へ</button></div>}
 {a&&['objects','numbers'].includes(tab)&&<><RangePicker timeZone={a.timezone} value={range} onChange={r=>{if(guard()){setRange(r);rememberRange(r);}}}/><div className="mp-toolbar"><button disabled={busy||!editable} onClick={()=>{if(guard())void mutate('sync',range);}}>この期間の広告と数字を取得</button><label>成果として見る行動<select aria-label="成果として見る行動" value={action} onChange={e=>setAction(e.target.value)}><option value="">成果の定義を選択</option>{actionTypes.map(k=><option key={k} value={k}>{resultNames[k]??k}</option>)}</select></label></div><p className="mp-muted">保存済みの実績を表示しています。取得は90日以内。成果は広告側の計測条件による値で、UTAGEの売上・登録数とは別です。同じ成果を示す行動を合算しません。</p>
 <div className="ad-summary">{[['広告費',amount(totals.spend)],['表示回数',fmt(totals.impressions)],['クリック数',fmt(totals.clicks)],['クリック率',totals.ctr===null?'未取得':fmt(totals.ctr)+'%'],['選んだ成果',fmt(totals.results)],['成果1件の費用',amount(totals.cpa)]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>
 <div className="mp-toolbar"><label>見る単位<select value={level} onChange={e=>setLevel(e.target.value as Level)}>{Object.entries(levels).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>名前・番号で絞る<input value={filter} onChange={e=>setFilter(e.target.value)}/></label></div>
 <div className="dc-layout"><SelectableChart title="広告実績の日別推移" kind="line" series={chartMetrics.map(([id,label,unit])=>({id,label,unit,points:[...new Set(chartRows.map(r=>r.date))].sort().map(date=>({id:date,date,label:date,value:aggregate(chartRows.filter(r=>r.date===date),action)[id]}))}))} note="選択中のアカウント・広告単位・名前の絞り込みを反映。率と単価は分子・分母から計算します。"/><SelectableChart title="広告別の比較" series={chartMetrics.map(([id,label,unit])=>({id,label,unit,points:objects.map(o=>({id:o.id,label:o.name,value:aggregate(subset(o),action)[id]}))}))}/></div>
 <div className="mp-table"><table><thead><tr><th>名称</th><th>配信状況</th><th>直接設定された日予算</th><th>広告費</th><th>表示</th><th>クリック</th><th>成果</th><th>成果1件の費用</th><th>操作</th></tr></thead><tbody>{objects.map(o=>{const m=aggregate(subset(o),action);return <tr key={o.id}><th>{o.name}<small className="ad-id">{o.id}</small></th><td>{statuses[o.effectiveStatus]??o.effectiveStatus}</td><td>{o.dailyBudget&&unit?amount(o.dailyBudget/unit):'直接設定なし'}</td><td>{amount(m.spend)}</td><td>{fmt(m.impressions)}</td><td>{fmt(m.clicks)}</td><td>{fmt(m.results)}</td><td>{amount(m.cpa)}</td><td><button disabled={!editable||busy} onClick={()=>{if(guard()){setSelected(o);setField('status');}}}>変更案を作る</button>{o.level==='campaign'&&<label>ファネル<select aria-label={o.name+'のファネル'} disabled={!editable||busy} value={o.funnelId??''} onChange={e=>void mutate('mapping',{entityId:o.id,funnelId:e.target.value})}><option value="">未登録</option>{value.funnels.filter(f=>f.source==='ads').map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}</td></tr>;})}</tbody></table></div>{!objects.length&&<p className="mp-empty">この条件の広告はまだありません。接続後に広告と数字を取得してください。</p>}
 {tab==='numbers'&&<><h3>日別の推移</h3><div className="mp-table"><table><thead><tr><th>日付</th><th>広告費</th><th>表示</th><th>クリック</th><th>成果</th><th>成果1件の費用</th></tr></thead><tbody>{[...new Set(rows.map(r=>r.date))].sort().map(day=>{const m=aggregate(rows.filter(r=>r.date===day),action);return <tr key={day}><th>{day}</th><td>{amount(m.spend)}</td><td>{fmt(m.impressions)}</td><td>{fmt(m.clicks)}</td><td>{fmt(m.results)}</td><td>{amount(m.cpa)}</td></tr>;})}</tbody></table></div><button onClick={onImprovement}>改善・診断で検討する</button></>}
 {selected&&<form className="mp-detail" onChange={()=>setDirty(true)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate('propose',{entityId:selected.id,level:selected.level,field,after:field==='daily_budget'?Number(f.get('after')):f.get('after'),reason:f.get('reason'),caseId:f.get('caseId')??''}).then(ok=>{if(ok)setTab('changes');});}}><h3>{selected.name}の変更案</h3><fieldset disabled={busy||!editable} className="mp-editor"><label>変更する項目<select aria-label="変更する項目" value={field} onChange={e=>setField(e.target.value)}><option value="status">停止・再開</option>{selected.level!=='ad'&&!!selected.dailyBudget&&unit&&<option value="daily_budget">日予算</option>}</select></label><p>現在：{field==='status'?(statuses[selected.status]??selected.status):unit?amount(selected.dailyBudget!/unit):'未取得'}</p>{field==='status'?<label>変更後<select name="after" defaultValue={selected.status==='ACTIVE'?'PAUSED':'ACTIVE'}><option value="PAUSED">停止する</option><option value="ACTIVE">再開する</option></select></label>:<label>変更後の日予算（{a.currency}）<input name="after" type="number" min="0.01" step={unit===1?'1':'0.01'} required/></label>}<label>変更する理由<textarea aria-label="変更する理由" name="reason" required maxLength={4000}/></label><label>関連する改善案件<select name="caseId"><option value="">関連付けなし</option>{value.cases.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label></fieldset><button disabled={busy}>変更案を保存</button><p>保存後に変更前後を確認し、承認してから実行できます。</p></form>}
 </>}
 {['changes','history'].includes(tab)&&<><CountChart title={tab==='changes'?'変更案の状態':'実行結果の内訳'} values={value.changes.filter(c=>(!a||c.account_id===a.id)&&(tab==='changes'?['draft','approved'].includes(c.status):!['draft','approved'].includes(c.status))).map(c=>c.status)} names={changeStates} note="現在読み込んだ変更履歴を集計しています。"/>{value.changes.filter(c=>(!a||c.account_id===a.id)&&(tab==='changes'?['draft','approved'].includes(c.status):!['draft','approved'].includes(c.status))).map(c=><article className="mp-detail" key={c.id}><h3>{c.data.entity.name}</h3><p>{changeStates[c.status]} / {levels[c.data.entity.level]} / {new Date(c.created_at).toLocaleString('ja-JP')}</p><div className="im-change"><div><h4>変更前</h4>{changeValue(c.data,c.data.before)}</div><div><h4>変更後</h4>{changeValue(c.data,c.data.after)}</div></div><p>{c.data.reason}</p>{c.data.caseId&&<p>関連する改善案件：{value.cases.find(v=>v.id===c.data.caseId)?.title??'関連付けあり'}</p>}{c.message&&<p>{c.message}</p>}<div className="mp-actions">{c.status==='draft'&&<button disabled={busy||!editable} onClick={()=>void mutate('approve',{accountId:c.account_id,changeId:c.id})}>この変更内容を承認</button>}{c.status==='approved'&&<button disabled={busy||!editable} onClick={()=>void mutate('execute',{accountId:c.account_id,changeId:c.id})}>承認した変更をMetaに反映</button>}{['draft','approved'].includes(c.status)&&<button disabled={busy||!editable} onClick={()=>void mutate('cancel',{accountId:c.account_id,changeId:c.id})}>変更案を取り消す</button>}{['uncertain','sending'].includes(c.status)&&<><button disabled={busy||!editable} onClick={()=>void mutate('reconcile',{accountId:c.account_id,changeId:c.id})}>Metaの現在値を確認</button><button disabled={busy||!editable} onClick={()=>{if(confirm('広告側の現在値を確認し、未反映として記録しますか？'))void mutate('reconcile',{accountId:c.account_id,changeId:c.id,acknowledge:true});}}>未反映として記録する</button></>}</div></article>)}{!value.changes.length&&<p className="mp-empty">変更案はまだありません。広告の一覧から対象を選んで作成してください。</p>}</>}
 {tab==='settings'&&<><CountChart title="広告アカウントの変更許可" values={value.accounts.map(a=>a.policy.enabled?'外部変更を許可':'外部変更を停止')} note="保存済みのアカウント設定。広告の現在の配信状況ではありません。"/><h3>Meta広告の接続</h3>{user.role==='owner'?<form className="im-form" onChange={()=>setDirty(true)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate('connect',{externalId:String(f.get('externalId')).trim(),token:f.get('token')});}}><fieldset disabled={busy||!value.ready}><label>広告アカウントID<input name="externalId" placeholder="act_123456789" required autoComplete="off"/></label><label>Meta接続キー<input name="token" type="password" required autoComplete="new-password"/></label><button>接続を確認して保存</button></fieldset><p>読取にはads_read、変更にはads_managementの権限を持つ接続キーを使用します。同じアカウントIDで保存するとキーを更新します。キーは暗号化して保存します。</p>{!value.ready&&<p>接続情報を暗号化するサーバー設定が必要です。</p>}</form>:<p>接続は全体管理者が設定します。</p>}{a&&<form className="mp-detail" onChange={()=>setDirty(true)} onSubmit={e=>{e.preventDefault();void mutate('policy',{policy,expectedVersion:a.version});}}><h3>{a.name}の実行範囲</h3><fieldset disabled={busy||user.role!=='owner'} className="mp-editor"><label><input type="checkbox" checked={policy.enabled} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/>承認した外部変更を許可する</label><label>予算変更時に設定できる日予算の上限（{a.currency}）<input type="number" min="0" step="0.01" value={policy.maxDailyBudget} onChange={e=>setPolicy({...policy,maxDailyBudget:e.target.valueAsNumber})}/></label><label>1回の予算変更率の上限（%）<input type="number" min="0" max="100" value={policy.maxChangePercent} onChange={e=>setPolicy({...policy,maxChangePercent:e.target.valueAsNumber})}/></label><div><h4>Astraに任せる広告操作</h4>{(['pause','resume','budget'] as const).map(op=><label key={op}><input type="checkbox" checked={policy.autonomousOperations?.includes(op)??false} onChange={e=>setPolicy({...policy,autonomousOperations:e.target.checked?[...(policy.autonomousOperations??[]),op]:(policy.autonomousOperations??[]).filter(v=>v!==op)})}/>{{pause:'広告の停止',resume:'広告の再開',budget:'上限内の日予算変更'}[op]}</label>)}</div><label>1日の実行試行回数（日本時間）<input type="number" min="1" max="30" value={policy.maxOperations} onChange={e=>setPolicy({...policy,maxOperations:e.target.valueAsNumber})}/></label></fieldset><p>上限はAstraから設定する値と操作回数に適用します。Metaの実消化額を止める上限ではありません。再開すると既存の広告設定で配信されます。</p><p>自律運用でこのアカウントを選ぶと、チェックした操作は案ごとの承認なしで実行できます。新規広告の入稿・広告本文の差し替えは含みません。</p>{user.role==='owner'&&<button disabled={busy}>実行範囲を保存</button>}{a.busy_id&&<p>実行中または結果確認待ちの変更があります。実行履歴から確認してください。</p>}</form>}</>}
 </>}</section>;
}
