'use client';
import {FactCharts} from './data-visuals';
import {DataChart} from '../components/data-charts';
import {useBusinessFetch,usePageAccess} from './business-context';
import { useEffect,useRef,useState } from 'react';
import { axisNames,measures,matches,total,ratio,group,previousPeriod,delta,validDate,type Fact,type Filter,type Measure,type Axis } from '@/lib/analytics/model';
import { emptyBusiness,type BusinessData } from '@/lib/marketing-business/types';
import RangePicker from './date-range';
import AnalyticsImport from './analytics-import';
import './analytics.css';
const day=()=>new Date().toLocaleDateString('sv-SE');
const initial=():Filter=>({start:typeof window!=='undefined'&&validDate(new URLSearchParams(location.search).get('start'))?new URLSearchParams(location.search).get('start')!:day().slice(0,7)+'-01',end:typeof window!=='undefined'&&validDate(new URLSearchParams(location.search).get('end'))?new URLSearchParams(location.search).get('end')!:day(),projectId:new URLSearchParams(location.search).get('projectId')??'',sourceType:new URLSearchParams(location.search).get('sourceType')??'',platform:new URLSearchParams(location.search).get('platform')??'',funnelId:new URLSearchParams(location.search).get('funnelId')??''});
const fmt=(n:number|null)=>n===null?'未取得':n.toLocaleString('ja-JP',{maximumFractionDigits:1});
const sourceNames:Record<string,string>={sns:'SNS',ads:'広告',other:'その他'};
export default function AnalyticsPanel({onSettings,onDiscuss,onImport,importOnly=false}:{onSettings:()=>void;onDiscuss:(text:string)=>void;onImport:()=>void;importOnly?:boolean}){
 const fetch=useBusinessFetch(),canEdit=usePageAccess('analytics',true);
 const [q,setQ]=useState<Filter>(initial),[rows,setRows]=useState<Fact[]>([]),[business,setBusiness]=useState<BusinessData>(emptyBusiness),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState(()=>importOnly?'import':['overview','cross','funnel'].includes(new URLSearchParams(location.search).get('analysisView')??'')?new URLSearchParams(location.search).get('analysisView')!:'overview'),[axis,setAxis]=useState<Axis>('projectId'),[col,setCol]=useState<Axis>('angle'),[metric,setMetric]=useState<Measure>('revenue'),[detail,setDetail]=useState<{title:string;rows:Fact[]}|null>(null),[loaded,setLoaded]=useState(false);
 const seq=useRef(0),detailHeading=useRef<HTMLHeadingElement>(null);const prior=validDate(q.start)&&validDate(q.end)&&q.start<=q.end?previousPeriod(q.start,q.end):null;
 async function load(){const version=++seq.current;setBusy(true);setError('');try{const config=await fetch('/api/marketing/business',{cache:'no-store'});const b=await config.json();if(!config.ok)throw new Error(b.error);if(importOnly){setBusiness(b.data);setLoaded(true);return;}if(!prior)throw new Error('開始日と終了日を確認してください。');const collected:Fact[]=[];let cursor:string|null='';do{const url=new URL('/api/marketing/analytics',location.origin);url.searchParams.set('start',prior.start);url.searchParams.set('end',q.end);if(cursor)url.searchParams.set('cursor',cursor);const r=await fetch(url),body=await r.json();if(!r.ok)throw new Error(body.error);collected.push(...body.rows);cursor=body.nextCursor;if(collected.length>20000)throw new Error('表示対象が多すぎます。期間を絞ってください。');}while(cursor);if(seq.current!==version)return;setRows(collected);setBusiness(b.data);setLoaded(true);}catch(e){if(seq.current===version){setRows([]);setLoaded(false);setError((e as Error).message);}}finally{if(seq.current===version)setBusy(false);}}
 useEffect(()=>{void load();return()=>{++seq.current;};},[q.start,q.end]);
 const current=rows.filter(r=>matches(r,q)),previous=prior?rows.filter(r=>matches(r,{...q,...prior})):[];
 const label=(a:Axis,id:string)=>a==='projectId'?business.projects?.find(p=>p.id===id)?.name??id:a==='funnelId'?business.funnels?.find(f=>f.id===id)?.name??id:a==='sourceType'?sourceNames[id]??id:id;
 const change=(p:Partial<Filter>)=>{setDetail(null);const next={...q,...p};setQ(next);const url=new URL(location.href);for(const [key,value] of Object.entries(next))url.searchParams.set(key,value);history.replaceState(null,'',url);};
 function open(title:string,data:Fact[]){setDetail({title,rows:data});setTimeout(()=>{detailHeading.current?.focus();detailHeading.current?.scrollIntoView({behavior:'smooth',block:'start'});},0);}
 const definitions=new Set(current.map(r=>r.definition));
 const groups=group(current,axis),days=group(current,'date'),seenDates=new Set(current.map(r=>r.date));
 const netCost=total(current,'cost'),sales=total(current,'sales');const cpa=ratio(current,'cost','sales');
 return <section className="an-root"><div className="an-heading"><div><span className="ao-eyebrow">成果から、改善する場所へ</span><h3>{importOnly?'日別の実績を登録':'同じ条件で数字を比べる'}</h3></div><button onClick={()=>void load()} disabled={busy}>データを更新</button></div>{!importOnly&&<><RangePicker value={q} onChange={change}/><div className="an-filters"><label>案件<select value={q.projectId} onChange={e=>change({projectId:e.target.value,funnelId:''})}><option value="">すべての案件</option>{business.projects?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>流入<select value={q.sourceType} onChange={e=>change({sourceType:e.target.value})}><option value="">すべて</option>{Object.entries(sourceNames).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>媒体<select value={q.platform} onChange={e=>change({platform:e.target.value})}><option value="">すべて</option>{[...new Set(rows.map(r=>r.platform))].sort().map(p=><option key={p}>{p}</option>)}</select></label><label>ファネル<select value={q.funnelId} onChange={e=>change({funnelId:e.target.value})}><option value="">すべて</option>{business.funnels?.filter(f=>!q.projectId||f.projectId===q.projectId).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div><div className="an-tabs">{[['overview','全体・案件比較'],['cross','掛け合わせ分析'],['funnel','ファネルの実績']].filter(([id])=>id!=='import'||canEdit).map(([id,n])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setDetail(null);const url=new URL(location.href);url.searchParams.set('analysisView',id);history.replaceState(null,'',url);}}>{n}</button>)}</div></>}
 {error&&<p className="an-warning" role="alert">{error}</p>}{busy&&<p role="status">選択した期間を読み込み中…</p>}
 {importOnly?<AnalyticsImport business={business} onSaved={()=>void load()}/>:!busy&&loaded&&<><div className="an-quality"><strong>{current.length}件の実績記録 / 実績がある日：{seenDates.size}日</strong><span>比較期間：{prior?.start}〜{prior?.end} / 日本円・日付は元データ基準</span><span>未記録日は0とは扱いません。個人の重複排除・購入経路の割当は未接続です。</span>{definitions.size>1&&<strong>集計定義が{definitions.size}種類あります。合算・前期比較の前に、明細で計上範囲が重複しないことを確認してください。</strong>}</div>{!current.length?<div className="an-empty"><h4>この条件の実績はまだありません</h4><p>案件とファネルを登録してから、日別の実績を取り込んでください。サンプル値で成果を表示することはしません。</p><button disabled={!canEdit} onClick={onImport}>実績を取り込む</button><button onClick={onSettings}>案件・ファネルを登録</button></div>:<>
 {tab==='overview'&&<><FactCharts rows={current} axis={axis} label={id=>label(axis,id)} onSelect={id=>open(label(axis,id)+'の明細',groups.find(([key])=>key===id)?.[1]??[])}/><div className="an-cards">{(Object.keys(measures) as Measure[]).map(k=>{const sum=total(current,k),diff=delta(sum,total(previous,k));return <button key={k} onClick={()=>open(measures[k]+'の明細',current)}><span>{measures[k]}</span><strong>{fmt(sum.value)}<small>{['registrations','sales'].includes(k)?'件':'円'}</small></strong><small>{sum.missing?`${sum.missing}記録が未取得・取得済み分の小計`:`記録済み${sum.count}件の合計`}</small><small>前期間との差：{diff===null?'比較不能':`${diff>0?'+':''}${fmt(diff)}`}</small></button>;})}</div><p className="an-note">期間内の費用 ÷ 期間内の成約：{cpa===null?'算出不可':fmt(cpa)+'円'}。費用 {fmt(netCost.value)}円 / 成約 {fmt(sales.value)}件。成約の流入元への帰属は未検証です。前期差は記録済みの範囲同士の差で、未記録日を補完しません。</p><div className="an-heading"><h4>どこで成果が変わったか</h4><label>比較する単位<select value={axis} onChange={e=>setAxis(e.target.value as Axis)}>{Object.entries(axisNames).map(([id,n])=><option value={id} key={id}>{n}</option>)}</select></label></div><div className="an-scroll"><table><thead><tr><th>{axisNames[axis]}</th><th>集客費用</th><th>登録</th><th>成約</th><th>確定売上</th><th>前期の売上差</th><th>入金</th><th>未取得項目</th></tr></thead><tbody>{groups.map(([id,rs])=>{const prev=previous.filter(r=>(r[axis]||'未分類')===id),diff=delta(total(rs,'revenue'),total(prev,'revenue'));return <tr key={id}><th><button onClick={()=>open(label(axis,id)+'の明細',rs)}>{label(axis,id)}</button></th>{(['cost','registrations','sales','revenue'] as Measure[]).map(k=><td key={k}><button onClick={()=>open(label(axis,id)+' / '+measures[k],rs)}>{fmt(total(rs,k).value)}{total(rs,k).missing?'*':''}</button></td>)}<td>{diff===null?'比較不能':`${diff>0?'+':''}${fmt(diff)}`}</td><td>{fmt(total(rs,'payments').value)}</td><td>{(Object.keys(measures) as Measure[]).filter(k=>total(rs,k).missing).map(k=>measures[k]).join('・')||'なし'}</td></tr>;})}</tbody></table></div><h4>日別の確定売上</h4><div className="an-trend">{days.map(([date,rs])=>{const value=total(rs,'revenue').value,max=Math.max(1,...days.map(([,d])=>total(d,'revenue').value??0));return <button key={date} onClick={()=>open(date+'の明細',rs)}><span>{date}</span><i style={{width:`${(value??0)/max*60}%`}}/><strong>{fmt(value)}円{total(rs,'revenue').missing?'（一部未取得）':''}</strong></button>;})}</div></>}
 {tab==='cross'&&<><h4>2つの条件を掛け合わせて比較する</h4><div className="an-fields"><label>行<select value={axis} onChange={e=>setAxis(e.target.value as Axis)}>{Object.entries(axisNames).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>列<select value={col} onChange={e=>setCol(e.target.value as Axis)}>{Object.entries(axisNames).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>見る数字<select value={metric} onChange={e=>setMetric(e.target.value as Measure)}>{Object.entries(measures).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label></div>{axis!==col&&<DataChart title={'掛け合わせの比較 / '+measures[metric]} unit={['sales','registrations'].includes(metric)?'件':'円'} points={groups.flatMap(([id,rs])=>group(rs,col).map(([column,cells])=>{const v=total(cells,metric);return{id:JSON.stringify([id,column]),label:label(axis,id)+' × '+label(col,column),value:v.value,partial:v.missing>0};}))} note="選択した行・列・指標の組み合わせです。条件のない組み合わせは表示しません。"/>}{axis===col?<p>行と列は違う切り口を選んでください。</p>:<div className="an-scroll"><table><thead><tr><th>{axisNames[axis]} × {axisNames[col]}</th>{group(current,col).slice(0,30).map(([id])=><th key={id}>{label(col,id)}</th>)}</tr></thead><tbody>{groups.slice(0,100).map(([id,rs])=><tr key={id}><th>{label(axis,id)}</th>{group(current,col).slice(0,30).map(([column])=>{const cells=rs.filter(r=>(r[col]||'未分類')===column),sum=total(cells,metric);return <td key={column}><button disabled={!cells.length} onClick={()=>open(label(axis,id)+' × '+label(col,column),cells)}>{fmt(sum.value)}{sum.missing?'*':''}<small>{cells.length}記録</small></button></td>;})}</tr>)}</tbody></table><p>最大100行×30列。多い場合は共通条件で絞ってください。*は一部未取得。</p></div>}</>}
 {tab==='funnel'&&<><h4>登録した導線に実績を重ねる</h4><p>各段階の記録件数です。同じ人の通過順序が未接続のため、移行率や離脱率は算出しません。</p>{[...new Map(current.map(r=>[JSON.stringify(r.funnel),r.funnel])).entries()].map(([snapshot,f])=>{const rs=current.filter(r=>JSON.stringify(r.funnel)===snapshot);return <section key={snapshot} className="an-funnel"><h4>{f.name}</h4><small>取込時の定義 / {rs.length}記録。同名でも定義が違う場合は分けて表示。</small><DataChart title={f.name+'の段階別記録'} points={f.stages.map(s=>{const recorded=rs.filter(r=>typeof r.stageCounts[s.id]==='number');return{id:s.id,label:s.name,value:recorded.length?recorded.reduce((n,r)=>n+r.stageCounts[s.id]!,0):null,partial:recorded.length<rs.length};})} note="各段階の記録件数。通過率や離脱率ではありません。"/><div className="an-stage-list">{f.stages.map(s=>{const recorded=rs.filter(r=>typeof r.stageCounts[s.id]==='number'),n=recorded.length?recorded.reduce((n,r)=>n+r.stageCounts[s.id]!,0):null;return <button key={s.id} onClick={()=>open(f.name+' / '+s.name,rs)}><span>{s.name}</span><strong>{fmt(n)}件</strong><small>{recorded.length}/{rs.length}記録で取得</small><small>{(f.connections??f.stages.slice(1).map((v,i)=>({from:f.stages[i].id,to:v.id}))).filter(e=>e.from===s.id).map(e=>'→ '+f.stages.find(v=>v.id===e.to)?.name).join(' / ')}</small></button>;})}</div></section>;})}</>}
 </>}</>}
 {detail&&<section className="an-detail"><div className="an-heading"><h4 ref={detailHeading} tabIndex={-1}>{detail.title}</h4><button onClick={()=>setDetail(null)}>明細を閉じる</button></div><p>条件：{q.start}〜{q.end} / {detail.rows.length}記録。元データの定義を確認して判断してください。</p><div className="an-scroll"><table><thead><tr><th>日付・媒体</th><th>投稿／広告・訴求</th><th>費用</th><th>登録 / 成約</th><th>売上 / 入金 / 返金</th><th>出典・定義・段階</th></tr></thead><tbody>{detail.rows.map(r=><tr key={r.id}><td>{r.date}<br/>{r.platform}</td><td>{r.content||'未分類'}<br/>{r.angle||'未分類'} / {r.format||'未分類'}</td><td>{fmt(r.values.cost)}</td><td>{fmt(r.values.registrations)} / {fmt(r.values.sales)}</td><td>{fmt(r.values.revenue)} / {fmt(r.values.payments)} / {fmt(r.values.refunds)}</td><td><details><summary>{r.source} / {r.externalId}</summary><p>{r.definition}</p><p>取得日 {r.collectedAt}</p>{r.funnel.stages.map(s=><p key={s.id}>{s.name}：{fmt(r.stageCounts[s.id]??null)}</p>)}</details></td></tr>)}</tbody></table></div><button onClick={()=>onDiscuss(`分析依頼の下書き：${detail.title}。期間${q.start}〜${q.end}。対象${detail.rows.length}記録。売上${fmt(total(detail.rows,'revenue').value)}円、費用${fmt(total(detail.rows,'cost').value)}円。出典：${[...new Set(detail.rows.map(r=>r.source))].join('、')}。集計定義・欠測・帰属の確認から調べたい。`)}>実行管理へ</button><p>実行管理で取り組む施策を登録してください。Astraの自動実行は未接続です。</p></section>}
 </section>;
}
