'use client';
import AgentSkills from './agent-skills';
import AgentCampaigns from './agent-campaigns';
import {actionNames as names} from '@/lib/autonomy/board';
import {useDataDetail} from './data-detail';
import {CountChart} from './data-visuals';
import {SelectableChart,DataChart} from '../components/data-charts';
import {useEffect,useState} from 'react';
import {useIdentity} from '../company/session';
import {useBusinessFetch} from './business-context';
import {defaultPolicy,jobStates,type Policy} from '@/lib/autonomy/model';
const time=(v:number|string|null)=>v?new Date(v).toLocaleString('ja-JP'):'未設定';
type Job={id:string;status:string;summary:string;question:string;nextAt:number|null;steps:number;calls:number;tokens:number;model:string;created_at:string};
type Data={policy:Policy;version:number;nextAt:number|null;jobs:Job[];actions:{id:string;job_id:string;name:string;status:string;result:string;created_at:string}[];accounts:{id:string;name:string;policy:{enabled:boolean;autonomousOperations?:string[]}}[];model:string;modelReady:boolean;storageReady:boolean;runnerReady:boolean};
export default function AutonomyPanel({onDirtyChange,onAds,onSettings,onCase,onKnowledge,settingsOnly=false}:{onCase?:(id:string)=>void;onKnowledge?:()=>void;onSettings?:()=>void;settingsOnly?:boolean;onDirtyChange:(v:boolean)=>void;onAds?:()=>void}){
 const detail=useDataDetail();const fetch=useBusinessFetch(),user=useIdentity(),[value,setValue]=useState<Data|null>(null),[policy,setPolicy]=useState(defaultPolicy),[tab,setTab]=useState<'now'|'settings'|'history'|'skills'>(settingsOnly?'settings':'now'),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{if(dirty)return;let live=true,timer:ReturnType<typeof setTimeout>;const load=async()=>{try{const r=await fetch('/api/marketing/autonomy'),b=await r.json();if(!r.ok)throw new Error(b.error);if(live){setValue(b);if(!dirty)setPolicy(b.policy);}}catch(e){if(live)setError((e as Error).message);}finally{if(live)timer=setTimeout(load,5000);}};void load();return()=>{live=false;clearTimeout(timer);};},[fetch,reload,dirty]);
 useEffect(()=>{onDirtyChange(dirty);const handler=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',handler);return()=>{onDirtyChange(false);window.removeEventListener('beforeunload',handler);};},[dirty,onDirtyChange]);
 async function mutate(action:string,extra:object={}){setBusy(true);setError('');try{const r=await fetch('/api/marketing/autonomy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})}),b=await r.json();if(!r.ok)throw new Error(b.error);setNotice(b.message);setDirty(false);setReload(n=>n+1);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 function choose(next:typeof tab){if(next==='settings'&&onSettings){onSettings();return;}if(dirty&&!confirm('未保存の編集を破棄しますか？'))return;setDirty(false);setTab(next);}
 const latest=value?.jobs[0],latestAction=value?.actions.find(a=>a.job_id===latest?.id),owner=user.role==='owner';
 function showJob(id:string){const job=value?.jobs.find(j=>j.id===id);if(!job)return;detail.show({title:time(job.created_at)+' / '+(jobStates[job.status]??job.status),context:[job.model,'呼び出し '+job.calls+'回 / 判断・操作 '+job.steps+'回 / '+job.tokens+'トークン'],columns:['日時','操作','状態','結果'],rows:value!.actions.filter(a=>a.job_id===id).map(a=>[a.created_at,names[a.name]??a.name,a.status,a.result]),note:'取得済みの直近100操作の範囲です。トークン数は仕事に保存された合計で、操作ごとの使用量や料金は記録されていません。'});}
 useEffect(()=>{detail.show(null);},[fetch,tab]);
 return <section>{!settingsOnly&&<div className="ad-agent-intro"><div><small>Astra</small><h3>事業エージェント</h3><p>目標と実績、ナレッジから改善案を作り、任された範囲で作業と観測を進めます。</p></div>{onAds&&<button onClick={onAds}>広告アカウントと操作上限を設定</button>}</div>}{!settingsOnly&&<div className="mp-tabs">{([['now','今の取り組み'],['settings','目的・任せる範囲'],['skills','スキル'],['history','判断と実行の履歴']] as const).map(([k,label])=><button key={k} aria-pressed={tab===k} onClick={()=>choose(k)}>{label}</button>)}</div>}{error&&<p role="alert" className="ao-error">{error}</p>}{notice&&<p role="status" className="ao-note">{notice}</p>}{busy&&<p role="status">設定を保存しています…</p>}{!value&&!error&&<p>現在の仕事を確認しています…</p>}{value&&<>
 {tab==='history'&&<div className="dc-layout"><CountChart title="Astraの仕事の状態" values={value.jobs.map(j=>j.status)} names={jobStates} columns={['日時','状態','報告','モデル呼出','操作数','トークン']} records={value.jobs.map(j=>[time(j.created_at),jobStates[j.status]??j.status,j.summary,j.calls,j.steps,j.tokens])} note="取得済みの仕事履歴を集計。施策の効果や成功率ではありません。"/><SelectableChart onSelect={id=>showJob(id)} title="仕事ごとの利用量" series={([['calls','モデル呼び出し','回'],['steps','判断・操作','回'],['tokens','利用トークン','トークン']] as const).map(([id,label,unit])=>({id,label,unit,points:value.jobs.slice().reverse().map(j=>({id:j.id,label:time(j.created_at),value:j[id]}))}))}/></div>}
 {tab==='skills'&&<AgentSkills onDirtyChange={setDirty}/>}
 {tab==='settings'&&<DataChart title="接続・実行基盤の準備状況" unit="項目" points={[{id:'ready',label:'準備済み',value:[value.modelReady,value.storageReady,value.runnerReady].filter(Boolean).length},{id:'missing',label:'未接続',value:[value.modelReady,value.storageReady,value.runnerReady].filter(v=>!v).length}]} note="モデル・接続情報の保存先・実行基盤の3項目。目的や操作許可は下で個別に設定します。"/>}
 {tab==='now'&&<><AgentCampaigns enabled={value.policy.enabled} onCase={onCase} onKnowledge={onKnowledge}/><article className="mp-detail"><h3>{!value.policy.enabled?'自律運用は停止中です':latest?jobStates[latest.status]:'開始を待っています'}</h3><p>{value.policy.purpose||'達成したい目標と、任せる範囲を設定してください。'}</p><p>次の判断・観測：{time(value.nextAt)}</p>{!value.modelReady&&<p>モデルを接続すると、Astraが判断と実行を始められます。</p>}{!value.runnerReady&&<p>自律運用の実行基盤が未接続です。</p>}<div className="mp-actions"><button onClick={()=>choose('settings')}>目的・任せる範囲を設定</button>{owner&&<button disabled={busy||!value.policy.enabled} onClick={()=>void mutate('stop')}>自律運用を停止</button>}</div></article>{latest&&<article className="mp-detail"><h3>Astraからの報告</h3>{latestAction&&<p>直近の調査・操作：{names[latestAction.name]??latestAction.name} / {latestAction.status==='started'?'結果未確定':latestAction.status==='failed'?'要確認':'処理済み'}</p>}<pre className="im-output">{latest.summary}</pre><p>{latest.calls}回のモデル呼び出し / {latest.steps}回の判断・操作 / {latest.tokens.toLocaleString()}トークン</p>{latest.question&&<p className="ao-note">{latest.question}</p>}</article>}{owner&&<form className="im-form" onChange={()=>setDirty(true)} onSubmit={e=>{e.preventDefault();void mutate('resume',{message:new FormData(e.currentTarget).get('message')??''});}}><label>追加の指示・Astraへの返答<textarea aria-label="追加の指示・Astraへの返答" name="message" maxLength={2000} rows={3}/></label><button disabled={busy||!value.policy.enabled}>この内容で再開する</button></form>}<p className="mp-muted">ブラウザを閉じても予約した仕事は続きます。許可のない操作や不足情報はここに残ります。停止時に既に送信した操作は、履歴で結果を確認してください。</p></>}
 {tab==='settings'&&<><form className="mp-detail" onChange={()=>setDirty(true)} onSubmit={e=>{e.preventDefault();void mutate('save',{policy,expectedVersion:value.version});}}><h3>Astraに任せる目的</h3><fieldset disabled={busy||!owner} className="mp-editor"><label className="mp-wide">達成したいこと・守ってほしいこと<textarea aria-label="達成したいこと・守ってほしいこと" rows={5} value={policy.purpose} maxLength={4000} onChange={e=>setPolicy({...policy,purpose:e.target.value})}/></label><label>期限（任意）<input type="date" value={policy.deadline} onChange={e=>setPolicy({...policy,deadline:e.target.value})}/></label><label><input type="checkbox" checked={policy.enabled} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/>自律運用を有効にする（モデルAPIの利用料が発生）</label><div><h4>任せる内部作業</h4>{(['record_campaign','create_post_draft'] as const).map(op=><label key={op}><input type="checkbox" checked={policy.internal.includes(op)} onChange={e=>setPolicy({...policy,internal:e.target.checked?[...policy.internal,op]:policy.internal.filter(v=>v!==op)})}/>{op==='record_campaign'?'施策を作成する':'SNSの下書きを作成する'}</label>)}</div><div><h4>変更を任せる広告アカウント</h4>{value.accounts.map(a=><label key={a.id}><input type="checkbox" checked={policy.adAccounts.includes(a.id)} onChange={e=>setPolicy({...policy,adAccounts:e.target.checked?[...policy.adAccounts,a.id]:policy.adAccounts.filter(id=>id!==a.id)})}/>{a.name}（{a.policy.enabled&&a.policy.autonomousOperations?.length?'広告側の自律操作設定あり':'広告側でも操作の許可が必要'}）</label>)}{!value.accounts.length&&<p>広告アカウントは未接続です。</p>}</div><label>次回時刻をAstraが決めなかった場合の間隔（時間）<input type="number" min="1" max="168" value={policy.intervalHours} onChange={e=>setPolicy({...policy,intervalHours:e.target.valueAsNumber})}/></label><label>1日の仕事の開始回数<input type="number" min="1" max="24" value={policy.maxRunsDay} onChange={e=>setPolicy({...policy,maxRunsDay:e.target.valueAsNumber})}/></label><label>1つの仕事でのモデル呼び出し上限<input type="number" min="1" max="20" value={policy.maxModelCalls} onChange={e=>setPolicy({...policy,maxModelCalls:e.target.valueAsNumber})}/></label><label>1つの仕事での判断・操作回数の上限<input type="number" min="2" max="60" value={policy.maxSteps} onChange={e=>setPolicy({...policy,maxSteps:e.target.valueAsNumber})}/></label></fieldset><p>調べる順序・期間・資料・施策・次の評価時点はAstraが選びます。外部の広告変更には、広告画面の許可と予算上限も適用します。</p><div className="mp-actions">{owner&&<button disabled={busy}>目的と任せる範囲を保存</button>}{onAds&&<button type="button" onClick={onAds}>広告の操作・予算上限を設定</button>}</div><p className="mp-muted">回数制限は金額の保証ではありません。実際のモデル費用はAPI提供元で確認してください。SNS公開・LP変更・配信シナリオ変更は未接続です。</p></form>
 {owner&&<form className="im-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),form=e.currentTarget;void mutate('model',{model:f.get('model'),key:f.get('key')}).then(ok=>{if(ok)form.reset();});}}><h3>モデルの接続</h3><p>{value.modelReady?'接続設定あり':'未接続'} / {value.model}</p><fieldset disabled={busy||!value.storageReady}><label>利用するモデル<input name="model" defaultValue={value.model} required autoComplete="off"/></label><label>OpenAI API接続キー<input name="key" type="password" required autoComplete="new-password"/></label><button>接続を確認して保存</button></fieldset><p>キーはこの画面で入力してください。チャットへの貼り付けは不要です。接続確認はモデル一覧の読取だけで、判断・実行は目的の設定を有効にしてから始まります。</p></form>}</>}
 {tab==='history'&&<><p className="mp-muted">直近30件の仕事と100件の操作を表示します。施策一覧の集計は、この履歴の表示件数に制限されません。</p>{value.jobs.map(j=><article className="mp-detail" key={j.id}><h3>{time(j.created_at)} / {jobStates[j.status]}</h3><pre className="im-output">{j.summary}</pre><p>モデル：{j.model} / 呼び出し：{j.calls}回 / {j.tokens.toLocaleString()}トークン</p>{value.actions.filter(a=>a.job_id===j.id).reverse().map(a=><details key={a.id}><summary>{names[a.name]??a.name} — {{started:'結果を確認中',done:'処理済み',failed:'要確認'}[a.status]??a.status}</summary><pre className="im-output">{a.result}</pre></details>)}</article>)}{!value.jobs.length&&<p className="mp-empty">まだ仕事は始まっていません。</p>}</>}
 </>}</section>;
}
