'use client';
import {useEffect,useRef,useState} from 'react';
import {useBusinessFetch,usePageAccess} from './business-context';
import {revenueModelNames} from '@/lib/business';
import {commerceTotals,type Product,type Sale,type Commerce} from '@/lib/commerce';
import {initialRange,rememberRange,validRange} from '@/lib/date-range';
import RangePicker from './date-range';
import {DetailValue,useDataDetail} from './data-detail';
import {commerceDetailRows} from '@/lib/data-detail';
import './commerce.css';
type Snapshot={version:number;data:Commerce};
type Entry=Pick<Sale,'id'|'productId'|'date'|'quantity'|'amount'|'fee'|'payment'|'kind'|'originalId'|'reference'|'notes'>;
const yen=(v:number)=>'¥'+v.toLocaleString('ja-JP');
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});
export default function CommercePanel({onDirtyChange}:{onDirtyChange:(dirty:boolean)=>void}){
 const fetch=useBusinessFetch(),editable=usePageAccess('business',true);
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[range,setRange]=useState(initialRange),[filter,setFilter]=useState(''),[showVoid,setShowVoid]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[product,setProduct]=useState<Product|null>(null),[entry,setEntry]=useState<Entry|null>(null);
 const detail=useDataDetail();
 useEffect(()=>{detail.show(null);},[range.start,range.end,filter,snapshot?.version]);
 const request=useRef<{body:string;id:string}|null>(null),formHeading=useRef<HTMLHeadingElement>(null),feedback=useRef<HTMLDivElement>(null),productsList=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{if(error||notice){feedback.current?.focus();feedback.current?.scrollIntoView({block:'nearest'});}},[error,notice]);
 async function load(signal?:AbortSignal){const r=await fetch('/api/marketing/commerce',{signal,cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error);setSnapshot(b);}
 useEffect(()=>{const c=new AbortController();void load(c.signal).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[fetch]);
 useEffect(()=>{onDirtyChange(dirty);const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>{onDirtyChange(false);window.removeEventListener('beforeunload',guard);};},[dirty,onDirtyChange]);
 const change=()=>{setDirty(true);request.current=null;setNotice('');};
 function close(){if(dirty&&!confirm('未保存の変更を破棄しますか？'))return false;setProduct(null);setEntry(null);setDirty(false);request.current=null;return true;}
 function focus(){setTimeout(()=>formHeading.current?.focus(),0);}
 function openProduct(p?:Product){if(!close())return;setProduct(p??{id:crypto.randomUUID(),name:'',model:'content',price:0,archived:false,updatedAt:''});if(!p)setDirty(true);focus();}
 function openSale(p?:Product,original?:Sale){if(!close())return;const chosen=p??snapshot?.data.products.find(v=>!v.archived);if(!chosen)return;setEntry({id:crypto.randomUUID(),productId:chosen.id,date:today(),quantity:1,amount:original?Math.max(0,original.amount-(snapshot?.data.entries.filter(e=>e.originalId===original.id&&!e.voidReason).reduce((n,e)=>n+e.amount,0)??0)):chosen.price,fee:0,payment:'paid',kind:original?'refund':'sale',originalId:original?.id??'',reference:'',notes:''});setDirty(true);focus();}
 async function save(body:Record<string,unknown>,finish=true){if(!snapshot||busy)return;setBusy(true);setError('');setNotice('');
 const payload=JSON.stringify({expectedVersion:snapshot.version,...body});if(request.current?.body!==payload)request.current={body:payload,id:crypto.randomUUID()};
 try{const r=await fetch('/api/marketing/commerce',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...JSON.parse(payload),requestId:request.current.id})}),b=await r.json();if(!r.ok)throw new Error(b.error);setSnapshot(b);request.current=null;if(finish){setDirty(false);setEntry(null);setProduct(null);}if(body.action==='record_sale'&&entry){const next={start:entry.date<range.start?entry.date:range.start,end:entry.date>range.end?entry.date:range.end};setRange(next);rememberRange(next);if(filter&&filter!==entry.productId)setFilter('');}if(body.action==='save_product'&&productsList.current)productsList.current.open=true;setNotice('保存しました');}
 catch(e){setError(e instanceof Error?e.message:'保存できませんでした。');}finally{setBusy(false);}}
 function download(){if(!snapshot)return;const safe=(v:unknown)=>'"'+String(v??'').replace(/^\s*[=+@-]/,"'$&").replaceAll('"','""')+'"';const rows=snapshot.data.entries.filter(e=>e.date>=range.start&&e.date<=range.end&&(!filter||e.productId===filter));const text='\uFEFF'+[['日付','商品','種類','数量','金額（円）','手数料（円）','入金状態','注文番号','メモ','取消理由'],...rows.map(e=>[e.date,e.productName,e.kind==='sale'?'売上':'返金',e.quantity,e.amount,e.fee,e.payment==='paid'?'入金済':'未入金',e.reference,e.notes,e.voidReason])].map(row=>row.map(safe).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='sales-'+range.start+'-'+range.end+'.csv';a.click();URL.revokeObjectURL(url);}
 function showEntries(title:string,entries:Sale[],value?:string){detail.show({title,value,context:[range.start+'〜'+range.end,'商品・売上の記帳 / 税込JPY / 販売日・返金日基準'],columns:['日付','商品','種類','数量','金額（円）','手数料（円）','状態','注文番号','メモ','記録ID','返金元ID','登録日時','更新日時','取消理由'],rows:entries.map(e=>[e.date,e.productName,e.kind==='sale'?'売上':'返金',e.quantity,e.amount,e.fee,e.kind==='sale'?(e.payment==='paid'?'入金済':'未入金'):(e.payment==='paid'?'返金済':'未返金'),e.reference,e.notes,e.id,e.originalId,e.createdAt,e.updatedAt,e.voidReason]),note:'APIやCSVの実績とは合算していません。金額を訂正する場合は、元の記帳を取り消して新しい記録を追加します。'});}
 const data=snapshot?.data,totals=data&&validRange(range)?commerceTotals(data.entries.filter(e=>!filter||e.productId===filter),range.start,range.end):null;
 const rows=data?.entries.filter(e=>(showVoid||!e.voidReason)&&e.date>=range.start&&e.date<=range.end&&(!filter||e.productId===filter)).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));
 return <section className="commerce-panel"><div ref={feedback} tabIndex={-1}>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</div>
 {!snapshot?<p role="status">{error?'取得できませんでした。':'商品と売上を読み込み中…'}<button onClick={()=>void load().catch(e=>setError(e.message))}>再取得</button></p>:<>
 <div className="mp-toolbar"><div className="commerce-actions">{editable&&<><button className="ao-primary" disabled={busy||!data?.products.some(p=>!p.archived)} onClick={()=>openSale()}>売上を記帳</button><button disabled={busy} onClick={()=>openProduct()}>商品を追加</button></>}<button disabled={busy} onClick={()=>{if(dirty&&!confirm('再取得して最新の版で保存しますか？入力は残ります。'))return;request.current=null;void load().catch(e=>setError(e.message));}}>再取得</button></div><button disabled={!validRange(range)} onClick={download}>CSVを保存</button></div>
 <RangePicker value={range} onChange={v=>{setRange(v);rememberRange(v);}}/>
 <div className="mp-toolbar"><label>商品<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">すべての商品</option>{data?.products.map(p=><option key={p.id} value={p.id}>{p.name}{p.archived?'（販売終了）':''}</option>)}</select></label><label className="commerce-check"><input type="checkbox" checked={showVoid} onChange={e=>setShowVoid(e.target.checked)}/>取消済みも表示</label></div>
 {totals&&<div className="summary-cards">{([['gross','売上',totals.gross],['refunds','返金',totals.refunds],['fees','手数料',totals.fees],['net','売上 − 返金 − 手数料',totals.net],['pending','未入金の売上',totals.pending]] as const).map(([key,label,value])=><article key={key}><small>{label}</small><strong><DetailValue label={label} onClick={()=>showEntries(label,commerceDetailRows(data!.entries,key,range.start,range.end,filter),yen(value))}>{yen(value)}</DetailValue></strong></article>)}</div>}
 {product&&<form className="mp-detail" onSubmit={e=>{e.preventDefault();void save({action:'save_product',product});}}><h3 tabIndex={-1} ref={formHeading}>{data?.products.some(p=>p.id===product.id)?'商品を編集':'商品を追加'}</h3><fieldset className="mp-editor" disabled={busy||!editable}><label className="mp-wide">商品名<input required maxLength={100} value={product.name} onChange={e=>{setProduct({...product,name:e.target.value});change();}}/></label><label>販売方法<select value={product.model} onChange={e=>{setProduct({...product,model:e.target.value as Product['model']});change();}}>{Object.entries(revenueModelNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>税込価格（円）<input type="number" required min={0} max={100000000000} step={1} value={product.price} onChange={e=>{setProduct({...product,price:Number(e.target.value)});change();}}/></label><label className="commerce-check"><input type="checkbox" checked={product.archived} onChange={e=>{setProduct({...product,archived:e.target.checked});change();}}/>販売終了</label></fieldset><div className="commerce-actions"><button type="submit" className="ao-primary" disabled={busy||!dirty}>商品を保存</button><button type="button" disabled={busy} onClick={close}>閉じる</button></div></form>}
 {entry&&<form className="mp-detail" onSubmit={e=>{e.preventDefault();void save({action:'record_sale',entry});}}><h3 tabIndex={-1} ref={formHeading}>{entry.kind==='refund'?'返金を記帳':'売上を記帳'}</h3><fieldset className="mp-editor" disabled={busy||!editable}><label>商品<select required disabled={entry.kind==='refund'} value={entry.productId} onChange={e=>{const p=data?.products.find(p=>p.id===e.target.value);if(p)setEntry({...entry,productId:p.id,amount:p.price*entry.quantity});change();}}>{data?.products.filter(p=>!p.archived||p.id===entry.productId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{entry.kind==='sale'?'販売日':'返金日'}<input required type="date" value={entry.date} onChange={e=>{setEntry({...entry,date:e.target.value});change();}}/></label><label>数量<input required type="number" min={1} max={100000} step={1} value={entry.quantity} onChange={e=>{const quantity=Number(e.target.value),p=data?.products.find(p=>p.id===entry.productId);setEntry({...entry,quantity,amount:entry.kind==='sale'?(p?.price??0)*quantity:entry.amount});change();}}/></label><label>{entry.kind==='sale'?'売上合計':'返金額'}（税込・円）<input required type="number" min={entry.kind==='sale'?0:1} max={100000000000} step={1} value={entry.amount} onChange={e=>{setEntry({...entry,amount:Number(e.target.value)});change();}}/></label><label>手数料（円）<input required type="number" min={0} max={entry.amount} step={1} value={entry.fee} onChange={e=>{setEntry({...entry,fee:Number(e.target.value)});change();}}/></label><label>{entry.kind==='sale'?'入金状態':'返金状態'}<select value={entry.payment} onChange={e=>{setEntry({...entry,payment:e.target.value as Entry['payment']});change();}}><option value="paid">{entry.kind==='sale'?'入金済':'返金済'}</option><option value="pending">{entry.kind==='sale'?'未入金':'未返金'}</option></select></label><label className="mp-wide">注文番号（任意）<input maxLength={150} value={entry.reference} onChange={e=>{setEntry({...entry,reference:e.target.value});change();}}/></label><label className="mp-wide">メモ<textarea maxLength={1000} value={entry.notes} onChange={e=>{setEntry({...entry,notes:e.target.value});change();}}/></label></fieldset><div className="commerce-actions"><button type="submit" className="ao-primary" disabled={busy||!dirty}>{busy?'保存中…':'記帳する'}</button><button type="button" disabled={busy} onClick={close}>閉じる</button></div></form>}
 <h3>売上の記録</h3>{!rows?.length?<p>この期間の記録はありません。</p>:<div className="mp-table"><table><caption className="sr-only">商品ごとの売上と返金</caption><thead><tr>{['日付','商品','種類','数量','金額','手数料','入金状態','注文番号','操作'].map(v=><th key={v} scope="col">{v}</th>)}</tr></thead><tbody>{rows.map(e=><tr key={e.id}><td>{e.date}</td><th scope="row"><DetailValue label={e.productName+'の記帳'} onClick={()=>showEntries(e.productName,[e],yen(e.amount))}>{e.productName}</DetailValue>{e.notes&&<small>{e.notes}</small>}{e.voidReason&&<small>取消：{e.voidReason}</small>}</th><td>{e.kind==='sale'?'売上':'返金'}</td><td>{e.quantity}</td><td><DetailValue label={e.productName+'の金額'} onClick={()=>showEntries(e.productName,[e],yen(e.amount))}>{yen(e.amount)}</DetailValue></td><td>{yen(e.fee)}</td><td>{e.kind==='refund'?(e.payment==='paid'?'返金済':'未返金'):(e.payment==='paid'?'入金済':'未入金')}</td><td>{e.reference||'—'}</td><td>{editable&&!e.voidReason&&<div className="commerce-actions"><button disabled={busy||dirty} onClick={()=>void save({action:'mark_payment',id:e.id,payment:e.payment==='paid'?'pending':'paid'})}>{e.payment==='pending'?(e.kind==='sale'?'入金済にする':'返金済にする'):'未処理に戻す'}</button>{e.kind==='sale'&&<button disabled={busy} onClick={()=>openSale(data?.products.find(p=>p.id===e.productId),e)}>返金</button>}<button disabled={busy||dirty} onClick={()=>{const reason=prompt('取消理由を入力してください。記録は履歴に残ります。');if(reason?.trim())void save({action:'void_entry',id:e.id,reason});}}>取消</button></div>}</td></tr>)}</tbody></table></div>}
 <details className="commerce-products" ref={productsList}><summary>商品一覧（{data?.products.length}件）</summary>{!data?.products.length?<p>「商品を追加」から商材を登録してください。</p>:<ul>{data.products.map(p=><li key={p.id}><div><strong>{p.name}</strong><small>{revenueModelNames[p.model]} / {yen(p.price)}{p.archived?' / 販売終了':''}</small></div>{editable&&<button disabled={busy} onClick={()=>openProduct(p)}>編集</button>}</li>)}</ul>}</details>
 <details><summary>集計と記録について</summary><p>税込の整数円、販売日と返金日を基準に集計します。未入金でも売上に含みます。APIやCSVの実績とは重複する可能性があるため合算しません。取消と商品名の変更前の記録は残ります。</p></details>
 </>}{detail.drawer}</section>;
}
