'use client';
import {useIdentity} from '../company/session';
import {ConnectionChart} from './data-visuals';
import {useEffect,useState} from 'react';
import {useBusiness,useBusinessFetch} from './business-context';
type Target={id:string;name:string};
type Connection={id:string;provider:string;label:string;enabled:number;targets:Target[];last_success:string|null;last_error:string|null};
const names:Record<string,string>={x:'X',threads:'Threads',instagram:'Instagram',youtube:'YouTube',utage:'UTAGE'};
export default function ConnectionsPanel({onOverview,onDirtyChange,channel,onAds}:{channel?:'sns'|'email';onAds?:()=>void;onOverview:()=>void;onDirtyChange?:(v:boolean)=>void}){
 const fetch=useBusinessFetch(),business=useBusiness(),user=useIdentity();
 const visible=(p:string)=>channel==='sns'?p!=='utage':channel==='email'?p==='utage':true;
 const [rows,setRows]=useState<Connection[]>([]),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[provider,setProvider]=useState(channel==='sns'?'x':'utage'),[label,setLabel]=useState(''),[token,setToken]=useState(''),[edit,setEdit]=useState(''),[targets,setTargets]=useState<Target[]>([]),[selected,setSelected]=useState<string[]>([]),[replace,setReplace]=useState(''),[replacementToken,setReplacementToken]=useState('');
 useEffect(()=>{const dirty=!!(label||token||replacementToken||edit);onDirtyChange?.(dirty);const guard=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',guard);return()=>{onDirtyChange?.(false);window.removeEventListener('beforeunload',guard);};},[label,token,replacementToken,edit,onDirtyChange]);
 async function load(){const r=await fetch('/api/marketing/connections',{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error);setRows(b.connections.filter((c:Connection)=>visible(c.provider)));setReady(b.ready);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function run(body:Record<string,unknown>,success?:string){if(busy)return null;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/marketing/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),b=await r.json();if(!r.ok)throw new Error(b.error);try{await load();}catch{setError('操作は完了しましたが、接続一覧を取得できませんでした。「一覧を更新」で確認してください。');}if(success)setNotice(success);return b;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 async function downloadData(){setBusy(true);setError('');try{const r=await fetch('/api/marketing/data-export');if(!r.ok){const b=await r.json();throw new Error(b.error);}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='astra-business-data-'+business.id+'-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('保存済み実績の控えを取得しました。認証キーは含まれません。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="native-connections">{error&&<p role="alert" className="cd-error">{error}</p>}{notice&&<p role="status">{notice}</p>}<details><summary>取得範囲と保存について</summary><p>SNSはアカウントの数字、UTAGEはファネルのページ実績を取得します。LINEやメルマガの配信別実績は対象外です。取得は手動です。取得に失敗しても保存済みの記録は残ります。</p>{user.role==='owner'&&<button disabled={busy} onClick={()=>void downloadData()}>保存済み実績をダウンロード</button>}</details>
 <div className="nc-grid"><section className="nc-box"><h3>接続を追加</h3><form onSubmit={async e=>{e.preventDefault();const b=await run({action:'create',provider,label,token},'接続を登録しました。');if(b){setToken('');setLabel('');}}}><fieldset disabled={busy||!ready}><label>取得先<select value={provider} onChange={e=>setProvider(e.target.value)}>{Object.entries(names).filter(([id])=>visible(id)).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label>表示名<input value={label} maxLength={100} required placeholder="公式アカウント、商品販売 など" onChange={e=>setLabel(e.target.value)}/></label><label>{provider==='utage'?'UTAGEのAPIキー':'読取権限のあるアクセストークン'}<input type="password" value={token} autoComplete="off" required onChange={e=>setToken(e.target.value)}/></label><button className="ao-primary" type="submit">接続を確認して登録</button></fieldset></form>{!ready&&<p>接続情報の保存を準備中です。</p>}<details><summary>取得できる数字・必要な権限</summary><p>Instagram：プロアカウントのフォロワー数・投稿数・表示回数・リーチ・プロフィール表示・反応数・反応したアカウント数。取得には <code>instagram_business_basic</code> と <code>instagram_business_manage_insights</code> が必要です。</p><p>UTAGE：ファネルのページ明細の表示・閲覧者・登録・購入・売上を保存。ページ間の重複を除いた人数は集計しません。X：フォロワー数。Threads：フォロワー数。YouTube：登録者数（取得元の丸めを含む）。</p><p>SNSへの投稿は行いません。Metaが返さない指標は未取得として扱い、0で補完しません。</p></details></section>
 <section className="nc-box"><h3>この事業の接続</h3><button disabled={busy} onClick={()=>{setError('');void load().catch(()=>setError('接続一覧を取得できませんでした。時間をおいて再試行してください。'));}}>一覧を更新</button>{!rows.length&&<p>接続がありません</p>}{rows.map(c=><article key={c.id} className="nc-account"><div className="cd-sectionhead"><h4>{c.label}<small> {names[c.provider]}</small></h4><span>{c.enabled?'取得可能':'停止中'}</span></div><p>最終取得：{c.last_success?new Date(c.last_success).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'まだ取得していません'}</p>{c.last_error&&<p className="cd-error">{c.last_error}</p>}{c.provider==='utage'&&<p>取得するファネル：{c.targets.map(t=>t.name).join('、')||'未選択'}</p>}<div className="ao-actions"><button disabled={busy||!c.enabled} onClick={()=>void run({action:'collect',id:c.id},'数字を取得しました。SNSの今日の記録は、明日から「昨日まで」のグラフに表示されます。')}>今すぐ取得</button>{c.provider==='utage'&&<button disabled={busy} onClick={async()=>{const b=await run({action:'funnels',id:c.id});if(b){setEdit(c.id);setTargets(b.funnels);setSelected(c.targets.map(t=>t.id));}}}>ファネルを選ぶ</button>}<button disabled={busy} onClick={()=>{setReplace(c.id);setReplacementToken('');}}>キーを更新</button><button disabled={busy} onClick={()=>void run({action:'toggle',id:c.id,enabled:!c.enabled},c.enabled?'収集を停止しました。記録は残っています。':'手動で取得できる状態に戻しました。')}>{c.enabled?'収集を停止':'取得を有効にする'}</button></div>{edit===c.id&&<form onSubmit={async e=>{e.preventDefault();if(await run({action:'targets',id:c.id,ids:selected},'取得対象を保存しました。'))setEdit('');}}><fieldset disabled={busy}><legend>取得するファネル（10件まで）</legend>{targets.map(t=><label className="nc-check" key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,t.id]:v.filter(id=>id!==t.id))}/>{t.name}</label>)}<button disabled={selected.length>10}>選択を保存</button><button type="button" onClick={()=>setEdit('')}>閉じる</button></fieldset></form>}{replace===c.id&&<form onSubmit={async e=>{e.preventDefault();if(await run({action:'replace',id:c.id,token:replacementToken},'接続キーを更新しました。')){setReplace('');setReplacementToken('');}}}><fieldset disabled={busy}><label>新しい接続キー<input type="password" autoComplete="off" value={replacementToken} onChange={e=>setReplacementToken(e.target.value)} required/></label><button disabled={busy}>更新</button><button type="button" onClick={()=>{setReplace('');setReplacementToken('');}}>閉じる</button></fieldset></form>}</article>)}</section></div><button onClick={onOverview}>全体の数字へ</button></section>;
}
