'use client';
import {DetailValue} from './data-detail';
import {NativeCharts} from './data-visuals';
import {DataChart} from '../components/data-charts';
import {useBusiness,useBusinessFetch,usePageAccess} from './business-context';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowLeft,RefreshCw,ChevronRight,Link2,BarChart3,Users,MousePointer2,Wallet,X} from 'lucide-react';
import {followersIn,sum,windowDates,yen,type Catalog,type ConnectedResult,type Links,type Page,type Day,type Account} from '@/lib/connected/model';
import './connected.css';
import RangePicker from './date-range';
import {initialRange,rememberRange,validRange} from '@/lib/date-range';
const names={pv:'ページ表示',uu:'閲覧者',registrations:'登録',sales:'購入',revenue:'UTAGE売上'};
type Metric=keyof typeof names;

export default function ConnectedDashboard({onAdvanced,onSettings}:{onAdvanced:()=>void;onSettings:()=>void}){
 const fetch=useBusinessFetch(),business=useBusiness(),canEdit=usePageAccess('overview',true);
 async function get<T>(url:string,signal?:AbortSignal):Promise<T>{const r=await fetch(url,{cache:'no-store',signal});const b=await r.json();if(!r.ok)throw new Error(b.error??'取得できませんでした。');return b;}
 const [range,setRange]=useState(initialRange),[groupId,setGroupId]=useState(''),[catalog,setCatalog]=useState<Catalog|null>(null),[result,setResult]=useState<ConnectedResult|null>(null),[links,setLinks]=useState<Links>({version:0,groups:{}}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[detailBusy,setDetailBusy]=useState(false),[refresh,setRefresh]=useState(0),[pageId,setPageId]=useState(''),[metric,setMetric]=useState<Metric>('registrations'),[drawer,setDrawer]=useState<Page|null>(null),[accountDetail,setAccountDetail]=useState<Account|null>(null),[editing,setEditing]=useState(false),[selectedAccounts,setSelectedAccounts]=useState<string[]>([]),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState('');
 const days=validRange(range)?Math.round((Date.parse(range.end)-Date.parse(range.start))/86400000)+1:0,dialog=useRef<HTMLDialogElement>(null),seq=useRef(0);
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');setCatalog(null);setResult(null);if(!validRange(range)){setBusy(false);return;}Promise.all([get<Catalog>(`/api/marketing/connected?action=catalog&${new URLSearchParams(range)}`,controller.signal),get<Links>('/api/marketing/connected?action=links',controller.signal)]).then(([c,l])=>{setCatalog(c);setLinks(l);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[range.start,range.end,refresh]);
 useEffect(()=>{const id=++seq.current,controller=new AbortController();setResult(null);setPageId('');setDrawer(null);setAccountDetail(null);setEditing(false);setSaveError('');if(!groupId||!catalog||!validRange(range)){setDetailBusy(false);return()=>controller.abort();}setDetailBusy(true);get<ConnectedResult>(`/api/marketing/connected?${new URLSearchParams({action:'utage',groupId,...range})}`,controller.signal).then(r=>{if(id===seq.current){setResult(r);setPageId([...r.pages].sort((a,b)=>(b.totals.pv??-1)-(a.totals.pv??-1))[0]?.id??'');}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted&&id===seq.current)setDetailBusy(false);});return()=>controller.abort();},[groupId,catalog,range.start,range.end]);
 useEffect(()=>{if(drawer||accountDetail)dialog.current?.showModal();else dialog.current?.close();},[drawer,accountDetail]);
 const group=catalog?.groups.find(g=>g.id===groupId),page=result?.pages.find(p=>p.id===pageId);
 const accounts=catalog?.accounts.filter(a=>!groupId||(links.groups[groupId]??[]).includes(a.id))??[];
 function choose(id:string){window.scrollTo({top:0,behavior:'auto'});setError('');setGroupId(id);setEditing(false);}
 async function saveLinks(){if(!canEdit)return;setSaving(true);setSaveError('');try{const r=await fetch('/api/marketing/connected?action=links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:crypto.randomUUID(),version:links.version,groupId,accountIds:selectedAccounts})});const b=await r.json();if(!r.ok){if(r.status===409)setLinks(await get<Links>('/api/marketing/connected?action=links'));throw new Error(b.error);}setLinks(b);setEditing(false);}catch(e){setSaveError((e as Error).message);}finally{setSaving(false);}}
 function edit(){if(!canEdit)return;setSelectedAccounts(links.groups[groupId]??[]);setEditing(true);setSaveError('');}
 return <section className="cd-root"><div className="cd-toolbar"><div className="cd-title">{groupId?<button className="cd-back" onClick={()=>choose('')}><ArrowLeft size={18}/>案件一覧</button>:<span className="cd-eyebrow">毎日の数字</span>}<h2>{group?.displayName??business.name}</h2><p>{groupId?'気になる数字を押すと、日別の実績を確認できます。':'ファネルを選んで、ページ閲覧から登録・購入までを確認。'}</p></div><div className="cd-period"><RangePicker value={range} onChange={r=>{setRange(r);rememberRange(r);setDrawer(null);setAccountDetail(null);}}/><button disabled={busy||detailBusy} onClick={()=>setRefresh(r=>r+1)}><RefreshCw size={14}/>数字を更新</button></div></div>
 {days>90&&<p className="cd-caption">保存済みの日次記録は選択期間で表示します。UTAGEのページ別直接取得は90日以内に絞ってください。</p>}<div className="cd-connection"><span><i/>この事業のSNS · UTAGE</span><span>{busy?'接続先を読み込み中':catalog?`取得確認 ${new Date(catalog.fetchedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}`:'接続を確認してください'}</span><button onClick={onSettings}>設定</button></div>
 {error&&<div className="cd-error" role="alert">{error}<button onClick={()=>setRefresh(v=>v+1)}>再取得</button></div>}{catalog?.errors.map(e=><p key={e} className="cd-error">{e}</p>)}
 {busy?<div className="cd-loading" role="status">実績を読み込んでいます…</div>:catalog&&<>
 <div className="dash-kpi-grid" aria-label="SNSの主要な数字">{accounts.map(a=>{const f=followersIn(a,range.start,range.end);return <article className="dash-kpi" key={a.id}><span><Users size={18}/>{a.displayName||a.handle}</span><strong><DetailValue label={(a.displayName||a.handle)+'のフォロワー'} onClick={()=>setAccountDetail(a)}>{yen(f.value)}</DetailValue></strong><small>{a.platform} / フォロワー / {f.date??'未取得'}</small><small className={f.change!==null&&f.change>0?'cd-positive':''}>{f.change===null?'比較記録なし':(f.change>0?'+':'')+yen(f.change)+'人'}（期間内の最初と最後）</small></article>;})}</div>
 <NativeCharts accounts={accounts} groups={catalog.groups.filter(g=>!groupId?g.status==='active':g.id===groupId)} start={range.start} end={range.end}/>
 {!groupId&&<><div className="cd-sectionhead"><h3>どのファネルを見ますか？</h3><span>この事業のUTAGEファネル</span></div><div className="cd-projects">{catalog.groups.filter(g=>g.status==='active').map(g=>{const series=g.series.filter(d=>d.date>=range.start&&d.date<=range.end),pv=sum(series.map(d=>d.pv)),reg=sum(series.map(d=>d.registrationCount));return <button className="cd-project" key={g.id} onClick={()=>choose(g.id)}><span className="cd-projecttop"><strong>{g.displayName}</strong><ArrowUpRight size={20}/></span><span className="cd-projectmetrics"><span><small>ページ表示</small><b>{yen(pv.value)}</b></span><span><small>登録件数</small><b>{yen(reg.value)}</b></span></span><small>{series.length}/{days}日分の記録 {pv.missing||reg.missing?'· 一部未取得':''} · {g.funnelIds.length}ファネル</small><span className="cd-projectlink">ページごとの内訳を見る<ChevronRight size={16}/></span></button>;})}</div>{!catalog.groups.some(g=>g.status==='active')&&<p className="cd-empty">取得中の案件がありません。「データ接続」からUTAGEと取得するファネルを登録してください。</p>}<p className="cd-caption">この一覧はAstraで日次取得したページ別件数の合計です。同じ人の重複を除いた人数ではありません。</p>{!catalog.globalEnabled&&catalog.groups.length>0&&<p className="cd-error">UTAGEの日次収集が停止中です。保存済みの数字と、案件内で取得する現在の数字は更新時点が異なります。</p>}{catalog.groups.some(g=>g.status!=='active')&&<details className="cd-muted-details"><summary>収集を停止している案件</summary>{catalog.groups.filter(g=>g.status!=='active').map(g=><button key={g.id} onClick={()=>choose(g.id)}>{g.displayName}の保存済み設定を見る</button>)}</details>}</>}
 {groupId&&<>{detailBusy?<div className="cd-loading" role="status">UTAGEからページ別の実績を取得しています…</div>:result&&<>{result.failures.length>0&&<div role="alert" className="cd-error">{result.failures.length}ファネルの取得に失敗しました。保存済みの範囲を表示しています。最新の取得結果ではありません。<button onClick={()=>setRefresh(v=>v+1)}>再取得</button></div>}<div className="cd-sectionhead"><div><h3>ページの成果</h3><span>{result.cached?'保存済み明細（取得失敗時の表示）':'UTAGEから取得して保存'} · 発生日で集計</span></div><label>表示するページ<select value={pageId} onChange={e=>setPageId(e.target.value)}>{result.pages.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label></div>{page?<><div className="cd-flow"><MetricCard icon={<MousePointer2 size={18}/>} title="ページ表示" value={page.totals.pv} unit="回" note="このページが表示された回数" onClick={()=>{setMetric('pv');setDrawer(page);}}/><ChevronRight className="cd-arrow"/><MetricCard icon={<Users size={18}/>} title="登録" value={page.totals.registrations} unit="件" note="このページ経由の登録" onClick={()=>{setMetric('registrations');setDrawer(page);}}/><ChevronRight className="cd-arrow"/><MetricCard icon={<Wallet size={18}/>} title="UTAGE売上" emptyLabel={page.payment?'未取得':'対象外'} value={page.payment?page.totals.revenue:null} unit="円" note={page.payment?`購入 ${yen(page.totals.sales)}件`:'決済ページではありません'} onClick={()=>{setMetric('revenue');setDrawer(page);}}/></div><p className="cd-caption">同じ人が順番に進んだことを示す図ではありません。面談実施・外部決済・入金は未接続です。</p><div className="cd-chartbox"><div className="cd-sectionhead"><h3>{page.name}の日別推移</h3><div className="cd-segment">{(['pv','registrations','revenue'] as Metric[]).map(k=><button key={k} aria-pressed={metric===k} onClick={()=>setMetric(k)}>{names[k]}</button>)}</div></div>{metric==='revenue'&&!page.payment?<p className="cd-empty">このページは決済対象外です。</p>:<Bars daily={page.daily} metric={metric} onSelect={()=>setDrawer(page)}/>}<button className="cd-textlink" onClick={()=>setDrawer(page)}>日別の数字を開く<ArrowUpRight size={15}/></button></div></>:<p className="cd-empty">この期間のページ情報を取得できませんでした。</p>}
 <div className="cd-sectionhead"><h3>どのページで反応があるか</h3><span>行を押して日別明細へ</span></div><div className="cd-table"><table><thead><tr><th>ページ</th><th>表示回数</th><th>閲覧者</th><th>登録</th><th>購入</th><th>UTAGE売上</th></tr></thead><tbody>{result.pages.map(p=><tr key={p.id}><th><button onClick={()=>{setPageId(p.id);setDrawer(p);}}>{p.name}<ArrowUpRight size={14}/></button><small>{p.step}</small></th><td><DetailValue label={p.name+'の'+names.pv} onClick={()=>{setMetric('pv');setDrawer(p);}}>{yen(p.totals.pv)}</DetailValue></td><td><DetailValue label={p.name+'の'+names.uu} onClick={()=>{setMetric('uu');setDrawer(p);}}>{yen(p.totals.uu)}</DetailValue></td><td><DetailValue label={p.name+'の'+names.registrations} onClick={()=>{setMetric('registrations');setDrawer(p);}}>{yen(p.totals.registrations)}</DetailValue></td><td>{p.payment?<DetailValue label={p.name+'の'+names.sales} onClick={()=>{setMetric('sales');setDrawer(p);}}>{yen(p.totals.sales)}</DetailValue>:'対象外'}</td><td>{p.payment?<DetailValue label={p.name+'の'+names.revenue} onClick={()=>{setMetric('revenue');setDrawer(p);}}>{yen(p.totals.revenue)+'円'}</DetailValue>:'対象外'}</td></tr>)}</tbody></table></div><p className="cd-caption">閲覧者はUTAGEのページ単位の集計値です。複数ページの閲覧者数は合算しません。登録先がLINEかメールかは、この集計APIだけでは確定できません。</p></>}
 </>}
 <div className="cd-sectionhead"><div><h3>{groupId?'この案件のSNS':'SNSアカウント'}</h3><span>フォロワーの増減と日別推移</span></div>{groupId&&<button disabled={!canEdit} onClick={edit}><Link2 size={15}/>アカウントを選ぶ</button>}</div>
 {editing&&<div className="cd-linkbox"><h4>この案件に関係するアカウントを選択</h4><p>対応付けはAstraに保存します。売上をSNSへ割り当てる設定ではありません。</p><fieldset disabled={saving}>{catalog.accounts.map(a=><label key={a.id}><input type="checkbox" checked={selectedAccounts.includes(a.id)} onChange={e=>setSelectedAccounts(v=>e.target.checked?[...v,a.id]:v.filter(id=>id!==a.id))}/>{a.displayName||a.handle}<small>{a.platform} / @{a.handle}</small></label>)}<button className="cd-primary" onClick={()=>void saveLinks()}>対応付けを保存</button><button onClick={()=>setEditing(false)}>閉じる</button></fieldset>{saveError&&<p role="alert">{saveError}</p>}</div>}
 {accounts.length?<div className="cd-accounts">{accounts.map(a=>{const f=followersIn(a,range.start,range.end),latest=a.series.filter(d=>d.date>=range.start&&d.date<=range.end).at(-1);return <button key={a.id} className="cd-account" onClick={()=>setAccountDetail(a)}><span className="cd-accounthead"><span className="cd-platform">{a.platform==='threads'?'Threads':a.platform==='instagram'?'Instagram':a.platform.toUpperCase()}</span><ArrowUpRight size={15}/></span><strong>{a.displayName||a.handle}</strong><small>@{a.handle}</small><span className="cd-accountnumber">{yen(f.value)}<small>フォロワー</small></span><span className={f.change!==null&&f.change>0?'cd-positive':''}>{f.change===null?'比較できる記録なし':`${f.change>0?'+':''}${yen(f.change)}`}<small> 最初と最後の取得値の差</small></span>{a.platform==='instagram'&&<small>リーチ {yen(latest?.reach??null)} · 反応 {yen(latest?.interactions??null)}</small>}<small>最新記録 {f.date??'なし'} {a.status!=='active'?'· 接続状態を要確認':''}</small></button>;})}</div>:<div className="cd-empty">{groupId?'この案件とSNSの対応付けがまだありません。':'この期間のSNSデータはありません。'}{groupId&&<button disabled={!canEdit} onClick={edit}>関連するアカウントを選ぶ</button>}</div>}
 <div className="cd-bottom"><div><h3>さらに細かく調べたいとき</h3><p>媒体・訴求の掛け合わせや、手入力した広告費・実績を確認できます。</p></div><button onClick={onAdvanced}><BarChart3 size={17}/>手入力実績の詳細分析<ChevronRight size={15}/></button></div>
 </>}
 <dialog ref={dialog} className="cd-drawer" onCancel={()=>{setDrawer(null);setAccountDetail(null);}} aria-labelledby="cd-detail-title"><div className="cd-drawerhead"><div><span className="cd-eyebrow">数字の内訳</span><h3 id="cd-detail-title">{drawer?.name??accountDetail?.displayName??accountDetail?.handle}</h3></div><button aria-label="明細を閉じる" onClick={()=>{setDrawer(null);setAccountDetail(null);}}><X size={20}/></button></div><p>{range.start}〜{range.end}</p>{drawer&&<><p>出典：UTAGE / ファネル {drawer.funnelId} / ページ {drawer.id.split(':').at(-1)}<br/>取得日時 {result?.collectedAt?new Date(result.collectedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'不明'}</p><Bars daily={drawer.daily} metric={metric}/><div className="cd-table"><table><thead><tr><th>日付</th><th>表示</th><th>閲覧者</th><th>登録</th><th>購入</th><th>売上</th></tr></thead><tbody>{drawer.daily.map(d=><tr key={d.date}><th>{d.date}</th><td>{yen(d.pv)}</td><td>{yen(d.uu)}</td><td>{yen(d.registrations)}</td><td>{drawer.payment?yen(d.sales):'対象外'}</td><td>{drawer.payment?yen(d.revenue):'対象外'}</td></tr>)}</tbody></table></div><p>日別の閲覧者数を足しても、期間内の重複を除いた人数にはなりません。</p></>}{accountDetail&&<><p>出典：各SNSの公式API / {accountDetail.platform} / @{accountDetail.handle}</p><div className="cd-table"><table><thead><tr><th>取得日</th><th>フォロワー</th><th>表示回数</th>{accountDetail.platform==='instagram'&&<><th>リーチ</th><th>プロフィール表示</th><th>反応</th><th>反応アカウント</th><th>投稿数</th></>}</tr></thead><tbody>{accountDetail.series.filter(d=>d.date>=range.start&&d.date<=range.end).map(d=><tr key={d.date}><th>{d.date}</th><td>{yen(d.followers)}</td><td>{yen(d.impressions)}</td>{accountDetail.platform==='instagram'&&<><td>{yen(d.reach??null)}</td><td>{yen(d.profileViews??null)}</td><td>{yen(d.interactions??null)}</td><td>{yen(d.engagedAccounts??null)}</td><td>{yen(d.mediaCount??null)}</td></>}</tr>)}</tbody></table></div><p>Instagramの数字はプロアカウントが公式APIで開示した範囲です。Metaが返さない指標は0に置き換えません。</p></>}</dialog>
 </section>;
}
function MetricCard({icon,title,value,unit,note,onClick,emptyLabel='未取得'}:{icon:React.ReactNode;title:string;value:number|null;unit:string;note:string;onClick:()=>void;emptyLabel?:string}){return <button className="cd-metric" onClick={onClick}><span>{icon}{title}<ArrowUpRight size={15}/></span><strong>{value===null?emptyLabel:yen(value)}{value!==null&&<small>{unit}</small>}</strong><small>{note}</small></button>;}
function Bars({daily,metric,onSelect}:{daily:Day[];metric:Metric;onSelect?:(date:string)=>void}){return <DataChart onSelect={onSelect} title={names[metric]+'の日別推移'} kind="line" tone={metric==='revenue'?'green':'blue'} unit={metric==='revenue'?'円':metric==='pv'?'回':'件'} points={daily.map(d=>({id:d.date,date:d.date,label:d.date,value:d[metric]}))}/>;}
