'use client';
import {useEffect,useRef,useState} from 'react';
import {DataChart} from '../components/data-charts';
import {creativeRanking,creativeImageUrl} from '@/lib/dashboard-model';
import {money,type Entity,type Report} from '@/lib/ads/model';
type Ranked=ReturnType<typeof creativeRanking>[number];
function Preview({row,large=false}:{row:Ranked;large?:boolean}){const src=creativeImageUrl(large?(row.entity?.creative?.imageUrl??row.entity?.creative?.thumbnailUrl):row.entity?.creative?.thumbnailUrl??row.entity?.creative?.imageUrl);const [failed,setFailed]=useState(false);return src&&!failed?<img src={src} alt={row.entity?.creative?.videoId?'動画のサムネイル':'広告素材'} className={large?'dash-creative-preview':'dash-creative-image'} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<span className="dash-creative-image dash-creative-placeholder">素材未取得</span>;}
export default function CreativeRanking({entities,reports,action,currency,actionName}:{entities:Entity[];reports:Report[];action:string;currency:string;actionName:string}){
 const ranked=creativeRanking(entities,reports,action),[selected,setSelected]=useState<Ranked|null>(null),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{setSelected(null);},[entities,reports,action]);useEffect(()=>{if(selected&&!dialog.current?.open)dialog.current?.showModal();if(!selected&&dialog.current?.open)dialog.current?.close();},[selected]);
 return <section className="dc-chart"><h4>好調なCR TOP5</h4><p className="dc-note">{action?'成果5件以上の広告をCPAが低い順に表示 / '+actionName:'成果の種類を選ぶと比較できます'}</p>{ranked.length?<ol className="dash-creative-list">{ranked.map((row,i)=><li key={row.id}><button className="dash-creative-row" onClick={()=>setSelected(row)}><span>{i+1}</span><Preview row={row}/><span className="dash-creative-name"><strong>{row.name}</strong><small>Meta / 広告費 {money(row.spend,currency)}</small></span><span className="dash-creative-result"><strong>CPA {money(row.cpa,currency)}</strong><small>成果 {row.results}件</small></span></button></li>)}</ol>:<p className="dc-empty">{action?'比較条件を満たす広告がまだありません。':'成果の種類が未選択です。'}</p>}<details className="dc-note"><summary>順位の条件</summary><p>同じアカウント・期間・成果定義での相対比較です。成果5件は表示条件で、統計的な確実性や採算を保証しません。欠測・費用0の広告は順位から外します。素材は最終同期時の代表プレビューです。期間中の差し替え履歴や、動的広告の素材ごとの効果は識別できません。</p></details><dialog ref={dialog} className="dash-creative-dialog" onCancel={()=>setSelected(null)} aria-label="広告素材と実績の詳細">{selected&&<><div className="mp-toolbar"><h3>{selected.name}</h3><button onClick={()=>setSelected(null)}>閉じる</button></div><Preview key={selected.id} row={selected} large/><p>Meta / 広告ID {selected.id} / {actionName}</p><div className="dash-kpi-grid"><article className="dash-kpi"><span>広告費</span><strong>{money(selected.spend,currency)}</strong></article><article className="dash-kpi"><span>成果</span><strong>{selected.results}件</strong></article><article className="dash-kpi"><span>CPA</span><strong>{money(selected.cpa,currency)}</strong></article></div><DataChart title="広告費の日別推移" kind="line" unit={currency} points={selected.rows.map(r=>({id:r.date,date:r.date,label:r.date,value:r.spend}))}/><details><summary>保存済みの明細</summary><div className="mp-table"><table><thead><tr><th>日付</th><th>広告費</th><th>表示</th><th>クリック</th><th>成果</th></tr></thead><tbody>{selected.rows.map(r=><tr key={r.date}><td>{r.date}</td><td>{r.spend??'未取得'}</td><td>{r.impressions??'未取得'}</td><td>{r.clicks??'未取得'}</td><td>{r.actions[action]??0}</td></tr>)}</tbody></table></div></details></>}</dialog></section>;
}
