'use client';
import {useEffect,useId,useRef,useState,isValidElement,type ReactNode} from 'react';
import './data-detail.css';
export type DataDetail={title:string;value?:string;context?:string[];columns:string[];rows:(string|number|null)[][];note?:string;loading?:boolean;error?:string;rowAction?:{label:string;onSelect:(index:number)=>void}};
function nodeText(node:ReactNode):string{if(typeof node==='string'||typeof node==='number')return String(node);if(Array.isArray(node))return node.map(nodeText).join('');if(isValidElement<{children?:ReactNode}>(node))return nodeText(node.props.children);return '';}
export function DetailValue({children,label,onClick}:{children:ReactNode;label:string;onClick:()=>void}){return <button type="button" className="data-detail-value" aria-label={label+' '+nodeText(children)+'の詳細を表示'} aria-haspopup="dialog" onClick={onClick}>{children}<span aria-hidden="true" className="data-detail-arrow">↗</span></button>;}
export function DataDetailDrawer({data,onClose}:{data:DataDetail|null;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),returnTo=useRef<HTMLElement|null>(null),id=useId(),[limit,setLimit]=useState(100);
 const active=!!data;
 useEffect(()=>{if(!active)return;setLimit(100);returnTo.current=document.activeElement&&'focus' in document.activeElement?document.activeElement as HTMLElement:null;dialog.current?.showModal();return()=>{dialog.current?.close();if(returnTo.current?.isConnected)returnTo.current.focus({preventScroll:true});};},[active]);
 if(!data)return null;
 return <dialog ref={dialog} className="data-detail-drawer" aria-labelledby={id} onCancel={e=>{e.preventDefault();onClose();}}><header><div><small>数字の詳細</small><h2 id={id}>{data.title}</h2></div><button type="button" aria-label="詳細を閉じる" onClick={onClose}>閉じる</button></header>{data.value&&<strong className="data-detail-total">{data.value}</strong>}{data.context?.map((text,i)=><p className="data-detail-context" key={i}>{text}</p>)}{data.loading?<p role="status">明細を読み込み中…</p>:data.error?<p role="alert">{data.error}</p>:<>{data.rows.length?<><p className="data-detail-count">{data.rows.length}記録{data.rows.length>limit?' / '+limit+'記録を表示中':''}</p><div className="data-detail-table"><table><caption className="sr-only">{data.title}の明細</caption><thead><tr>{data.columns.map((label,i)=><th scope="col" key={i}>{label}</th>)}{data.rowAction&&<th scope="col">操作</th>}</tr></thead><tbody>{data.rows.slice(0,limit).map((row,i)=><tr key={i}>{row.map((value,j)=><td key={j}>{value===null?'未取得':typeof value==='number'?value.toLocaleString('ja-JP',{maximumFractionDigits:2}):value||'—'}</td>)}{data.rowAction&&<td><button type="button" onClick={()=>data.rowAction!.onSelect(i)}>{data.rowAction.label}</button></td>}</tr>)}</tbody></table></div>{data.rows.length>limit&&<button type="button" onClick={()=>setLimit(v=>v+100)}>次の100記録を表示</button>}</>:<p>この条件の記録はありません。</p>}</>}{data.note&&<p className="data-detail-note">{data.note}</p>}</dialog>;
}
export function useDataDetail(){const [data,setData]=useState<DataDetail|null>(null);return {show:setData,drawer:<DataDetailDrawer data={data} onClose={()=>setData(null)}/>};}
