'use client';
import {useEffect,useState} from 'react';
import {factDetail} from '@/lib/data-detail';
import {useDataDetail} from './data-detail';
import {DataChart, SelectableChart} from '../components/data-charts';
import {countCategories} from '@/lib/chart-model';
import type {ChartSeries} from '@/lib/chart-model';
import {group, measures, total, type Fact, type Axis, type Measure} from '@/lib/analytics/model';
import {goalProgress, campaignPhase, phaseNames} from '@/lib/marketing-business/planning';
import {metricNames, metricUnit, type BusinessData, type BusinessGoal, type Campaign, type Observation} from '@/lib/marketing-business/types';
import type {Account, SourceGroup} from '@/lib/connected/model';
import type {PostizDraft} from '@/lib/postiz/types';

export function CountChart({title, values, names, note,columns=['記録','区分'],records}: {title: string; values: string[]; names?: Record<string, string>; note?: string;columns?:string[];records?:(string|number|null)[][]}) {
 const detail=useDataDetail(),signature=JSON.stringify([values,records]);useEffect(()=>{detail.show(null);},[signature]);
 return <><DataChart title={title} points={countCategories(values, v => v, names)} note={note} onSelect={id=>detail.show({title:title+' / '+(names?.[id]??id),value:values.filter(v=>(v||'未登録')===id).length+'件',columns,rows:values.flatMap((v,i)=>(v||'未登録')===id?[records?.[i]??[i+1,names?.[v]??v]]:[]),note})}/>{detail.drawer}</>;
}
export function FactCharts({rows, axis = 'funnelId', label, title = '実績', onSelect,onDaySelect,annotations}: {annotations?:{date:string;label:string}[];rows: Fact[]; axis?: Axis; label?: (id: string) => string; title?: string; onSelect?: (id: string,metric?:Measure) => void;onDaySelect?:(date:string,metric:Measure)=>void}) {
  const detail=useDataDetail();useEffect(()=>{detail.show(null);},[rows,axis]);function show(title:string,records:Fact[],metric:Measure){const d=factDetail(records,metric);detail.show({title,value:d.sum.value===null?'未取得':d.sum.value.toLocaleString('ja-JP'),columns:d.columns,rows:d.rows,note:d.sum.missing?d.sum.missing+'記録が未取得。表示値は取得済みの小計です。':'選んだ条件の記録です。'});}
  function series(by: Axis): ChartSeries[] {
    return (Object.keys(measures) as Measure[]).map(metric => ({id: metric, label: measures[metric], unit: ['sales', 'registrations'].includes(metric) ? '件' : '円', points: group(rows, by).map(([id, records]) => {
      const value = total(records, metric);
      return {id, label: by === 'date' ? id : label?.(id) ?? (by === 'funnelId' ? records[0].funnel.name : id), date: by === 'date' ? id : undefined, value: value.value, partial: value.missing > 0};
    })}));
  }
  return <><div className="dc-layout"><SelectableChart title={`${title}の日別推移`} series={series('date')} annotations={annotations} onSelect={(date,key)=>onDaySelect?onDaySelect(date,key as Measure):show(date+' / '+measures[key as Measure],rows.filter(r=>r.date===date),key as Measure)} kind="line" note="選択した条件の記録だけを集計。未取得は0に置き換えません。"/><SelectableChart title={`${title}の比較`} series={series(axis)} onSelect={(id,key)=>onSelect?onSelect(id,key as Measure):show((label?.(id)??id)+' / '+measures[key as Measure],rows.filter(r=>(r[axis]||'未分類')===id),key as Measure)} note="出典・定義が異なる記録を含む場合があります。明細と併せて確認してください。"/></div>{detail.drawer}</>;
}
export function CampaignCharts({campaigns, note = '現在の施策の状況です。作業完了と成果の達成は別に扱います。'}: {campaigns: Campaign[]; note?: string}) {
  return <div className="dc-layout"><CountChart title="施策の作業状況" values={campaigns.map(campaignPhase)} names={phaseNames} columns={['施策','担当','開始','終了予定','作業状況']} records={campaigns.map(c=>[c.title,c.assignee??'未登録',c.start,c.end,phaseNames[campaignPhase(c)]])} note={note}/><CountChart title="施策の結果判断" values={campaigns.map(c => c.result)} columns={['施策','担当','終了予定','判断']} records={campaigns.map(c=>[c.title,c.assignee??'未登録',c.end,({pending:'判断保留',continue:'継続',change:'変更',stop:'停止'})[c.result]])} names={{pending:'判断保留',continue:'継続',change:'変更',stop:'停止'}} note={note}/></div>;
}
export function GoalChart({goals, observation}: {goals: BusinessGoal[]; observation?: Observation}) {
  const detail=useDataDetail();useEffect(()=>{detail.show(null);},[goals,observation]);return <><DataChart onSelect={id=>{const g=goals.find(g=>g.id===id);if(!g)return;const p=goalProgress(g,observation);detail.show({title:g.title,value:p.value===null?'未判定':p.value+'%',columns:['項目','値'],rows:[['指標',metricNames[g.metric]],['基準',g.baseline],['目標',g.target],['現在',p.current],['期限',g.deadline],['担当',g.owner],['観測',observation?.label??'なし'],['観測期間',observation?observation.start+'〜'+observation.end:'なし']],note:p.reason??'同じ条件の観測と基準から、目標に向けた改善率を計算しています。'});}} title="目標ごとの改善進捗" unit="%" maximum={100} note="100%が目標。比較条件を確認した観測だけを使います。未判定は棒を表示しません。" points={goals.map(g => {const p = goalProgress(g, observation); return {id: g.id, label: g.title, value: p.value, note: p.reason ?? `目標 ${g.target.toLocaleString('ja-JP')}${metricUnit(g.metric)}`};})}/>{detail.drawer}</>;
}
export function ObservationChart({rows, selected}: {rows: Observation[]; selected?: string}) {
  const detail=useDataDetail();const [id, setId] = useState('');
  const row = rows.find(o => o.id === (selected ?? id)) ?? rows.at(-1);
  useEffect(()=>{detail.show(null);},[rows,selected,id]);
 const show=(metric:string,label:string)=>{if(!row)return;detail.show({title:row.label+' / '+label,context:[row.start+'〜'+row.end],columns:['項目','保存値'],rows:Object.entries(row).filter(([k])=>!['id','comparability'].includes(k)).map(([k,v])=>[({label:'観測',start:'開始日',end:'終了日',days:'観測日数',source:'出典',collectedAt:'取得日',visitors:'ページ訪問者',registrations:'登録者',bookings:'予約者',meetings:'商談者',conversions:'成約者',adSpend:'広告費',revenue:'売上',grossProfit:'粗利'} as Record<string,string>)[k]??k,typeof v==='object'?JSON.stringify(v):v as string|number|null]),note:'観測に保存された集計値です。個人別の記録はこの観測に含まれていません。'});};
 const fields = {visitors:'ページ訪問者',registrations:'登録者',bookings:'予約者',meetings:'商談者',conversions:'成約者'} as const;
  return <div>{selected === undefined && <label>グラフで見る観測<select value={row?.id ?? ''} onChange={e => setId(e.target.value)}>{rows.map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select></label>}<div className="dc-layout"><DataChart onSelect={key=>show(key,fields[key as keyof typeof fields])} title="観測した段階別の人数" unit="人" points={row ? Object.entries(fields).map(([key, label]) => ({id:key,label,value:row[key as keyof typeof fields]})) : []} note={row ? `${row.label} / ${row.start}〜${row.end} / ${row.days}日観測。別の集団は合算しません。` : undefined}/><SelectableChart onSelect={(_,key)=>show(key,({revenue:'売上',adSpend:'広告費',grossProfit:'粗利'})[key as 'revenue'|'adSpend'|'grossProfit'])} title="観測した金額" series={(['revenue','adSpend','grossProfit'] as const).map(key => ({id:key,label:({revenue:'売上',adSpend:'広告費',grossProfit:'粗利'})[key],unit:'円',points:row ? [{id:row.id,label:row.label,value:row[key],note:row.source || '出典未登録'}] : []}))}/></div>{detail.drawer}</div>;
}
export function BusinessCharts({data, section, observation}: {data: BusinessData; section?: string; observation?: string}) {
  const detail=useDataDetail();useEffect(()=>{detail.show(null);},[data,section,observation]);
 if (section === 'observations') return <ObservationChart rows={data.observations} selected={observation}/>;
  if (section === 'campaigns') return <CampaignCharts campaigns={data.campaigns}/>;
  if (section === 'funnels' || !section) return <><div className="dc-layout"><DataChart onSelect={id=>detail.show({title:(data.projects??[]).find(p=>p.id===id)?.name??'案件',columns:['ファネル','流入区分','段階数'],rows:(data.funnels??[]).filter(f=>f.projectId===id).map(f=>[f.name,f.source,f.stages.length])})} title="案件ごとのファネル登録数" points={(data.projects ?? []).map(p => ({id:p.id,label:p.name,value:(data.funnels ?? []).filter(f => f.projectId === p.id).length}))} note="登録された構成の件数です。実績・成約数ではありません。"/><DataChart onSelect={id=>{const f=data.funnels?.find(f=>f.id===id);if(f)detail.show({title:f.name+'の段階',columns:['段階','次の段階'],rows:f.stages.map((stage,i)=>[stage.name,(f.connections??f.stages.slice(1).map((v,i)=>({from:f.stages[i].id,to:v.id}))).filter(c=>c.from===stage.id).map(c=>f.stages.find(s=>s.id===c.to)?.name??c.to).join(' / ')])});}} title="ファネルの段階数" points={(data.funnels ?? []).map(f => ({id:f.id,label:f.name,value:f.stages.length}))} note="分岐・合流を含む登録済みの段階数です。"/></div>{detail.drawer}</>;
  return <div className="dc-layout"><GoalChart goals={data.goals.filter(g=>!g.period)} observation={data.observations.find(o => o.id === observation) ?? data.observations.at(-1)}/><CountChart title="設定した目標の指標" values={data.goals.map(g => g.metric)} names={metricNames} columns={['目標','指標','基準','目標値','担当','期限']} records={data.goals.map(g=>[g.title,metricNames[g.metric],g.baseline,g.target,g.owner,g.deadline])}/></div>;
}
export function DraftCharts({drafts}: {drafts: PostizDraft[]}) {
  return <div className="dc-layout"><CountChart title="下書きの確認状況" values={drafts.map(d => d.reviewState ?? 'editing')} columns={['下書き','投稿先','本文','予定日']} records={drafts.map(d=>[d.title??'無題',d.platform??'未登録',d.content??'',d.scheduleAt??'未設定'])} names={{editing:'編集中',pending:'確認待ち',changes:'差し戻し',rejected:'却下'}} note="画面に読み込んだ下書きの状況です。公開済みの投稿数ではありません。"/><CountChart title="下書きの投稿先" values={drafts.map(d => d.platform ?? '未登録')} columns={['下書き','投稿先','本文','予定日']} records={drafts.map(d=>[d.title??'無題',d.platform??'未登録',d.content??'',d.scheduleAt??'未設定'])} names={{x:'X',threads:'Threads',instagram:'Instagram',youtube:'YouTube'}}/></div>;
}
export function ConnectionChart({connections}: {connections: {enabled: number | boolean; last_success: string | null; last_error: string | null;label?:string;name?:string;provider?:string;id?:string}[]}) {
  return <CountChart title="データ接続の取得状況" columns={['接続','媒体','最終取得','取得エラー']} records={connections.map(c=>[c.label??c.name??c.id??'接続',c.provider??'未登録',c.last_success,c.last_error])} values={connections.map(c => !c.enabled ? '停止中' : c.last_error ? '取得エラー' : c.last_success ? '取得記録あり' : 'まだ未取得')} note="保存された最終取得の状態です。最新の疎通を保証するものではありません。"/>;
}
export function NativeCharts({accounts, groups, start, end}: {accounts: Account[]; groups: SourceGroup[]; start: string; end: string}) {
  const detail=useDataDetail();useEffect(()=>{detail.show(null);},[accounts,groups,start,end]);const open=(date:string,series:string)=>{const [kind,id]=JSON.parse(series);const account=kind==='account'?accounts.find(a=>a.id===id):undefined;const group=kind==='group'?groups.find(g=>g.id===id):undefined;if(account){const day=account.series.find(d=>d.date===date);if(day)detail.show({title:(account.displayName||account.handle)+' / '+date,context:[account.platform+' / @'+account.handle],columns:['指標','取得値'],rows:[['フォロワー',day.followers],['表示',day.impressions],['リーチ',day.reach??null],['プロフィール表示',day.profileViews??null],['反応',day.interactions??null],['反応したアカウント',day.engagedAccounts??null]],note:'取得日の保存値。日別フォロワーやリーチは合算しません。'});}else if(group){const day=group.series.find(d=>d.date===date);if(day)detail.show({title:group.displayName+' / '+date,columns:['指標','取得値'],rows:[['ページ表示',day.pv],['登録',day.registrationCount]],note:'UTAGE日次取得の保存値。ページ間の個人の重複は除いていません。'});}};
 const instagram=accounts.filter(a=>a.platform==='instagram'),instagramNames={impressions:'表示回数',reach:'リーチ',profileViews:'プロフィール表示',interactions:'反応数',engagedAccounts:'反応したアカウント'} as const;
  return <><div className="dc-layout"><SelectableChart onSelect={open} title="SNSフォロワーの推移" kind="line" series={accounts.map(a => ({id:JSON.stringify(['account',a.id,'followers']),label:a.displayName || a.handle,unit:'人',points:a.series.filter(d => d.date >= start && d.date <= end).map(d => ({id:d.date,date:d.date,label:d.date,value:d.followers}))}))} note="各アカウントの取得日の値です。日別の値やアカウント間の人数は合算しません。"/>{instagram.length>0&&<SelectableChart onSelect={open} title="Instagramの反応" kind="line" series={instagram.flatMap(a=>(Object.keys(instagramNames) as (keyof typeof instagramNames)[]).map(key=>({id:JSON.stringify(['account',a.id,key]),label:`${a.displayName||a.handle} / ${instagramNames[key]}`,unit:key==='reach'||key==='engagedAccounts'?'人':'回',points:a.series.filter(d=>d.date>=start&&d.date<=end).map(d=>({id:d.date,date:d.date,label:d.date,value:d[key]??null}))})))} note="Instagram公式APIが取得時点に返した値です。未取得は0に置き換えません。"/>}<SelectableChart onSelect={open} title="UTAGEの日別記録" kind="line" series={groups.flatMap(g => (['pv','registrationCount'] as const).map(key => ({id:JSON.stringify(['group',g.id,key]),label:`${g.displayName} / ${key === 'pv' ? 'ページ表示' : '登録'}`,unit:key === 'pv' ? '回' : '件',points:g.series.filter(d => d.date >= start && d.date <= end).map(d => ({id:d.date,date:d.date,label:d.date,value:d[key]}))})))} note="保存された日次記録。ページをまたぐ個人の重複排除はしていません。"/></div>{detail.drawer}</>;
}
