'use client';
import {CampaignCharts} from './data-visuals';
import {useEffect,useRef,useState} from 'react';
import {useBusiness,useBusinessFetch} from './business-context';
import {useIdentity} from '../company/session';
import {can} from '@/lib/access';
import {phaseNames,campaignPhase,overdue,type Phase} from '@/lib/marketing-business/planning';
import type {Campaign} from '@/lib/marketing-business/types';
type Data={version:number;goals:{id:string;title:string}[];campaigns:Campaign[]};
const decisions={pending:'判断保留',continue:'継続',change:'変更',stop:'停止'};
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});
export default function ExecutionPanel({goalId,onOkr,onSettings,onDirtyChange}:{goalId:string;onOkr:()=>void;onSettings:()=>void;onDirtyChange:(dirty:boolean)=>void}){
 const detailHeading=useRef<HTMLHeadingElement>(null);
 const fetch=useBusinessFetch(),business=useBusiness(),user=useIdentity(),editable=can(user,business.id,'work',true)||can(user,business.id,'business',true);
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('board'),[filter,setFilter]=useState(goalId),[phase,setPhase]=useState('all'),[draft,setDraft]=useState<Campaign|null>(null),[dirty,setDirty]=useState(false),[creating,setCreating]=useState(false);
 useEffect(()=>{if(draft){detailHeading.current?.focus();detailHeading.current?.scrollIntoView({block:'nearest'});}},[draft?.id]);
 async function load(){setError('');const r=await fetch('/api/marketing/plan?view=work',{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error);setData(b.data);return b.data as Data;}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[fetch]);
 useEffect(()=>{onDirtyChange(dirty);const warn=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>{onDirtyChange(false);window.removeEventListener('beforeunload',warn);};},[dirty,onDirtyChange]);
 const campaigns=data?.campaigns.filter(c=>(!filter||c.goalId===filter)&&(phase==='all'||campaignPhase(c)===phase))??[];
 function open(c:Campaign,isNew=false){if(dirty&&!confirm('未保存の変更があります。破棄して別の施策を開きますか？'))return;setDraft(c);setCreating(isNew);setDirty(false);setNotice('');setError('');}
 function patch(p:Partial<Campaign>){setDraft(c=>c?{...c,...p}:c);setDirty(true);}
 async function save(){if(!draft||!data)return;setBusy(true);setError('');try{const r=await fetch('/api/marketing/plan?view=work',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:crypto.randomUUID(),expectedVersion:data.version,campaign:draft,create:creating})}),b=await r.json();if(!r.ok)throw new Error(b.error);setData(b.data);setDraft(b.data.campaigns.find((c:Campaign)=>c.id===draft.id));setDirty(false);setCreating(false);setNotice('施策の状況を保存しました。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function create(){if(!data?.goals.length)return;open({id:crypto.randomUUID(),title:'新しい施策',goalId:filter||data.goals[0].id,phase:'planned',assignee:'',hypothesis:'',change:'',comparison:'',stopRule:'',start:today(),end:today(),result:'pending',reason:'',source:'',postIds:[]},true);}
 return <section><div className="mp-toolbar"><p>施策ごとの担当・期限・作業状況と、その後の判断を管理します。</p><div className="mp-actions"><button onClick={onOkr}>目標とのつながりを見る</button>{editable&&<button className="ao-primary" disabled={!data?.goals.length||busy} onClick={create}>＋ 施策を追加</button>}</div></div>
 <div className="mp-tabs" aria-label="実行管理の表示">{[['board','状態別'],['list','一覧'],['astra','Astraの稼働']].map(([id,name])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{name}</button>)}</div>
 {error&&<div role="alert" className="ao-error">{error}<button disabled={busy} onClick={()=>{if(dirty&&!confirm('未保存の変更を破棄して最新の状態を取得しますか？'))return;void load().then(()=>{setDraft(null);setDirty(false);}).catch(e=>setError(e.message));}}>保存済みの状態を再取得</button></div>}{notice&&<p role="status">{notice}</p>}{!data&&!error&&<p role="status">施策を読み込み中…</p>}
 {view==='astra'?<div className="mp-empty"><h3>Astraの自動実行は未接続です</h3><p>この画面の施策は、人が記録する実行管理です。Astraが実行した履歴や、自動で確認した成果はまだありません。</p><p>自動実行の接続後は、実行中・確認待ち・評価待ちと、その根拠をここから追えるようにします。</p></div>:data&&<>
 <div className="mp-toolbar"><label>目標<select aria-label="目標" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">すべての目標</option>{data.goals.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label>作業状況<select aria-label="作業状況で絞り込む" value={phase} onChange={e=>setPhase(e.target.value)}><option value="all">すべて</option>{Object.entries(phaseNames).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><span>{campaigns.length}件 / 終了予定日を過ぎた施策 {campaigns.filter(c=>overdue(c,today())).length}件</span></div>
 <CampaignCharts campaigns={campaigns} note="選択した目標・作業状況に一致する施策を集計しています。"/>
 {!data.goals.length?<div className="mp-empty"><h3>先に目標を登録してください</h3><p>施策を目標へ結び付けて、目的を見失わずに管理します。</p><button onClick={onSettings}>目標を登録</button></div>:!campaigns.length?<div className="mp-empty"><h3>この条件の施策はありません</h3><p>施策を追加するか、目標・作業状況の絞り込みを変えてください。</p></div>:view==='board'?<div className="mp-board">{(Object.keys(phaseNames) as Phase[]).filter(p=>(phase==='all'||phase===p)&&(p!=='unrecorded'||campaigns.some(c=>!c.phase))).map(p=><section key={p}><h3>{phaseNames[p]} <small>{campaigns.filter(c=>campaignPhase(c)===p).length}</small></h3>{campaigns.filter(c=>campaignPhase(c)===p).map(c=><button className="mp-task" key={c.id} onClick={()=>open(c)}><strong>{c.title}</strong><small>{data.goals.find(g=>g.id===c.goalId)?.title}</small><span>{c.assignee||'担当未登録'}</span><span className={overdue(c,today())?'mp-overdue':''}>{c.end}まで{overdue(c,today())?' / 予定日超過':''}</span><small>結果の判断：{decisions[c.result]}</small></button>)}</section>)}</div>:<div className="mp-table"><table><thead><tr><th>施策</th><th>目標</th><th>担当</th><th>作業状況</th><th>終了予定</th><th>結果の判断</th></tr></thead><tbody>{campaigns.map(c=><tr key={c.id}><th><button onClick={()=>open(c)}>{c.title}</button></th><td>{data.goals.find(g=>g.id===c.goalId)?.title}</td><td>{c.assignee||'未登録'}</td><td>{phaseNames[campaignPhase(c)]}</td><td>{c.end}</td><td>{decisions[c.result]}</td></tr>)}</tbody></table></div>}
 </>}
 {draft&&<section className="mp-detail" aria-label="施策の詳細"><div className="mp-toolbar"><h3 ref={detailHeading} tabIndex={-1}>{creating?'施策を追加':draft.title}</h3><button disabled={busy} onClick={()=>{if(dirty&&!confirm('未保存の変更を破棄して閉じますか？'))return;setDraft(null);setDirty(false);}}>詳細を閉じる</button></div><fieldset disabled={busy||!editable} className="mp-editor"><label>施策名<input maxLength={100} value={draft.title} onChange={e=>patch({title:e.target.value})}/></label><label>つながる目標<select value={draft.goalId} onChange={e=>patch({goalId:e.target.value})}>{data?.goals.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label>担当<input maxLength={100} value={draft.assignee??''} onChange={e=>patch({assignee:e.target.value})}/></label><label>作業状況<select aria-label="作業状況" value={draft.phase??''} onChange={e=>patch({phase:e.target.value as Campaign['phase']})}><option value="" disabled>状況未登録</option>{Object.entries(phaseNames).filter(([id])=>id!=='unrecorded').map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>開始予定日<input type="date" value={draft.start} onChange={e=>patch({start:e.target.value})}/></label><label>終了・評価予定日<input type="date" value={draft.end} onChange={e=>patch({end:e.target.value})}/></label><label className="mp-wide">変えること<textarea rows={3} value={draft.change} onChange={e=>patch({change:e.target.value})}/></label><details className="mp-wide"><summary>仮説・比較・停止条件</summary>{([['hypothesis','仮説'],['comparison','比較条件'],['stopRule','停止条件']] as const).map(([id,name])=><label key={id}>{name}<textarea value={draft[id]} onChange={e=>patch({[id]:e.target.value})}/></label>)}</details><details className="mp-wide"><summary>結果と振り返り</summary><label>結果の判断<select value={draft.result} onChange={e=>patch({result:e.target.value as Campaign['result']})}>{Object.entries(decisions).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>結果の出典<textarea value={draft.source} onChange={e=>patch({source:e.target.value})}/></label><label>判断の理由<textarea value={draft.reason} onChange={e=>patch({reason:e.target.value})}/></label></details></fieldset><p className="mp-muted">作業完了と、成果が出たかの判断は別に記録します。外部への配信やAstraの起動は行いません。</p>{editable&&<button className="ao-primary" disabled={busy||(!dirty&&!creating)} onClick={()=>void save()}>{busy?'保存中…':'施策を保存'}</button>}</section>}
 </section>;
}
