'use client';
import FunnelCanvas from './funnel-canvas';
import { useState } from 'react';
import type { BusinessData } from '@/lib/marketing-business/types';
import { sourceNames, consultationStages, stagesFromNames, type ProjectFunnel } from '@/lib/marketing-business/funnels';
const uid=()=>crypto.randomUUID();
export default function FunnelRegistry({data,onChange}:{data:BusinessData;onChange:(d:BusinessData)=>void}){
 const projects=data.projects??[],funnels=data.funnels??[];
 const [selected,setSelected]=useState(''),[custom,setCustom]=useState(''),[error,setError]=useState('');
 const project=projects.find(p=>p.id===selected)??projects[0];
 function patchFunnel(id:string,patch:Partial<ProjectFunnel>){onChange({...data,funnels:funnels.map(f=>f.id===id?{...f,...patch}:f)});}
 function addFunnel(source:ProjectFunnel['source'],names=source==='ads'?['広告','商品ページ','購入']:['SNS投稿','LINE登録','個別相談','成約'],name=sourceNames[source]+'の導線'){if(!project)return;let stages;try{stages=stagesFromNames(names,uid);setError('');}catch(e){setError((e as Error).message);return;}onChange({...data,funnels:[...funnels,{id:uid(),projectId:project.id,name,source,medium:'',status:'draft',goalIds:[],notes:'',stages}]});}
 return <><p>プロジェクトごとに、使っている導線を登録します。SNSと広告、媒体や商品ごとに複数のファネルを作れます。登録だけでは配信や自動計測は始まりません。</p><div className="ao-actions"><label>プロジェクト<select value={project?.id??''} onChange={e=>setSelected(e.target.value)}><option value="" disabled>選択してください</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button onClick={()=>{const id=uid();onChange({...data,projects:[...projects,{id,name:'新しいプロジェクト',product:'',objective:''}]});setSelected(id);}}>プロジェクトを追加</button></div>
 {project&&<><fieldset className="ao-note"><legend>プロジェクトの設定</legend>{([['name','プロジェクト名'],['product','扱う商品・サービス'],['objective','このプロジェクトで目指す状態']] as const).map(([key,label])=><label key={key}>{label}<input value={project[key]} onChange={e=>onChange({...data,projects:projects.map(p=>p.id===project.id?{...p,[key]:e.target.value}:p)})}/></label>)}</fieldset><div className="ao-actions"><button onClick={()=>addFunnel('sns')}>SNS流入のファネルを追加</button><button onClick={()=>addFunnel('ads')}>広告流入のファネルを追加</button><button onClick={()=>addFunnel('other',consultationStages,'LINE登録から面談・成約')}>LINE登録→3回の面談→成約を追加（7段階）</button></div><p>LINE登録 → 面談申込 → 予約 → 着座 → 2回目面談 → 3回目面談 → 成約。流入の種類は追加後に選べます。</p><details><summary>段階名を入力してまとめて追加</summary><label>1行に1段階（2〜30段階）<textarea value={custom} onChange={e=>setCustom(e.target.value)} placeholder={consultationStages.join('\n')}/></label><button type="button" onClick={()=>addFunnel('other',custom.split(/\r?\n/).map(n=>n.trim()).filter(Boolean),'新しいファネル')}>この順序でファネルを追加</button></details>{error&&<p role="alert">{error}</p>}
 {!funnels.some(f=>f.projectId===project.id)&&<p>使っている導線を追加してください。段階の名前・数・順序は変更できます。</p>}
 {funnels.filter(f=>f.projectId===project.id).map(f=>{const patch=(p:Partial<ProjectFunnel>)=>patchFunnel(f.id,p);return <fieldset className="ao-note" key={f.id}><legend>{f.name}</legend><div className="ao-business-fields"><label>ファネル名<input value={f.name} onChange={e=>patch({name:e.target.value})}/></label><label>流入の種類<select value={f.source} onChange={e=>patch({source:e.target.value as ProjectFunnel['source']})}>{Object.entries(sourceNames).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>媒体・入口<input placeholder="例：Instagram、Meta広告、Google広告" value={f.medium} onChange={e=>patch({medium:e.target.value})}/></label><label>運用状態<select value={f.status} onChange={e=>patch({status:e.target.value as ProjectFunnel['status']})}><option value="draft">準備中</option><option value="active">運用中</option><option value="paused">停止中</option></select></label></div>
 <fieldset><legend>関連する数値目標</legend>{data.goals.length?data.goals.map(g=><label key={g.id}><input type="checkbox" checked={f.goalIds.includes(g.id)} disabled={data.campaigns.some(c=>c.funnelId===f.id&&c.goalId===g.id)} onChange={e=>patch({goalIds:e.target.checked?[...f.goalIds,g.id]:f.goalIds.filter(id=>id!==g.id)})}/>{g.title}</label>):<p>「目標設定」で登録した数値目標を選べます。</p>}</fieldset>
 <FunnelCanvas funnel={f} onChange={patch}/><label>設計の意図・分岐の条件<textarea value={f.notes} onChange={e=>patch({notes:e.target.value})}/></label><p className="ao-small">図のつながりで分岐を登録できます。分岐する条件はここに残してください。停止中への変更は登録上の状態で、外部の広告や配信を停止しません。</p></fieldset>;})}</>}
 </>;
}
