'use client';
import { useId, useRef, useState } from 'react';
import { connectionsFor, type ProjectFunnel, type FunnelStage } from '@/lib/marketing-business/funnels';
const parts=['SNS投稿','広告','LINE登録','面談申込','予約','着座','2回目面談','3回目面談','LINE','メルマガ','記事','商品ページ','説明会','面談','購入','成約'];
const position=(s:FunnelStage,i:number)=>s.position??{x:80+(i%2)*260,y:60+Math.floor(i/2)*190};
export default function FunnelCanvas({funnel:f,onChange}:{funnel:ProjectFunnel;onChange:(patch:Partial<ProjectFunnel>)=>void}){
 const board=useRef<HTMLDivElement>(null),drag=useRef<{id:string;x:number;y:number;left:number;top:number}|null>(null);
 const [selected,setSelected]=useState(''),[from,setFrom]=useState(''),[message,setMessage]=useState('');
 const marker=useId().replace(/:/g,'');const edges=connectionsFor(f),stage=f.stages.find(s=>s.id===selected);
 const width=Math.max(800,...f.stages.map((s,i)=>position(s,i).x+250)),height=Math.max(600,...f.stages.map((s,i)=>position(s,i).y+220));
 function add(name:string,x=80,y=60){if(f.stages.length>=30)return;const id=crypto.randomUUID();onChange({connections:edges,stages:[...f.stages,{id,name,metric:name+'に進んだ人数',action:'',url:'',position:{x:Math.min(3000,Math.max(0,x)),y:Math.min(6000,Math.max(0,y))}}]});setSelected(id);}
 function connect(to:string){if(!from)return;if(from===to){setMessage('別の部品を選んでください。');return;}if(edges.some(e=>e.from===from&&e.to===to)){setMessage('すでにつながっています。');setFrom('');return;}onChange({connections:[...edges,{id:crypto.randomUUID(),from,to}]});setFrom('');setMessage('つながりを追加しました。');}
 return <div className="ao-builder"><details className="ao-builder-palette"><summary>＋ 段階を追加</summary><p>クリックで追加。図へドラッグして置くこともできます。</p><div className="ao-builder-parts">{parts.map(name=><button type="button" draggable disabled={f.stages.length>=30} key={name} onDragStart={e=>e.dataTransfer.setData('application/x-funnel-part',name)} onClick={()=>add(name,80,Math.min(5800,f.stages.length*80))}>{name}</button>)}</div></details><div className="ao-builder-main"><div className="ao-actions"><strong>ファネルの組み立て</strong><button type="button" onClick={()=>onChange({stages:f.stages.map((s,i)=>({...s,position:{x:80+(i%3)*250,y:70+Math.floor(i/3)*190}}))})}>配置を整える</button><button type="button" onClick={()=>onChange({stages:f.stages.map((s,i)=>({...s,position:{x:80,y:50+i*180}}))})}>縦一列に並べる</button><span>{f.stages.length} / 30段階</span>{from&&<button type="button" onClick={()=>setFrom('')}>接続をやめる</button>}</div><p className="ao-small">部品の見出しをつかんで移動。「次の段階につなぐ」を押して、相手の「接続先にする」を選びます。複数につなげば分岐になります。</p><p role="status">{from?`${f.stages.find(s=>s.id===from)?.name}の次に進む部品を選んでください。`:message}</p><div className="ao-builder-scroll"><div ref={board} className="ao-builder-board" style={{width,height}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const name=e.dataTransfer.getData('application/x-funnel-part');if(!parts.includes(name))return;const r=e.currentTarget.getBoundingClientRect();add(name,e.clientX-r.left-90,e.clientY-r.top-25);}}>
 <svg className="ao-builder-wires" width={width} height={height} aria-hidden="true"><defs><marker id={marker} markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#4877a6"/></marker></defs>{edges.map(e=>{const a=f.stages.findIndex(s=>s.id===e.from),b=f.stages.findIndex(s=>s.id===e.to);if(a<0||b<0)return null;const p=position(f.stages[a],a),q=position(f.stages[b],b);return <path key={e.id} d={`M${p.x+100},${p.y+148} C${p.x+100},${p.y+165} ${q.x+100},${q.y-50} ${q.x+100},${q.y}`} stroke="#4877a6" strokeWidth="2" fill="none" markerEnd={`url(#${marker})`}/>;})}</svg>
 {f.stages.map((s,i)=>{const p=position(s,i);return <div key={s.id} className={`ao-builder-node ${selected===s.id?'is-selected':''}`} style={{left:p.x,top:p.y}}><button type="button" className="ao-node-in" style={{visibility:from?'visible':'hidden'}} disabled={!from} onClick={()=>connect(s.id)} aria-label={`${s.name}へつなぐ`}>接続先にする</button><button type="button" className="ao-node-handle" aria-label={`${s.name}を移動・編集`} onClick={()=>setSelected(s.id)} onKeyDown={e=>{const delta:Record<string,[number,number]>={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]};if(!delta[e.key])return;e.preventDefault();const [x,y]=delta[e.key];onChange({stages:f.stages.map(n=>n.id===s.id?{...n,position:{x:Math.max(0,Math.min(3000,p.x+x)),y:Math.max(0,Math.min(6000,p.y+y))}}:n)});}} onPointerDown={e=>{if(e.button!==0)return;setSelected(s.id);drag.current={id:s.id,x:e.clientX,y:e.clientY,left:p.x,top:p.y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(d?.id!==s.id)return;onChange({stages:f.stages.map(n=>n.id===s.id?{...n,position:{x:Math.max(0,Math.min(3000,d.left+e.clientX-d.x)),y:Math.max(0,Math.min(6000,d.top+e.clientY-d.y))}}:n)});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>{s.name}<small>{s.metric}</small></button><button type="button" className="ao-node-out" aria-pressed={from===s.id} onClick={()=>{setFrom(s.id);setMessage('');}}>次の段階につなぐ ↓</button></div>;})}
 </div></div><details><summary>つながりの一覧・解除（{edges.length}件）</summary>{edges.map(e=><div key={e.id} className="ao-actions"><span>{f.stages.find(s=>s.id===e.from)?.name} → {f.stages.find(s=>s.id===e.to)?.name}</span><button type="button" onClick={()=>onChange({connections:edges.filter(x=>x.id!==e.id)})}>このつながりを外す</button></div>)}</details></div>
 {stage&&<aside className="ao-builder-inspector"><strong>選択した部品</strong>{([['name','名前'],['metric','見る数字'],['action','次に促す行動'],['url','ページのURL']] as const).map(([key,label])=><label key={key}>{label}<input value={stage[key]} onChange={e=>onChange({stages:f.stages.map(s=>s.id===stage.id?{...s,[key]:e.target.value}:s)})}/></label>)}<button type="button" disabled={f.stages.length<=2} onClick={()=>{onChange({stages:f.stages.filter(s=>s.id!==stage.id),connections:edges.filter(e=>e.from!==stage.id&&e.to!==stage.id)});setSelected('');setFrom('');}}>部品を外す</button><p className="ao-small">変更後はページ下の「このページの変更を保存」を押してください。</p></aside>}
 </div>;
}
