'use client';
import {useEffect,useRef,useState} from 'react';
import {useIdentity} from '../company/session';
import {useBusinessFetch} from './business-context';
import {measures,type Measure} from '@/lib/analytics/model';
import {metricStatusNames,type MetricPolicy,type MetricResult,type Binding} from '@/lib/measurement/model';
import {initialRange,rememberRange,validRange,type DateRange} from '@/lib/date-range';
import RangePicker from './date-range';
import './measurement.css';
import {DetailValue,DataDetailDrawer,type DataDetail} from './data-detail';
import {MetricIcon} from '../components/dashboard-ui';
import {SelectableChart} from '../components/data-charts';
import {daysIn} from '@/lib/ads/reporting';
import TrackingDiagnostics from './tracking-diagnostics';
type Choice={ads:{id:string;name:string;currency:string;timezone:string}[];utage:{connectionId:string;label:string;funnelId:string;pageId:string;name:string}[];funnels:{id:string;name:string}[];sources:string[]};
type Result={metrics:Record<Measure,MetricResult>;policy:MetricPolicy|null;choices:Choice|null};
const fmt=(v:number|null)=>v===null?'未取得':v.toLocaleString('ja-JP',{maximumFractionDigits:1});
export default function MeasurementPanel({range:given,refresh=0,settingsOnly=false,onSettings,onAnalysis,onSources,onDirtyChange}:{range?:DateRange;refresh?:number;settingsOnly?:boolean;onSettings?:()=>void;onSources?:()=>void;onAnalysis?:(funnel?:string)=>void;onDirtyChange?:(v:boolean)=>void}){
 const fetch=useBusinessFetch(),user=useIdentity(),[ownRange,setOwnRange]=useState(initialRange),range=given??ownRange;
 const [data,setData]=useState<Result|null>(null),[policy,setPolicy]=useState<MetricPolicy|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[revision,setRevision]=useState(0);
 const [detail,setDetail]=useState<DataDetail|null>(null),detailRequest=useRef(0);
 const pending=useRef<string|null>(null);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 useEffect(()=>{onDirtyChange?.(dirty);return()=>onDirtyChange?.(false);},[dirty,onDirtyChange]);
 useEffect(()=>{const c=new AbortController();setData(null);setPolicy(null);setError('');if(!validRange(range))return;setBusy(true);void (async()=>{try{const r=await fetch('/api/marketing/measurement?'+new URLSearchParams({...range,...(!settingsOnly?{charts:'1'}:{})}),{signal:c.signal,cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error??'取得できませんでした。');if(!c.signal.aborted){setData(b);setPolicy(b.policy);setDirty(false);pending.current=null;}}catch(e){if(!c.signal.aborted)setError((e as Error).message);}finally{if(!c.signal.aborted)setBusy(false);}})();return()=>c.abort();},[fetch,range.start,range.end,refresh,revision]);
 function patch(key:Measure,b:Binding){if(!policy)return;setPolicy({...policy,metrics:{...policy.metrics,[key]:b}});setDirty(true);setNotice('');pending.current=null;}
 async function save(){if(!policy||!dirty||busy)return;setBusy(true);setError('');pending.current??=JSON.stringify({policy,expectedVersion:policy.version,requestId:crypto.randomUUID()});try{const r=await fetch('/api/marketing/measurement',{method:'POST',headers:{'Content-Type':'application/json'},body:pending.current}),b=await r.json();if(!r.ok)throw new Error(b.error??'保存できませんでした。');setPolicy(b.policy);setDirty(false);pending.current=null;setNotice('保存しました。');setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{detailRequest.current++;setDetail(null);},[fetch,range.start,range.end,refresh,revision]);
 async function openDetail(key:Measure){if(!data)return;const request=++detailRequest.current,m=data.metrics[key];const title=measures[key],unit=['sales','registrations'].includes(key)?'件':'円';setDetail({title,value:fmt(m.value)+(m.value===null?'':unit),context:[range.start+'〜'+range.end,m.source+' / '+metricStatusNames[m.status]],columns:[],rows:[],loading:true});
 try{const r=await fetch('/api/marketing/measurement?'+new URLSearchParams({...range,detail:key}),{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error);if(request!==detailRequest.current)return;const latest:MetricResult=b.metrics[key];const changed=latest.value!==m.value||latest.status!==m.status||b.policy?.version!==data.policy?.version;
 setDetail({title,value:fmt(latest.value)+(latest.value===null?'':unit),context:[range.start+'〜'+range.end,latest.source+' / '+metricStatusNames[latest.status],latest.coveredDays+' / '+latest.expectedDays+'日分',...(changed?['表示後にデータまたは取得元が更新されました。最新の明細です。']:[]),...(latest.recordedValue!==null&&latest.value===null?['取得済みの小計：'+fmt(latest.recordedValue)+unit+'。期間全体の値ではありません。']:[])],columns:['日付',title+'（'+unit+'）','定義','取得日時'],rows:(latest.points??[]).map(p=>[p.date,p.value,p.definition,p.collectedAt]),note:latest.error??latest.definition});
 }catch(e){if(request===detailRequest.current)setDetail({title,columns:[],rows:[],error:e instanceof Error?e.message:'取得できませんでした。'});}}
 const choices=data?.choices;
 return <section className="measurement-panel" aria-label="正式な取得元と計測状態">
 {settingsOnly&&<><RangePicker value={range} onChange={r=>{if(dirty&&!confirm('未保存の取得元設定を破棄して期間を変えますか？'))return;setOwnRange(r);rememberRange(r);}}/></>}
 <div className="mp-toolbar"><h3>{settingsOnly?'取得元と計測状態':'事業の正式な指標'}</h3>{!settingsOnly&&onSettings&&<button onClick={onSettings}>取得元を確認・設定</button>}</div>
 {busy&&<p role="status">計測状態を確認中…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {data&&<><div className="measurement-cards">{(Object.keys(measures) as Measure[]).map(key=>{const m=data.metrics[key],binding=data.policy?.metrics[key],unit=['registrations','sales'].includes(key)?'件':'円';return <article key={key} className={'metric-'+m.status}><small><MetricIcon metric={key}/>{binding?.kind==='utage'?(key==='sales'?'購入件数':key==='revenue'?'UTAGEの売上':measures[key]):measures[key]}</small><strong><DetailValue label={measures[key]} onClick={()=>void openDetail(key)}>{fmt(m.value)}{m.value!==null&&<span>{unit}</span>}</DetailValue></strong><span className="metric-state">{metricStatusNames[m.status]}{m.error?' / 接続を確認':''}</span><p>{m.source}</p><p>{m.coveredDays} / {m.expectedDays}日分{m.missingValues?' / 指標欠測あり':''}</p><details><summary>定義と取得状況</summary><p>{m.definition||'取得済みの定義がありません。'}</p><p>最終取得：{m.collectedAt?new Date(m.collectedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'なし'}</p>{m.error&&<p role="alert">{m.error}</p>}{m.value===null&&m.recordedValue!==null&&<p>記録済みの小計：{fmt(m.recordedValue)}{unit}。期間全体の値としては採用していません。</p>}</details>{onAnalysis&&binding?.kind==='import'&&<button onClick={()=>onAnalysis(binding.funnelId||undefined)}>取込実績を開く</button>}{binding?.kind!=='import'&&onSettings&&<button onClick={onSettings}>取得元を確認</button>}</article>;})}</div>
 {!settingsOnly&&<div className="dc-layout"><SelectableChart title="正式な指標の日別推移" kind="line" series={(Object.keys(measures) as Measure[]).map(key=>({id:key,label:measures[key],unit:['sales','registrations'].includes(key)?'件':'円',points:daysIn(range.start,range.end).map(date=>{const p=data.metrics[key].points?.filter(p=>p.date===date)??[];return {id:date,date,label:date,value:p.length===1?p[0].value:null,note:data.metrics[key].source};})}))} onSelect={(_,key)=>void openDetail(key as Measure)}/><SelectableChart title="取得状況" series={[{id:'coverage',label:'記録がある日数',unit:'日',points:(Object.keys(measures) as Measure[]).map(key=>({id:key,label:measures[key],value:data.metrics[key].coveredDays,note:metricStatusNames[data.metrics[key].status]+' / '+data.metrics[key].expectedDays+'日'}))}]} onSelect={key=>void openDetail(key as Measure)}/></div>}
 <details><summary>集計について</summary><p>未記録の日は0にしません。広告費は媒体の配信日、UTAGEは成果の発生日が基準です。別の取得元同士を割ったCPAやROASは、顧客の帰属を確認するまで表示しません。</p></details></>}
 {settingsOnly&&policy&&choices&&user.role==='owner'&&<details className="measurement-editor"><summary>{dirty?'取得元を編集（未保存）':'取得元を編集'}</summary><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}><legend>指標の取得元を選ぶ</legend>{(Object.keys(measures) as Measure[]).map(key=>{const b=policy.metrics[key];return <fieldset key={key} className="measurement-binding"><legend>{measures[key]}</legend><label>取得元<select value={b.kind} onChange={e=>patch(key,e.target.value==='import'?{kind:'import',source:'',funnelId:''}:e.target.value==='ads'?{kind:'ads',connectionIds:[]}:{kind:'utage',connectionId:'',funnelId:'',pageId:''})}><option value="import">手入力・CSVの実績</option>{key==='cost'&&<option value="ads">広告API</option>}{['revenue','sales','registrations'].includes(key)&&<option value="utage">UTAGEのページ</option>}</select></label>
 {b.kind==='import'&&<><label>出典<select value={b.source} onChange={e=>patch(key,{...b,source:e.target.value})}><option value="">すべての出典</option>{choices.sources.map(s=><option key={s}>{s}</option>)}</select></label><label>ファネル<select value={b.funnelId} onChange={e=>patch(key,{...b,funnelId:e.target.value})}><option value="">すべて</option>{choices.funnels.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label></>}
 {b.kind==='ads'&&<><fieldset><legend>広告アカウント（複数選択）</legend>{choices.ads.filter(a=>a.currency==='JPY'&&a.timezone==='Asia/Tokyo').map(a=><label key={a.id}><input type="checkbox" checked={b.connectionIds.includes(a.id)} onChange={e=>patch(key,{...b,connectionIds:e.target.checked?[...b.connectionIds,a.id]:b.connectionIds.filter(id=>id!==a.id)})}/>{a.name}</label>)}</fieldset><details><summary>選択できるアカウント</summary><p>円建て・日本時間の接続のみ。全接続のデータが揃った期間だけ合算します。</p></details></>}
 {b.kind==='utage'&&<><label>ファネル内のページ<select required value={b.pageId?JSON.stringify([b.connectionId,b.pageId]):''} onChange={e=>{const p=choices.utage.find(p=>JSON.stringify([p.connectionId,p.pageId])===e.target.value);if(p)patch(key,{kind:'utage',connectionId:p.connectionId,funnelId:p.funnelId,pageId:p.pageId});}}><option value="">選択してください</option>{choices.utage.map(p=><option value={JSON.stringify([p.connectionId,p.pageId])} key={JSON.stringify([p.connectionId,p.pageId])}>{p.label} / {p.name} / {p.funnelId}</option>)}</select></label>{!choices.utage.length&&<p>ページが未取得です</p>}<details><summary>ページが見つからないとき</summary><p>UTAGEの接続でファネルを選び、数字を取得してください。全ページを合算しません。</p></details></>}
 </fieldset>;})}<button type="submit" disabled={!dirty}>取得元を保存</button><button type="button" onClick={()=>{if(dirty&&!confirm('未保存の変更を破棄して再読込しますか？'))return;setRevision(v=>v+1);}}>保存済み設定を再読込</button></fieldset></form></details>}
 {settingsOnly&&<TrackingDiagnostics range={range} view="routes" onSetup={onSources}/>}
 {settingsOnly&&user.role!=='owner'&&<p>取得元の変更は全体管理者が行います。</p>}
 <DataDetailDrawer data={detail} onClose={()=>{detailRequest.current++;setDetail(null);}}/>
 </section>;
}
