'use client';
import {useBusinessFetch} from './business-context';
import { useEffect, useState } from 'react';
import type { MediaAsset } from '@/lib/postiz/media';
export const mediaUrl=(id:string)=>`/api/marketing/postiz/media?id=${encodeURIComponent(id)}`;
export function MediaPreview({asset}:{asset:MediaAsset}){return asset.mime.startsWith('video/')?<video src={mediaUrl(asset.id)} controls preload="metadata" aria-label={asset.name}/>:<img src={mediaUrl(asset.id)} alt={asset.name} loading="lazy"/>;}
export default function MediaPicker({ids,thumbnailId,onChange,onThumbnail,disabled,onAssets}:{ids:string[];thumbnailId?:string;onChange:(ids:string[])=>void;onThumbnail?:(id:string|undefined)=>void;disabled:boolean;onAssets:(assets:MediaAsset[])=>void}){
 const fetch=useBusinessFetch();
 const [assets,setAssets]=useState<MediaAsset[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[usage,setUsage]=useState('');
 async function load(){try{const r=await fetch('/api/marketing/postiz/media',{cache:'no-store'}),data=await r.json();if(!r.ok)throw new Error(data.error);setAssets(data.assets);onAssets(data.assets);}catch(e){setError(e instanceof Error?e.message:'素材を取得できません。');}}
 useEffect(()=>{void load();},[]);
 async function upload(file:File){setError('');if(file.size>256*1024*1024){setError('この版の保存上限は256MBです。');return;}setBusy(true);setProgress(0);try{
  await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/marketing/postiz/media');xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.setRequestHeader('X-File-Name',encodeURIComponent(file.name));xhr.setRequestHeader('X-File-Usage',encodeURIComponent(usage||'未確認'));xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100));};xhr.onload=()=>{try{const data=JSON.parse(xhr.responseText);if(xhr.status>=300)throw new Error(data.error);resolve();}catch(e){reject(e);}};xhr.onerror=()=>reject(new Error('素材の保存結果を確認できません。'));xhr.timeout=180000;xhr.ontimeout=()=>reject(new Error('素材の保存が時間内に完了しませんでした。'));xhr.send(file);});await load();
 }catch(e){setError(e instanceof Error?e.message:'保存できません。');}finally{setBusy(false);}}
 return <section className="ao-media"><h4>画像・動画</h4><p className="ao-small">JPEG・PNG・MP4、1ファイル256MBまで。このMacに保存し、投稿の実行時にPostizへ転送します。</p><label>素材の利用条件<input value={usage} onChange={e=>setUsage(e.target.value)} placeholder="自社で撮影、購入済み素材など" maxLength={1000}/></label><label>素材を追加<input type="file" accept="image/jpeg,image/png,video/mp4" disabled={disabled||busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value='';}}/></label>{busy&&<p role="status">{progress<100?`保存中 ${progress}%`:'ファイルの内容を検査しています…'}</p>}{error&&<p role="alert" className="ao-error">{error}</p>}
 <div className="ao-media-grid">{assets.map(a=><article key={a.id}><MediaPreview asset={a}/><strong>{a.name}</strong><small>{a.width}×{a.height} · {(a.size/1024/1024).toFixed(1)}MB{a.duration?` · ${Math.round(a.duration)}秒`:''}<br/>利用条件：{a.usage}</small><button type="button" disabled={disabled||busy||(!ids.includes(a.id)&&ids.length>=10)} aria-pressed={ids.includes(a.id)} onClick={()=>onChange(ids.includes(a.id)?ids.filter(id=>id!==a.id):[...ids,a.id])}>{ids.includes(a.id)?'投稿から外す':'投稿に使用'}</button>{onThumbnail&&a.mime.startsWith('image/')&&<button type="button" disabled={disabled||busy} aria-pressed={thumbnailId===a.id} onClick={()=>onThumbnail(thumbnailId===a.id?undefined:a.id)}>{thumbnailId===a.id?'表紙から外す':'表紙に使用'}</button>}</article>)}</div>
 {!!ids.length&&<ol>{ids.map((id,i)=><li key={id}>{assets.find(a=>a.id===id)?.name??'素材を確認中'} <button type="button" disabled={disabled||i===0} onClick={()=>{const next=[...ids];[next[i-1],next[i]]=[next[i],next[i-1]];onChange(next);}}>前へ</button><button type="button" disabled={disabled||i===ids.length-1} onClick={()=>{const next=[...ids];[next[i+1],next[i]]=[next[i],next[i+1]];onChange(next);}}>後ろへ</button></li>)}</ol>}
 </section>;
}
