'use client';
import { useState } from 'react';
import type { PostizDraft, PostizPost } from '@/lib/postiz/types';
import { SNS_PLATFORMS } from '@/lib/postiz/platforms';
const labels:Record<string,string>={local:'下書き',submitting:'処理中',synced:'登録済み',unknown:'結果確認中',failed:'失敗',queue:'予約済み',published:'公開済み',draft:'下書き',error:'失敗'};
export default function PostCalendar({drafts,posts,onSelect,onDate,onRemote}:{drafts:PostizDraft[];posts:PostizPost[];onSelect:(id:string)=>void;onDate:(date:string)=>void;onRemote:(post:PostizPost)=>void}){
 const [month,setMonth]=useState(()=>{const d=new Date();return d;}),[view,setView]=useState<'month'|'week'|'list'>('month'),[platform,setPlatform]=useState(''),[state,setState]=useState('');
 const localIds=new Set(drafts.flatMap(d=>d.remotePostIds));
 const entries=[...drafts.filter(d=>d.scheduleAt).map(d=>({id:d.id,title:d.title,date:d.scheduleAt!,platform:d.platform??'',state:d.reviewState==='pending'?'pending':posts.find(p=>d.remotePostIds.includes(p.id))?.state.toLowerCase()??d.syncStatus,select:()=>onSelect(d.id)})),...posts.filter(p=>!localIds.has(p.id)).map(p=>({id:p.id,title:p.content.slice(0,50),date:p.publishDate,platform:p.integration.providerIdentifier,state:p.state.toLowerCase(),select:()=>onRemote(p)}))].filter(e=>(!platform||e.platform===platform||(platform==='instagram'&&e.platform==='instagram-standalone'))&&(!state||e.state===state)).sort((a,b)=>a.date.localeCompare(b.date));
 const start=new Date(month.getFullYear(),month.getMonth(),1),end=new Date(month.getFullYear(),month.getMonth()+1,0),dayCount=view==='week'?7:Math.ceil((start.getDay()+end.getDate())/7)*7;
 const cells=Array.from({length:dayCount},(_,i)=>{const d=new Date(view==='week'?month:start);d.setDate((view==='week'?month.getDate():1)+i-d.getDay());return d;});const key=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
 return <section className="ao-calendar"><div className="ao-sectionhead"><h4>投稿カレンダー</h4><div><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-(view==='week'?0:1),view==='week'?month.getDate()-7:1))}>{view==='week'?'前週':'前月'}</button><strong> {month.getFullYear()}年{month.getMonth()+1}月 </strong><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+(view==='week'?0:1),view==='week'?month.getDate()+7:1))}>{view==='week'?'翌週':'翌月'}</button></div></div><div className="ao-actions">{(['month','week','list'] as const).map((v,i)=><button key={v} type="button" aria-pressed={view===v} onClick={()=>setView(v)}>{['月','週','一覧'][i]}</button>)}<label>SNS<select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="">すべて</option>{SNS_PLATFORMS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>状態<select value={state} onChange={e=>setState(e.target.value)}><option value="">すべて</option><option value="pending">確認待ち</option>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><p className="ao-small">{Intl.DateTimeFormat().resolvedOptions().timeZone}で表示。外部投稿は取得済み期間の範囲だけ表示します。日付から下書きを作成できます。</p>
 {view==='list'?entries.filter(e=>new Date(e.date).getFullYear()===month.getFullYear()&&new Date(e.date).getMonth()===month.getMonth()).map(e=><button type="button" key={e.id} onClick={e.select}>{new Date(e.date).toLocaleString('ja-JP')} · {e.title} · {labels[e.state]??'確認待ち'}</button>):<div className="ao-calendar-grid">{cells.map(d=><div key={key(d)} className={d.getMonth()===month.getMonth()?'':'ao-calendar-out'}><button type="button" aria-label={`${key(d)}の下書きを作る`} onClick={()=>onDate(key(d)+'T12:00')}>{d.getDate()}日</button>{entries.filter(e=>key(new Date(e.date))===key(d)).map(e=><button type="button" className="ao-calendar-entry" key={e.id} onClick={e.select}><small>{labels[e.state]??'確認待ち'}</small>{e.title}</button>)}</div>)}</div>}
 {!entries.length&&<p className="ao-small">該当する予定はありません。</p>}</section>;
}
