'use client';
import {FactCharts,CampaignCharts} from './data-visuals';
import {useEffect,useState} from 'react';
import {useBusinessFetch,usePageAccess} from './business-context';
import {initialRange,rememberRange,validRange} from '@/lib/date-range';
import {measures,total,ratio,group,previousPeriod,delta,type Fact,type Measure} from '@/lib/analytics/model';
import {phaseNames,campaignPhase,overdue} from '@/lib/marketing-business/planning';
import type {BusinessData} from '@/lib/marketing-business/types';
import type {Catalog} from '@/lib/connected/model';
import {sum,followersIn} from '@/lib/connected/model';
import RangePicker from './date-range';
const displayMeasures={revenue:measures.revenue,payments:measures.payments,cost:measures.cost,refunds:measures.refunds,registrations:measures.registrations,sales:measures.sales};
const fmt=(n:number|null)=>n===null?'未取得':n.toLocaleString('ja-JP',{maximumFractionDigits:1});
export default function SummaryDashboard({onAnalysis,onOkr,onWork,onNative}:{onAnalysis:(funnel?:string)=>void;onOkr:()=>void;onWork:()=>void;onNative:()=>void}){
 const fetch=useBusinessFetch(),nativeAccess=usePageAccess('overview'),okrAccess=usePageAccess('okr'),businessAccess=usePageAccess('business'),workAccess=usePageAccess('work');
 const [range,setRange]=useState(initialRange),[rows,setRows]=useState<Fact[]>([]),[plan,setPlan]=useState<BusinessData|null>(null),[native,setNative]=useState<Catalog|null>(null),[error,setError]=useState(''),[notes,setNotes]=useState<string[]>([]),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 const prior=validRange(range)?previousPeriod(range.start,range.end):null;
 useEffect(()=>{const controller=new AbortController();setRows([]);setPlan(null);setNative(null);setNotes([]);setError('');setBusy(false);if(!validRange(range))return;setBusy(true);
 async function get(url:string){const r=await fetch(url,{signal:controller.signal,cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error??'取得できませんでした');return b;}
 const facts=async()=>{const result:Fact[]=[];let cursor='';do{const b=await get('/api/marketing/analytics?'+new URLSearchParams({start:prior!.start,end:range.end,cursor}));result.push(...b.rows);cursor=b.nextCursor??'';if(result.length>20000)throw new Error('対象が多いため期間を短くしてください。');}while(cursor);return result;};
 void Promise.allSettled([facts(),okrAccess||businessAccess||workAccess?get('/api/marketing/plan?view='+(okrAccess||businessAccess?'okr':'work')):Promise.resolve(null),nativeAccess?get('/api/marketing/connected?action=catalog&'+new URLSearchParams(range)):Promise.resolve(null)]).then(results=>{if(controller.signal.aborted)return;const [a,b,c]=results;if(a.status==='fulfilled')setRows(a.value);else setError(a.reason.message);if(b.status==='fulfilled')setPlan(b.value?.data??null);if(c.status==='fulfilled')setNative(c.value);setNotes([...(b.status==='rejected'?['目標・施策：'+b.reason.message]:[]),...(c.status==='rejected'?['SNS・UTAGE：'+c.reason.message]:[])]);setBusy(false);});return()=>controller.abort();},[range.start,range.end,refresh,fetch,nativeAccess,okrAccess,businessAccess,workAccess]);
 const current=rows.filter(r=>r.date>=range.start&&r.date<=range.end),previous=rows.filter(r=>prior&&r.date>=prior.start&&r.date<=prior.end),days=new Set(current.map(r=>r.date)),definitions=new Set(current.map(r=>r.definition));
 const revenue=total(current,'revenue'),cost=total(current,'cost');
 return <section className="summary-dashboard"><RangePicker value={range} onChange={r=>{setRange(r);rememberRange(r);}}/><div className="mp-toolbar"><p>選択中の事業のうち、閲覧できる範囲の数字です。カードやファネルから内訳を確認できます。</p><button disabled={busy} onClick={()=>setRefresh(v=>v+1)}>最新の数字を取得</button></div>{busy?<p role="status">数字を集計中…</p>:<>{error&&<p role="alert">{error}</p>}{notes.map(n=><p role="alert" key={n}>{n}</p>)}<div className="summary-cards">{(Object.entries(displayMeasures) as [Measure,string][]).map(([key,name])=>{const value=total(current,key),change=delta(value,total(previous,key));return <button key={key} onClick={()=>onAnalysis()}><small>{name}</small><strong>{fmt(value.value)}{value.value!==null&&<em>{['sales','registrations'].includes(key)?'件':'円'}</em>}</strong><span>{value.missing?'一部未取得 / ':''}{change===null?'前期間と比較できません':`前期間の記録分との差 ${change>0?'+':''}${fmt(change)}`}</span></button>;})}</div><div className="summary-cards secondary">{[['成約1件あたりの集客費用',ratio(current,'cost','sales'),'円'],['売上 ÷ 集客費用',ratio(current,'revenue','cost')===null?null:ratio(current,'revenue','cost')!*100,'%'],['売上 − 集客費用',!revenue.missing&&!cost.missing&&revenue.value!==null&&cost.value!==null?revenue.value-cost.value:null,'円']].map(([name,value,unit])=><article key={String(name)}><small>{name}</small><strong>{fmt(value as number|null)}{value!==null&&<em>{unit}</em>}</strong></article>)}</div><p className="mp-muted">{current.length}記録・{days.size}日分／比較期間 {prior?.start}〜{prior?.end}。記録のない日は0に置き換えません。売上−集客費用は、人件費・原価などを含まない差額です。{definitions.size>1&&' 複数の集計定義を含みます。内訳で出典を確認してください。'}</p>
 {!error&&validRange(range)&&<FactCharts rows={current} onSelect={onAnalysis}/>}
 <div className="mp-toolbar"><h3>ファネル別の数字</h3><button onClick={onOkr}>ファネルの目標と施策を見る</button></div><div className="mp-table"><table><thead><tr><th>ファネル</th>{Object.values(displayMeasures).map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{group(current,'funnelId').map(([id,rs])=><tr key={id}><th><button onClick={()=>onAnalysis(id)}>{rs[0].funnel.name}</button></th>{(Object.keys(displayMeasures) as Measure[]).map(k=><td key={k}>{fmt(total(rs,k).value)}{total(rs,k).missing?' *':''}</td>)}</tr>)}</tbody></table></div>{!current.length&&<p className="mp-empty">この期間の実績はまだありません。実績の取込、または期間を変更してください。</p>}
 <h3>日別の数字</h3><div className="mp-table"><table><thead><tr><th>日付</th>{Object.values(displayMeasures).map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{group(current,'date').sort(([a],[b])=>b.localeCompare(a)).map(([date,rs])=><tr key={date}><th>{date}</th>{(Object.keys(displayMeasures) as Measure[]).map(k=><td key={k}>{fmt(total(rs,k).value)}{total(rs,k).missing?' *':''}</td>)}</tr>)}</tbody></table></div>
 {plan&&<><CampaignCharts campaigns={plan.campaigns}/><div className="mp-toolbar"><h3>実行の状況</h3><button onClick={onWork}>実行管理へ</button></div><div className="summary-cards secondary">{Object.entries(phaseNames).map(([key,name])=><article key={key}><small>{name}</small><strong>{plan.campaigns.filter(c=>campaignPhase(c)===key).length}<em>件</em></strong></article>)}</div><p className="mp-muted">施策は現在の全件の状況です。上の集計期間では絞り込みません。終了予定日超過 {plan.campaigns.filter(c=>overdue(c,new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}))).length}件。</p></>}
 {native&&<><div className="mp-toolbar"><h3>SNS・UTAGEで取得した数字</h3><button onClick={onNative}>接続先別の内訳</button></div><p className="mp-muted">上の取込実績とは別の取得元です。重複を避けるため合算しません。</p>{native.errors.map(n=><p role="alert" key={n}>{n}</p>)}<div className="summary-cards secondary">{native.groups.map(g=><article key={g.id}><small>{g.displayName} / ページ表示・登録</small><strong>{fmt(sum(g.series.map(d=>d.pv)).value)} / {fmt(sum(g.series.map(d=>d.registrationCount)).value)}</strong><span>{g.series.length}日分の取得記録</span></article>)}{native.accounts.map(a=>{const n=followersIn(a,range.start,range.end);return <article key={a.id}><small>{a.displayName||a.handle} / フォロワー</small><strong>{fmt(n.value)}</strong><span>期間内の最終取得 {n.date??'なし'}</span></article>;})}</div>{!native.groups.length&&!native.accounts.length&&<p>この事業の接続先は未登録です。</p>}</>}
 </>}</section>;
}
