'use client';
import CommerceSummary from './commerce-summary';
import JourneySummary from './journey-summary';
import MyTasks from './my-tasks';
import GoalPacePanel from './goal-pace-panel';
import MeasurementPanel from './measurement-panel';
import {AdReportSummary} from './ad-reporting-panel';
import {FactCharts,CampaignCharts} from './data-visuals';
import {useEffect,useState} from 'react';
import {useBusinessFetch,usePageAccess} from './business-context';
import {initialRange,rememberRange,validRange} from '@/lib/date-range';
import {measures,total,ratio,group,previousPeriod,delta,type Fact,type Measure} from '@/lib/analytics/model';
import {phaseNames,campaignPhase,overdue} from '@/lib/marketing-business/planning';
import type {BusinessData} from '@/lib/marketing-business/types';
import type {Catalog} from '@/lib/connected/model';
import {sum,followersIn} from '@/lib/connected/model';
import {DetailValue,useDataDetail} from './data-detail';
import {factDetail} from '@/lib/data-detail';
import RangePicker from './date-range';
const displayMeasures={revenue:measures.revenue,payments:measures.payments,cost:measures.cost,refunds:measures.refunds,registrations:measures.registrations,sales:measures.sales};
const fmt=(n:number|null)=>n===null?'未取得':n.toLocaleString('ja-JP',{maximumFractionDigits:1});
export default function SummaryDashboard({onCommerce,onAnalysis,onOkr,onWork,onNative,onAds,onMeasurement,onGoalSettings,onTasks,onJourney}:{onCommerce?:()=>void;onJourney?:()=>void;onTasks?:(campaign?:string)=>void;onGoalSettings?:()=>void;onMeasurement:()=>void;onAds:()=>void;onAnalysis:(funnel?:string)=>void;onOkr:()=>void;onWork:(campaign?:string)=>void;onNative:()=>void}){
 const detail=useDataDetail();
 const fetch=useBusinessFetch(),nativeAccess=usePageAccess('overview'),okrAccess=usePageAccess('okr'),businessAccess=usePageAccess('business'),workAccess=usePageAccess('work');
 const [range,setRange]=useState(initialRange),[rows,setRows]=useState<Fact[]>([]),[plan,setPlan]=useState<BusinessData|null>(null),[native,setNative]=useState<Catalog|null>(null),[error,setError]=useState(''),[notes,setNotes]=useState<string[]>([]),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 const prior=validRange(range)?previousPeriod(range.start,range.end):null;
 useEffect(()=>{const controller=new AbortController();detail.show(null);setRows([]);setPlan(null);setNative(null);setNotes([]);setError('');setBusy(false);if(!validRange(range))return;setBusy(true);
 async function get(url:string){const r=await fetch(url,{signal:controller.signal,cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error??'取得できませんでした');return b;}
 const facts=async()=>{const result:Fact[]=[];let cursor='';do{const b=await get('/api/marketing/analytics?'+new URLSearchParams({start:prior!.start,end:range.end,cursor}));result.push(...b.rows);cursor=b.nextCursor??'';if(result.length>20000)throw new Error('対象が多いため期間を短くしてください。');}while(cursor);return result;};
 void Promise.allSettled([facts(),okrAccess||businessAccess||workAccess?get('/api/marketing/plan?view='+(okrAccess||businessAccess?'okr':'work')):Promise.resolve(null),nativeAccess?get('/api/marketing/connected?action=catalog&'+new URLSearchParams(range)):Promise.resolve(null)]).then(results=>{if(controller.signal.aborted)return;const [a,b,c]=results;if(a.status==='fulfilled')setRows(a.value);else setError(a.reason.message);if(b.status==='fulfilled')setPlan(b.value?.data??null);if(c.status==='fulfilled')setNative(c.value);setNotes([...(b.status==='rejected'?['目標・施策：'+b.reason.message]:[]),...(c.status==='rejected'?['SNS・UTAGE：'+c.reason.message]:[])]);setBusy(false);});return()=>controller.abort();},[range.start,range.end,refresh,fetch,nativeAccess,okrAccess,businessAccess,workAccess]);
 const current=rows.filter(r=>r.date>=range.start&&r.date<=range.end),previous=rows.filter(r=>prior&&r.date>=prior.start&&r.date<=prior.end),days=new Set(current.map(r=>r.date)),definitions=new Set(current.map(r=>r.definition));
 function showFacts(title:string,records:Fact[],key:Measure){const content=factDetail(records,key);detail.show({title,value:fmt(content.sum.value)+(content.sum.missing?' *':''),context:[range.start+'〜'+range.end,'手入力・CSVの実績 / '+records.length+'記録'],columns:content.columns,rows:content.rows,note:content.sum.missing?content.sum.missing+'記録が未取得です。表示値は取得済みの小計です。':'記録済みの範囲を合計しています。'});}
 const revenue=total(current,'revenue'),cost=total(current,'cost');
 return <section className="summary-dashboard"><RangePicker value={range} onChange={r=>{setRange(r);rememberRange(r);}}/><div className="mp-toolbar"><button disabled={busy} onClick={()=>setRefresh(v=>v+1)}>更新</button></div>{busy?<p role="status">数字を集計中…</p>:<>{error&&<p role="alert">{error}</p>}{notes.map(n=><p role="alert" key={n}>{n}</p>)}<MeasurementPanel range={range} refresh={refresh} onSettings={onMeasurement} onAnalysis={onAnalysis}/>{plan&&(okrAccess||businessAccess)&&<GoalPacePanel goals={plan.goals} refresh={refresh} onSettings={onGoalSettings??onOkr}/>}{plan&&<section aria-label="対応が必要な施策"><div className="mp-toolbar"><h3>対応が必要な施策</h3><button onClick={()=>onWork()}>施策管理へ</button></div>{plan.campaigns.filter(c=>c.phase!=='done'&&(c.phase==='review'||overdue(c,new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}))||!c.phase)).sort((a,b)=>Number(b.phase==='review')-Number(a.phase==='review')||a.end.localeCompare(b.end)).slice(0,8).map(c=><article className="ao-note" key={c.id}><h4>{c.title}</h4><button onClick={()=>onWork(c.id)}>この施策を開く</button><p>{c.phase==='review'?'判断待ち':!c.phase?'状況未登録':'終了予定日超過'} / 終了予定 {c.end} / 担当 {c.assignee||'未指定'}</p></article>)}{!plan.campaigns.some(c=>c.phase!=='done'&&(c.phase==='review'||overdue(c,new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}))||!c.phase))&&<p>対応が必要な施策はありません</p>}</section>}{onCommerce&&<CommerceSummary start={range.start} end={range.end} refresh={refresh} onOpen={onCommerce}/>}<JourneySummary start={range.start} end={range.end} refresh={refresh} onOpen={onJourney}/>{onTasks&&<MyTasks onOpen={onTasks}/>}<details><summary>取込実績の集計条件</summary><p>{current.length}記録・{days.size}日分／比較期間 {prior?.start}〜{prior?.end}。記録のない日は0にしません。売上−広告費は人件費や原価を含みません。{definitions.size>1&&' 複数の定義を含みます。'}</p></details>
 {validRange(range)&&<details><summary>媒体が報告する広告実績</summary><AdReportSummary start={range.start} end={range.end} refresh={refresh} onOpen={onAds}/></details>}
 {!error&&validRange(range)&&<details><summary>手入力・CSVの取込実績のグラフ</summary><p className="mp-muted">指標で選んだ正式な取得元とは異なる場合があります。取込実績だけを表示します。</p><FactCharts rows={current} onDaySelect={(date,key)=>showFacts(date+' / '+measures[key],current.filter(r=>r.date===date),key)} onSelect={(id,key='revenue')=>showFacts(measures[key]+' / ファネル別',current.filter(r=>r.funnelId===id),key)}/></details>}
 <div className="mp-toolbar"><h3>取込実績のファネル別内訳</h3><button onClick={onOkr}>ファネルの目標と施策を見る</button></div><div className="mp-table"><table><thead><tr><th>ファネル</th>{Object.values(displayMeasures).map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{group(current,'funnelId').map(([id,rs])=><tr key={id}><th><button onClick={()=>onAnalysis(id)}>{rs[0].funnel.name}</button></th>{(Object.keys(displayMeasures) as Measure[]).map(k=><td key={k}><DetailValue label={measures[k]} onClick={()=>showFacts(measures[k]+'の内訳',rs,k)}>{fmt(total(rs,k).value)}{total(rs,k).missing?' *':''}</DetailValue></td>)}</tr>)}</tbody></table></div>{!current.length&&<p className="mp-empty">この期間の実績はまだありません。実績の取込、または期間を変更してください。</p>}
 <h3>取込実績の日別明細</h3><details><summary>日別明細を開く</summary><div className="mp-table"><table><thead><tr><th>日付</th>{Object.values(displayMeasures).map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{group(current,'date').sort(([a],[b])=>b.localeCompare(a)).map(([date,rs])=><tr key={date}><th>{date}</th>{(Object.keys(displayMeasures) as Measure[]).map(k=><td key={k}><DetailValue label={measures[k]} onClick={()=>showFacts(measures[k]+'の内訳',rs,k)}>{fmt(total(rs,k).value)}{total(rs,k).missing?' *':''}</DetailValue></td>)}</tr>)}</tbody></table></div></details>
 {plan&&<><CampaignCharts campaigns={plan.campaigns}/><div className="mp-toolbar"><h3>実行の状況</h3><button onClick={()=>onWork()}>実行管理へ</button></div><div className="summary-cards secondary">{Object.entries(phaseNames).map(([key,name])=><article key={key}><small>{name}</small><strong><DetailValue label={name+'の施策'} onClick={()=>detail.show({title:name+'の施策',context:['全期間'],columns:['施策','担当','開始','終了予定','判断結果'],rows:plan.campaigns.filter(c=>campaignPhase(c)===key).map(c=>[c.title,c.assignee||'未指定',c.start,c.end,c.result])})}>{plan.campaigns.filter(c=>campaignPhase(c)===key).length}<em>件</em></DetailValue></strong></article>)}</div><p className="mp-muted">全期間の施策 ／ 終了予定日超過 {plan.campaigns.filter(c=>overdue(c,new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}))).length}件。</p></>}
 {native&&<><div className="mp-toolbar"><h3>SNS・UTAGEで取得した数字</h3><button onClick={onNative}>接続先別の内訳</button></div><details><summary>集計について</summary><p>取込実績と重複する可能性があるため合算しません。</p></details>{native.errors.map(n=><p role="alert" key={n}>{n}</p>)}<div className="summary-cards secondary">{native.groups.map(g=><article key={g.id}><small>{g.displayName} / ページ表示・登録</small><strong><DetailValue label={g.displayName+'のページ表示と登録'} onClick={()=>detail.show({title:g.displayName+'の保存済み実績',context:[range.start+'〜'+range.end,'UTAGE日次取得'],columns:['日付','ページ表示','登録'],rows:g.series.map(d=>[d.date,d.pv,d.registrationCount]),note:'同じ人の重複を除いた人数ではありません。'})}>{fmt(sum(g.series.map(d=>d.pv)).value)} / {fmt(sum(g.series.map(d=>d.registrationCount)).value)}</DetailValue></strong><span>{g.series.length}日分の取得記録</span></article>)}{native.accounts.map(a=>{const n=followersIn(a,range.start,range.end);return <article key={a.id}><small>{a.displayName||a.handle} / フォロワー</small><strong><DetailValue label={(a.displayName||a.handle)+'のフォロワー'} onClick={()=>detail.show({title:(a.displayName||a.handle)+' / フォロワー',value:fmt(n.value),context:[range.start+'〜'+range.end,a.platform+' / @'+a.handle],columns:['取得日','フォロワー','表示'],rows:a.series.filter(d=>d.date>=range.start&&d.date<=range.end).map(d=>[d.date,d.followers,d.impressions]),note:'期間内の最終取得値です。日別のフォロワー数を合算しません。'})}>{fmt(n.value)}</DetailValue></strong><span>期間内の最終取得 {n.date??'なし'}</span></article>;})}</div>{!native.groups.length&&!native.accounts.length&&<p>この事業の接続先は未登録です。</p>}</>}
 </>}{detail.drawer}</section>;
}
