'use client';
import {useDataDetail} from './data-detail';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useBusiness,useBusinessFetch} from './business-context';
import {useIdentity} from '../company/session';
import {can} from '@/lib/access';
import {sortTasks,taskOverdue,taskPriorityNames,taskStatusNames} from '@/lib/marketing-business/planning';
import {taskMatches,visibleTaskFilters} from '@/lib/marketing-business/task-list';
import type {WorkTask} from '@/lib/marketing-business/types';

type Data={version:number;assignees:{id:string;name:string}[];campaigns:{id:string;title:string}[];tasks:WorkTask[]};
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});
const statusFilters=[['active','未完了'],['all','すべて'],...Object.entries(taskStatusNames)] as const;

export default function TasksPanel({onWork,onDirtyChange,campaignId=''}:{campaignId?:string;onWork:(campaign:string)=>void;onDirtyChange:(dirty:boolean)=>void}){
 const detail=useDataDetail();const fetch=useBusinessFetch(),business=useBusiness(),user=useIdentity(),editable=can(user,business.id,'work',true)||can(user,business.id,'business',true),detailHeading=useRef<HTMLHeadingElement>(null);
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState(campaignId?'all':'active'),[campaign,setCampaign]=useState(campaignId||'all'),[assignee,setAssignee]=useState('all'),[query,setQuery]=useState(''),[draft,setDraft]=useState<WorkTask|null>(null),[creating,setCreating]=useState(false),[dirty,setDirty]=useState(false),[savedId,setSavedId]=useState('');
 const feedback=useRef<HTMLDivElement>(null),pendingSave=useRef<{content:string;id:string}|null>(null);
 useEffect(()=>{if(error||notice){feedback.current?.focus();feedback.current?.scrollIntoView({block:'nearest'});}},[error,notice]);
 useEffect(()=>{detail.show(null);},[data,fetch]);
 function showCount(key:string,title:string){const selected=(data?.tasks??[]).filter(t=>key==='active'?t.status!=='done':key==='overdue'?taskOverdue(t,today()):t.status===key);detail.show({title,context:['全タスク / 閲覧できる範囲'],columns:['タスク','状態','担当','期限','施策'],rows:selected.map(t=>[t.title,taskStatusNames[t.status],t.assignee,t.due,data?.campaigns.find(c=>c.id===t.campaignId)?.title??'なし']),rowAction:{label:'タスクを開く',onSelect:index=>{detail.show(null);open(selected[index]);}}});}
 async function load(){setError('');const r=await fetch('/api/marketing/plan?view=tasks',{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error);setData(b.data);return b.data as Data;}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[fetch]);
 useEffect(()=>{onDirtyChange(dirty);const warn=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>{onDirtyChange(false);window.removeEventListener('beforeunload',warn);};},[dirty,onDirtyChange]);
 useEffect(()=>{if(draft){detailHeading.current?.focus();detailHeading.current?.scrollIntoView({block:'nearest'});}},[draft?.id]);
 const tasks=useMemo(()=>sortTasks((data?.tasks??[]).filter(t=>taskMatches(t,{status,campaign,assignee,query},today(),data?.assignees??[]))),[data,status,campaign,assignee,query]);
 const counts=useMemo(()=>{const all=data?.tasks??[];return{active:all.filter(t=>t.status!=='done').length,doing:all.filter(t=>t.status==='doing').length,blocked:all.filter(t=>t.status==='blocked').length,overdue:all.filter(t=>taskOverdue(t,today())).length};},[data]);
 function open(task:WorkTask,isNew=false){if(busy)return;if(dirty&&!confirm('未保存の変更があります。破棄して別のタスクを開きますか？'))return;setDraft(task);setCreating(isNew);setDirty(false);setNotice('');setError('');pendingSave.current=null;}
 function patch(value:Partial<WorkTask>){setDraft(task=>task?{...task,...value}:task);setDirty(true);}
 function create(){const self=data?.assignees.find(member=>member.id===user.id);open({id:crypto.randomUUID(),title:'',status:'todo',priority:'medium',assignee:self?.name??'',assigneeId:self?.id,due:today(),notes:'',campaignId:campaign!=='all'&&campaign!=='none'&&data?.campaigns.some(c=>c.id===campaign)?campaign:undefined},true);}
 async function saveTask(task:WorkTask,createTask=false){if(!data||busy)return;setBusy(true);setError('');setNotice('');const content=JSON.stringify({expectedVersion:data.version,task,create:createTask});if(pendingSave.current?.content!==content)pendingSave.current={content,id:crypto.randomUUID()};try{const r=await fetch('/api/marketing/plan?view=tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...JSON.parse(content),requestId:pendingSave.current.id})}),b=await r.json();if(!r.ok)throw new Error(b.error);setData(b.data);setDraft(null);setDirty(false);setCreating(false);pendingSave.current=null;setSavedId(task.id);const next=visibleTaskFilters(task,{status,campaign,assignee,query},today(),b.data.assignees);setStatus(next.status);setCampaign(next.campaign);setAssignee(next.assignee);setQuery(next.query);setNotice(createTask?'タスクを登録しました。':task.status==='done'?'タスクを完了にしました。':'タスクを保存しました。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function quickStatus(task:WorkTask,status:WorkTask['status']){if(dirty){setError('編集中のタスクを保存または閉じてから、別のタスクの状態を変更してください。');return;}if(task.status!==status)void saveTask({...task,status});}
 return <section className="task-panel"><div className="mp-toolbar"><p>日々の作業を担当・期限・優先度で整理し、必要なものだけ施策へつなげます。</p>{editable&&!draft&&<button className="ao-primary" disabled={busy||!data} onClick={create}>＋ タスクを追加</button>}</div>
 <div ref={feedback} tabIndex={-1}>{error&&<div role="alert" className="ao-error">{error}<button disabled={busy} onClick={()=>{if(dirty&&!confirm('未保存の変更を破棄して最新の状態を取得しますか？'))return;void load().then(()=>{setDraft(null);setDirty(false);}).catch(e=>setError(e.message));}}>保存済みの状態を再取得</button></div>}{notice&&<p role="status" className="ao-note">{notice}</p>}</div>{!data&&!error&&<p role="status">タスクを読み込み中…</p>}
 {data&&!draft&&<>{campaignId&&!data.campaigns.some(c=>c.id===campaignId)&&<p role="status" className="ao-note">指定した施策が見つからないか、閲覧範囲外です。施策の条件を変更してください。</p>}<div className="task-summary" aria-label="タスクの集計"><button aria-pressed={status==='active'} onClick={()=>showCount('active','未完了のタスク')}><span>未完了</span><strong>{counts.active}</strong></button><button aria-pressed={status==='doing'} onClick={()=>showCount('doing','進行中のタスク')}><span>進行中</span><strong>{counts.doing}</strong></button><button aria-pressed={status==='blocked'} onClick={()=>showCount('blocked','確認待ちのタスク')}><span>確認待ち</span><strong>{counts.blocked}</strong></button><button aria-pressed={status==='overdue'} onClick={()=>showCount('overdue','期限超過のタスク')}><span>期限超過</span><strong className={counts.overdue?'mp-overdue':''}>{counts.overdue}</strong></button></div>
 <div className="task-filters"><div className="mp-tabs" aria-label="状態で絞り込む">{statusFilters.map(([id,name])=><button key={id} aria-pressed={status===id} onClick={()=>setStatus(id)}>{name}</button>)}</div><label>検索<input type="search" value={query} placeholder="タスク名・メモ" onChange={e=>setQuery(e.target.value)}/></label><label>施策<select value={campaign} onChange={e=>setCampaign(e.target.value)}>{campaignId&&!data.campaigns.some(c=>c.id===campaignId)&&<option value={campaignId}>指定した施策（見つかりません）</option>}<option value="all">すべて</option><option value="none">施策なし</option>{data.campaigns.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>担当<select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="all">すべて</option><option value="none">担当なし</option>{data.assignees.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label></div>
 {!tasks.length?<div className="mp-empty"><h3>{data.tasks.length?'この条件のタスクはありません':'最初のタスクを登録しましょう'}</h3><p>{data.tasks.length?'状態・施策・担当・検索条件を変えてください。':'期限と担当を決めると、次に動く作業が分かります。'}</p>{editable&&!data.tasks.length&&<button onClick={create}>タスクを追加</button>}</div>:<div className="mp-table task-table"><table><thead><tr><th>タスク</th><th>状態</th><th>優先度</th><th>施策</th><th>担当</th><th>期限</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{tasks.map(task=>{const isOverdue=taskOverdue(task,today());return <tr key={task.id} className={savedId===task.id?'task-saved-row':undefined}><th data-label="タスク"><button className="task-title" disabled={busy} onClick={()=>open(task)}>{task.title}</button>{task.notes&&<small>{task.notes}</small>}</th><td data-label="状態">{editable?<select aria-label={task.title+'の状態'} disabled={busy} value={task.status} onChange={e=>quickStatus(task,e.target.value as WorkTask['status'])}>{Object.entries(taskStatusNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>:<span className={'task-status task-status-'+task.status}>{taskStatusNames[task.status]}</span>}</td><td data-label="優先度"><span className={'task-priority task-priority-'+task.priority}>{taskPriorityNames[task.priority]}</span></td><td data-label="施策">{task.campaignId?<button disabled={busy} onClick={()=>onWork(task.campaignId!)}>{data.campaigns.find(c=>c.id===task.campaignId)?.title??'関連施策'}</button>:'—'}</td><td data-label="担当">{task.assignee||'未登録'}</td><td data-label="期限"><span className={isOverdue?'mp-overdue':''}>{task.due}{isOverdue&&<small>期限超過</small>}</span></td><td data-label="操作"><button disabled={busy} onClick={()=>open(task)}>詳細</button></td></tr>;})}</tbody></table></div>}
 <p className="mp-muted">完了済みのタスクは「すべて」または「完了」で確認できます。タスクを削除せず、実行記録として残します。</p></>}
 {draft&&<section className="mp-detail" aria-label="タスクの詳細"><div className="mp-toolbar"><h3 ref={detailHeading} tabIndex={-1}>{creating?'タスクを追加':draft.title}</h3><button disabled={busy} onClick={()=>{if(dirty&&!confirm('未保存の変更を破棄して閉じますか？'))return;setDraft(null);setDirty(false);}}>一覧へ戻る</button></div><fieldset disabled={busy||!editable} className="mp-editor"><label className="mp-wide">タスク名<input autoFocus={creating} required maxLength={100} value={draft.title} onChange={e=>patch({title:e.target.value})}/></label><label>状態<select value={draft.status} onChange={e=>patch({status:e.target.value as WorkTask['status']})}>{Object.entries(taskStatusNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>優先度<select value={draft.priority} onChange={e=>patch({priority:e.target.value as WorkTask['priority']})}>{Object.entries(taskPriorityNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>担当<select value={draft.assigneeId??(draft.assignee?'legacy':'')} onChange={e=>{const member=data?.assignees.find(value=>value.id===e.target.value);patch({assigneeId:e.target.value,assignee:member?.name??''});}}><option value="">担当なし</option>{!draft.assigneeId&&draft.assignee&&<option value="legacy" disabled>現在の担当：{draft.assignee}</option>}{data?.assignees.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label>期限<input type="date" value={draft.due} onChange={e=>patch({due:e.target.value})}/></label><label className="mp-wide">関連する施策<select value={draft.campaignId??''} onChange={e=>patch({campaignId:e.target.value||undefined})}><option value="">施策に紐付けない</option>{data?.campaigns.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="mp-wide">メモ<textarea rows={4} value={draft.notes} onChange={e=>patch({notes:e.target.value})}/></label></fieldset>{draft.campaignId&&<button disabled={busy} onClick={()=>onWork(draft.campaignId!)}>紐付いた施策を見る</button>}{editable&&<button className="ao-primary" disabled={busy||!draft.title.trim()||(!dirty&&!creating)} onClick={()=>void saveTask(draft,creating)}>{busy?'保存中…':creating?'タスクを登録':'変更を保存'}</button>}</section>}
 {detail.drawer}</section>;
}
