'use client';
import {useEffect,useState} from 'react';
import {useBusinessFetch} from './business-context';
import type {DateRange} from '@/lib/date-range';
import './tracking-diagnostics.css';
type Route={id:string;name:string;provider:string;enabled:boolean;serverKey:string;browserReception:string;outcomeReception:string;lastRecorded:string|null;installation:string};
type Comparison={connection:string;campaignId:string;campaignName:string;ownSales:number|null;metaPurchases:number|null;coverage:number;expected:number;latest:string|null;status:string;reasons:string[]};
type Data={partial:boolean;mediaPartial:boolean;routes:Route[];comparisons:Comparison[];adsAccess:boolean;unmappedSales:number|null;metaProtocol:Record<string,string>;note:string};
const fmt=(n:number|null)=>n===null?'未取得':n.toLocaleString('ja-JP',{maximumFractionDigits:2});
export default function TrackingDiagnostics({range,view,onSetup}:{range:DateRange;view:'routes'|'comparison';onSetup?:()=>void}){
 const fetch=useBusinessFetch(),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setData(null);setError('');void(async()=>{try{const r=await fetch('/api/marketing/tracking-diagnostics?'+new URLSearchParams(range),{signal:c.signal,cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error??'診断を取得できませんでした。');if(!c.signal.aborted)setData(b);}catch(e){if(!c.signal.aborted)setError((e as Error).message);}})();return()=>c.abort();},[fetch,range.start,range.end,revision]);
 return <section className="tracking-diagnostics" aria-label={view==='routes'?'計測経路の診断':'自社成果とMeta報告値の比較'}><div className="mp-toolbar"><h3>{view==='routes'?'計測経路の診断':'自社成果とMeta報告値の比較'}</h3><button onClick={()=>setRevision(v=>v+1)}>更新</button></div><small className="tracking-period">{range.start}〜{range.end}</small>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">診断を読み込んでいます…</p>}{data&&<>{data.partial&&<p role="alert">集計上限を超えています。期間を短くしてください。成果件数を表示していません。</p>}{data.mediaPartial&&<p role="alert">媒体実績が集計上限を超えています。期間を短くしてください。Meta報告値を表示していません。</p>}{view==='routes'?<>{!data.routes.length?<div className="tracking-empty"><p>取得元がありません</p>{onSetup&&<button onClick={onSetup}>LP・UTAGEの取得元を登録</button>}</div>:<div className="tracking-table"><table><caption>取得元の受信状況</caption><thead><tr><th scope="col">取得元</th><th scope="col">取得</th><th scope="col">サーバーキー</th><th scope="col">LP閲覧</th><th scope="col">成果記録</th><th scope="col">期間内の最終記録</th></tr></thead><tbody>{data.routes.map(s=><tr key={s.id}><th scope="row">{s.name}<small>{s.provider==='utage'?'UTAGE':s.provider==='external'?'外部LP':'手動記録'}</small></th><td>{s.enabled?'有効':'取得停止'}</td><td>{s.serverKey}</td><td>{s.browserReception}</td><td>{s.outcomeReception}</td><td>{s.lastRecorded?new Date(s.lastRecorded).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'なし'}</td></tr>)}</tbody></table></div>}<details><summary>Metaの計測設定</summary><dl>{Object.entries(data.metaProtocol).map(([k,v])=><div key={k}><dt>{{capi:'CAPI送信',pixel:'Pixel設置',deduplication:'重複排除',matching:'照合',attribution:'広告への帰属'}[k]}</dt><dd>{v}</dd></div>)}</dl></details></>:<><p className="tracking-status">比較条件：未確認</p>{!data.adsAccess?<p>Meta報告値を比較するには、この事業の広告閲覧権限が必要です。</p>:!data.comparisons.length?<div className="tracking-empty"><p>Metaが未接続です</p>{onSetup&&<button onClick={onSetup}>Metaを接続</button>}</div>:<div className="tracking-table"><table><caption>キャンペーン別の記録値</caption><thead><tr><th scope="col">アカウント / キャンペーン</th><th scope="col">記録済み自社成約</th><th scope="col">保存済みMeta購入CV</th><th scope="col">取得日数</th><th scope="col">比較状態と確認点</th></tr></thead><tbody>{data.comparisons.map((c,i)=><tr key={[c.connection,c.campaignId,i].join(':')}><th scope="row">{c.connection}<small>{c.campaignName}</small></th><td className="tracking-number">{fmt(c.ownSales)}</td><td className="tracking-number">{fmt(c.metaPurchases)}</td><td>{c.coverage} / {c.expected}日</td><td>{c.status}<details><summary>確認が必要な条件</summary><ul>{c.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>{c.latest&&<p>最終取得：{new Date(c.latest).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}</p>}</details></td></tr>)}</tbody></table></div>}{data.adsAccess&&<p>広告IDとの対応がない成約記録：{data.unmappedSales===null?'集計不可':`${data.unmappedSales}件`}</p>}</>}<details><summary>集計について</summary><p>受信記録がない項目は、ゼロ件と確定せず未確認と表示します。成果記録には手動登録も含みます。</p>{view==='comparison'&&<p>自社は成果の発生日（日本時間）、Metaは媒体の報告日です。定義・帰属期間・日付基準が一致するまで、差分や実CPAは算出しません。広告との対応は記録時のIDを使用します。</p>}<p>{data.note}</p></details></>}</section>;
}
