'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {useBusinessFetch} from './business-context';
import type {BoardCard,BoardEdge,WhiteboardData} from '@/lib/whiteboard';
import './whiteboard.css';
const blank:WhiteboardData={version:0,cards:[],edges:[],updatedAt:''};
const colors:BoardCard['color'][]=['yellow','blue','green','pink','white'];
const colorNames={yellow:'黄',blue:'青',green:'緑',pink:'ピンク',white:'白'};
export default function WhiteboardPanel({onDirtyChange}:{onDirtyChange:(dirty:boolean)=>void}){
 const fetch=useBusinessFetch(),pendingSave=useRef<{content:string;id:string}|null>(null),boardRef=useRef<HTMLDivElement>(null),drag=useRef<{id:string;x:number;y:number;left:number;top:number}|null>(null),heading=useRef<HTMLHeadingElement>(null),marker=useId().replace(/:/g,'');
 const [data,setData]=useState<WhiteboardData|null>(null),[selected,setSelected]=useState(''),[from,setFrom]=useState(''),[zoom,setZoom]=useState(1),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[deleted,setDeleted]=useState<{card:BoardCard;edges:BoardEdge[]}|null>(null);
 const card=data?.cards.find(value=>value.id===selected),width=5200,height=3600;
 async function load(){setError('');const r=await fetch('/api/marketing/whiteboard',{cache:'no-store'}),body=await r.json();if(!r.ok)throw new Error(body.error);setData(body.data);setDirty(false);setSelected('');setFrom('');return body.data as WhiteboardData;}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[fetch]);
 useEffect(()=>{onDirtyChange(dirty);const warn=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};addEventListener('beforeunload',warn);return()=>{onDirtyChange(false);removeEventListener('beforeunload',warn);};},[dirty,onDirtyChange]);
 function update(next:WhiteboardData){if(busy)return;setData(next);setDirty(true);setNotice('');setError('');}
 function add(type:BoardCard['type']){if(!data||data.cards.length>=200)return;const id=crypto.randomUUID(),index=data.cards.length,next:BoardCard={id,type,title:type==='sticky'?'新しい付箋':type==='action'?'新しい施策':'見出し',body:'',color:type==='sticky'?'yellow':type==='action'?'blue':'white',x:80+(index%4)*240,y:80+Math.floor(index/4)*180,width:type==='text'?300:220,height:type==='text'?100:150};update({...data,cards:[...data.cards,next]});setSelected(id);setTimeout(()=>heading.current?.focus(),0);}
 function patch(value:Partial<BoardCard>){if(!data||!card)return;update({...data,cards:data.cards.map(item=>item.id===card.id?{...item,...value}:item)});}
 function connect(to:string){if(!data||!from)return;if(from===to){setError('同じカード同士はつなげません。');return;}if(data.edges.some(edge=>edge.from===from&&edge.to===to)){setNotice('そのつながりは登録済みです。');setFrom('');return;}update({...data,edges:[...data.edges,{id:crypto.randomUUID(),from,to,label:''}]});setFrom('');setNotice('カードをつなぎました。');}
 function remove(){if(!data||!card||!confirm(`「${card.title||'無題'}」をボードから外しますか？`))return;const edges=data.edges.filter(edge=>edge.from===card.id||edge.to===card.id);setDeleted({card,edges});update({...data,cards:data.cards.filter(item=>item.id!==card.id),edges:data.edges.filter(edge=>edge.from!==card.id&&edge.to!==card.id)});setSelected('');setFrom('');}
 function undo(){if(!data||!deleted)return;update({...data,cards:[...data.cards,deleted.card],edges:[...data.edges,...deleted.edges]});setSelected(deleted.card.id);setDeleted(null);}
 async function save(){if(!data||!dirty||busy)return;setBusy(true);setError('');setNotice('');const content=JSON.stringify({expectedVersion:data.version,data});if(pendingSave.current?.content!==content)pendingSave.current={content,id:crypto.randomUUID()};try{const r=await fetch('/api/marketing/whiteboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...JSON.parse(content),requestId:pendingSave.current.id})}),body=await r.json();if(!r.ok)throw new Error(body.error);setData(body.data);setDirty(false);pendingSave.current=null;setDeleted(null);setNotice('ホワイトボードを保存しました。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="wb-panel"><fieldset disabled={busy} className="mp-save-lock" aria-busy={busy}><div className="mp-toolbar"><div><p>付箋や施策を自由に配置し、関係を線でつないで整理します。</p><small>ボードは選択中の事業だけに保存されます。</small></div><div className="mp-actions"><button onClick={()=>add('sticky')}>＋ 付箋</button><button onClick={()=>add('text')}>＋ テキスト</button><button onClick={()=>add('action')}>＋ 施策カード</button><button className="ao-primary" disabled={!dirty||busy} onClick={()=>void save()}>{busy?'保存中…':'ボードを保存'}</button></div></div>
 {error&&<div role="alert" className="ao-error">{error}<button disabled={busy} onClick={()=>{if(!dirty||confirm('未保存の変更を破棄して最新のボードを取得しますか？'))void load().catch(e=>setError(e.message));}}>保存済みのボードを再取得</button></div>}{notice&&<p role="status" className="ao-note">{notice}</p>}{deleted&&<p role="status" className="wb-undo">カードを外しました。<button onClick={undo}>元に戻す</button></p>}{!data&&!error&&<p role="status">ホワイトボードを読み込み中…</p>}
 {data&&<div className="wb-layout"><div className="wb-main"><div className="wb-tools" aria-label="ボードの表示操作"><button onClick={()=>setZoom(value=>Math.max(.5,Math.round((value-.1)*10)/10))} aria-label="縮小">−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(value=>Math.min(1.5,Math.round((value+.1)*10)/10))} aria-label="拡大">＋</button><button onClick={()=>setZoom(1)}>100%に戻す</button>{from&&<button onClick={()=>setFrom('')}>接続をやめる</button>}<span>{data.cards.length}カード・{data.edges.length}本の線</span></div><p className="ao-small" role="status">{from?`${data.cards.find(value=>value.id===from)?.title}からつなぐ相手を選んでください。`:'カードをドラッグして移動できます。矢印キーでも20pxずつ動かせます。'}</p><div className="wb-viewport"><div ref={boardRef} className="wb-board" style={{width,height,transform:`scale(${zoom})`}} onPointerDown={e=>{if(e.target===e.currentTarget)setSelected('');}}>
 <svg width={width} height={height} aria-label="カードのつながり"><defs><marker id={marker} markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#526f8d"/></marker></defs>{data.edges.map(edge=>{const a=data.cards.find(value=>value.id===edge.from),b=data.cards.find(value=>value.id===edge.to);if(!a||!b)return null;const x1=a.x+a.width/2,y1=a.y+a.height/2,x2=b.x+b.width/2,y2=b.y+b.height/2;return <g key={edge.id}><path d={`M${x1},${y1} C${x1+(x2-x1)/2},${y1} ${x1+(x2-x1)/2},${y2} ${x2},${y2}`} fill="none" stroke="#526f8d" strokeWidth="2" markerEnd={`url(#${marker})`}/>{edge.label&&<text x={(x1+x2)/2} y={(y1+y2)/2-8}>{edge.label}</text>}</g>;})}</svg>
 {data.cards.map(item=><article key={item.id} className={`wb-card wb-${item.type} wb-${item.color} ${selected===item.id?'is-selected':''}`} style={{left:item.x,top:item.y,width:item.width,height:item.height}}><button className="wb-target" hidden={!from} onClick={()=>connect(item.id)} aria-label={`${item.title}へつなぐ`}>ここへつなぐ</button><button className="wb-handle" onClick={()=>setSelected(item.id)} onKeyDown={e=>{const move:Record<string,[number,number]>={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]};if(!move[e.key])return;e.preventDefault();const [x,y]=move[e.key];update({...data,cards:data.cards.map(value=>value.id===item.id?{...value,x:Math.max(0,Math.min(5000,value.x+x)),y:Math.max(0,Math.min(5000,value.y+y))}:value)});}} onPointerDown={e=>{if(e.button!==0)return;setSelected(item.id);drag.current={id:item.id,x:e.clientX,y:e.clientY,left:item.x,top:item.y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const state=drag.current;if(state?.id!==item.id)return;const x=Math.max(0,Math.min(5000,state.left+(e.clientX-state.x)/zoom)),y=Math.max(0,Math.min(5000,state.top+(e.clientY-state.y)/zoom));update({...data,cards:data.cards.map(value=>value.id===item.id?{...value,x,y}:value)});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><strong>{item.title||'無題'}</strong><span>{item.body||'内容を入力'}</span></button><button className="wb-connect" aria-pressed={from===item.id} onClick={()=>setFrom(item.id)}>線でつなぐ</button></article>)}
 </div></div></div><aside className="wb-inspector" aria-label="選択したカードの編集">{card?<><h3 ref={heading} tabIndex={-1}>カードを編集</h3><label>タイトル<input value={card.title} maxLength={100} onChange={e=>patch({title:e.target.value})}/></label><label>内容<textarea rows={6} value={card.body} maxLength={2000} onChange={e=>patch({body:e.target.value})}/></label><fieldset><legend>色</legend>{colors.map(color=><label key={color}><input type="radio" name="card-color" checked={card.color===color} onChange={()=>patch({color})}/>{colorNames[color]}</label>)}</fieldset><label>幅<input type="range" min="140" max="600" step="20" value={card.width} onChange={e=>patch({width:Number(e.target.value)})}/></label><label>高さ<input type="range" min="90" max="600" step="20" value={card.height} onChange={e=>patch({height:Number(e.target.value)})}/></label><button className="wb-remove" onClick={remove}>カードを外す</button></>:<><h3>カードを選択</h3><p>ボード上のカードを選ぶと、タイトル、内容、色、大きさを編集できます。</p></>}</aside></div>}
</fieldset> </section>;
}
