'use client';
import {useEffect,useState} from 'react';
import {useIdentity} from './session';
import RangePicker from '../marketing/date-range';
import {initialRange,rememberRange} from '@/lib/date-range';
import {can} from '@/lib/access';
import CompanyCharts from './charts';
import type {CompanySummary} from '@/lib/company';
const number=(n:number|null|undefined)=>n==null?'未取得':n.toLocaleString('ja-JP');
export default function Company(){
 const user=useIdentity(),[start,setStart]=useState(()=>initialRange().start),[end,setEnd]=useState(()=>initialRange().end),[data,setData]=useState<CompanySummary|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');fetch('/api/company?'+new URLSearchParams({start,end}),{cache:'no-store',signal:controller.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);return b;}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[start,end,retry]);
 function open(id:string,panel:string){localStorage.setItem('astra-business',id);location.href='/marketing?'+new URLSearchParams({businessId:id,panel,start,end});}
 return <main className="co-main"><div className="co-heading"><div><p className="co-eyebrow">{user.role==='owner'?'会社全体を、ひとつの画面で':'あなたの担当範囲'}</p><h1>{data?.company.name??'会社ホーム'}</h1><p>事業の状況をつかみ、気になる数字から内訳へ。</p></div><div className="co-period"><RangePicker value={{start,end}} onChange={r=>{setStart(r.start);setEnd(r.end);rememberRange(r);}}/><button onClick={()=>setRetry(n=>n+1)}>更新</button></div></div>
 <div className="co-status"><span>{user.role==='owner'?'全事業を表示':'許可された事業・案件だけを表示'}</span><span>日付：日本時間 / 手動で取り込んだ実績</span></div>
 {error&&<p className="co-error" role="alert">{error}<button onClick={()=>setRetry(n=>n+1)}>再試行</button></p>}{!data&&!error&&<p role="status">事業の数字を読み込んでいます…</p>}
 {data&&<><CompanyCharts data={data} onOpen={id=>open(id,'dashboard')}/><section><h2>事業別の実績</h2><p className="co-muted">売上・入金・返金は別の数字です。出典や定義が異なる可能性があるため、全社合計には自動で加算していません。</p>{data.businesses.length===0?<div className="co-empty"><h3>閲覧できる事業がまだありません</h3><p>全体管理者に担当する事業と画面の追加を依頼してください。</p></div>:<div className="co-table"><table><thead><tr><th>事業</th><th>確定売上</th><th>入金</th><th>返金</th><th>集客費用</th><th>成約</th><th>記録の状態</th><th>詳細</th></tr></thead><tbody>{data.businesses.map(b=><tr key={b.id}><th>{b.name}{b.restrictedProjects&&<small>許可された案件のみ</small>}</th>{(['revenue','payments','refunds','cost'] as const).map(key=><td key={key}>{!b.metrics?'閲覧対象外':<><strong>{number(b.metrics[key])}</strong>{b.metrics[key]!=null&&' 円'}<small>{b.metrics.records>b.metrics[key+'Count' as 'revenueCount'|'paymentsCount'|'refundsCount'|'costCount']!?'一部未取得':''}</small></>}</td>)}<td>{b.metrics?number(b.metrics.sales):'閲覧対象外'}</td><td>{b.metrics?<><span>{b.metrics.records}記録 / {b.metrics.days}日分</span><small>最終記録：{b.metrics.latest??'なし'}</small>{b.metrics.definitions>1&&<small className="co-warning">集計定義が複数あります</small>}</>:'詳細分析の権限なし'}</td><td>{can(user,b.id,'analytics')?<button onClick={()=>open(b.id,'dashboard')}>総合ダッシュボード</button>:<button onClick={()=>open(b.id,'')}>業務を開く</button>}</td></tr>)}</tbody></table></div>}</section>
 <div className="co-columns"><section><h2>事業の目標と改善</h2>{data.businesses.map(b=><article className="co-card" key={b.id}><div className="co-heading"><h3>{b.name}</h3>{can(user,b.id,'business')&&<button onClick={()=>open(b.id,'okr')}>目標・施策を見る</button>}</div><p>{b.objective||'目標が未登録、または閲覧範囲外です。'}</p>{b.goals.map(g=><div className="co-goal" key={g.id}><span>{g.title}</span><strong>目標 {number(g.target)}</strong><small>期限 {g.deadline}</small></div>)}{b.pendingImprovements!==null&&<p>評価待ちの改善施策：{b.pendingImprovements}件</p>}</article>)}</section><section><h2>会社の各業務</h2><a className="co-module" href="/marketing"><strong>マーケティング</strong><span>投稿・集客 → LP・販売 → リスト運用</span><small>接続した数字と実績を確認する →</small></a><div className="co-card"><h3>Astraの診断・改善</h3><p>実行接続は準備中です。自動で診断・変更・効果検証を回した結果はまだありません。</p></div>{['営業・顧客対応','財務・入金管理','人員・業務管理'].map(name=><div className="co-pending" key={name}><strong>{name}</strong><span>未接続</span></div>)}</section></div></>}
 </main>;
}
